### ISSUE TITLE
New bugs regarding the Prime Update

### ISSUE THREAD

**Issue by TheRealNexion** [DFS-Servers/BugReportsAndSuggestions#1]
_Alright so, here are a few issues that have arised in the span of ~12h._

**1.** XP, credits and item drops are currently not dropping. After many map changes, no one seems to be getting credits, xp or any items.

**2.** The leaderboards are currently not working properly. After trying to look at the playtime leaderboards, I got the error "There was an error reading from the database. Please try again."

**3.** Some people are reporting getting an ERROR pet that does not count as a pet, as they stated using the /pet command showed no signs of any pets. There was one instance where someone said that "feeding the pet makes it go away". Didn't see myself, but still dropping this info here just in case.

**4.** The server crashed around 3-4 times. Two of those times were on slender_baldis_education after spending 20-30 minutes or so in it. Might need further testing just in case.

**5.** Some people immediatly got Rank 5 on the Mercenary Guild after joining. Seems to be at random.

**6.** And the biggest issue I found myself, the new quest system gave me 2 Massive Briefcases which have INFINITE USES. It doesn't register the item as actually being used, since the message of it being used doesn't appear and they didn't dissapear from my pack, but it still gave me the money when using them. Not sure if it might be an issue with quest gained Massive Briefcases, or all briefcases in general.

**That's all for now.**

**Comment by Dispenz0r** [comment]
Regarding 5, if you happen to have the badge from Xmas update, you'll be given free Mercenary Rank until Rank 5.

Will investigate the rest with Light, thanks for reporting.

**Comment by Light08** [comment]
Done and fixed. At least from the look of it...
