### ISSUE TITLE
Moonstones effect not working on facing_worlds_2011 & possibly other maps

### ISSUE THREAD

**Issue by miniz1994** [DFS-Servers/BugReportsAndSuggestions#10]
**Steam Profile**
https://steamcommunity.com/id/miniz1994/

**Describe the bug**
Tried using a moonstone too get up higher & had no difference in gravity on facing_worlds_2011 as heavy.
it used the item but nothing happened too my gravity pretty much.

**To Reproduce**
Describe the steps to reproduce the bug.
For an *example*:
1. I went to '...'
2. I clicked on '....'
3. Purchase did not '...'
4. No credits

**Expected behavior**
its supposed too lower gravity ofc

**Screenshots or error logs**
If applicable, add screenshots or error logs to help explain your problem.

**Server Info (please complete the following information):**
 - Region: [e.g. EU]
 - IP [e.g. 89.35.29.11:27145 ...]

**Additional context**

**Comment by Dispenz0r** [comment]
We don't want people flying in the air so it's better a lot that way.
