### ISSUE TITLE
VSH Deadringer control point bug

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#100]
**Steam Profile**
https://steamcommunity.com/id/vilxxu/

**Describe the bug**
The bug is that the control point can be enabled by a deadringer death

**To Reproduce**
1. get to 5 non hale players on vsh
2. Spy gets killed with the deadringer active
3. Control point active without actually hitting the perimeters

**Expected behavior**
Control point staying locked

**Server Info**
 - Region: [EU UK]
 - IP [89.35.29.11:27145]

**Comment by ramunecarbonated** [comment]
addressed

**Comment by Dispenz0r** [comment]
Community Box given now, thanks for reporting.
