### ISSUE TITLE
Charge Shield gets destroyed by Hale when ubered

### ISSUE THREAD

**Issue by Kray0la** [DFS-Servers/BugReportsAndSuggestions#101]
**Describe the bug**
Hale trancendes with twice the attacking power for some reason. If you are a Demoman, equip any charge shield and happen to be ubered - if the Hale hits you, your charge shield gets destroyed which shouldn't even be possible from a logical standpoint. 

**To Reproduce**
I. Be Demo and equip any charge shield of choice
II. Get ubered by any medic by the stock medigun 
III. Let Hale hit you
IV. The charge shield should now be destroyed and no longer usable

**Server Info (please complete the following information):**
 - Any Server

**Additional context**
I am aware the shield is supposed to tank one hit from the hale. That shouldn't be happening when I still have it and be ubered at the same time.

**Comment by ramunecarbonated** [comment]
has been addressed for a future update since yesterday, @Dispenz0r will give you a keyless community box sometime later.
