### ISSUE TITLE
Playermodel Suggestion: "Niko Package" 

### ISSUE THREAD

**Issue by Kray0la** [DFS-Servers/BugReportsAndSuggestions#102]
**Describe your suggestion**
I would like to suggest an all around "Niko" package of playermodels, so to speak. With the addition of Hatkid, introducing new playermodels out of other titles seems encouraging. 

Niko Bellic from GTA 4 (Sniper) 
steamcommunity.com/sharedfiles/filedetails/?id=134271485

Niko from OneShot (Scout) 
steamcommunity.com/sharedfiles/filedetails/?id=912048346

**Comment by Dispenz0r** [comment]
I doubt Niko Bellic would be popular that much tbh. As for Niko from OneShot, we'll consider it for the future.
