### ISSUE TITLE
Map issue: vsh_gyros_v5 spawn doors stuck

### ISSUE THREAD

**Issue by V1NAlt** [DFS-Servers/BugReportsAndSuggestions#103]
**Describe the bug**
In vsh_gyros_v5, the doors do open the first round but afterwards do not even open up for the rest of the map time.

**To Reproduce**
1. Go to a DFS server with vsh_gyros_v5
2. Have at least one other person to play, and kill during the first round
3. Spawn doors are now stuck.

**Expected behavior**
Both of the spawn doors should open, allowing the usual fight to happen.

**Server Info (please complete the following information):**
 - Region: USA | VA
 - IP: 198.24.171.83:27185

**Additional context**
I have only encountered this while playing with Ashoid so far. Not sure if this issue has been going on in other servers.

Edit: To add more info to this, I only managed to see this once, so I don't know if it will happen again.

**Comment by GreenSwede** [comment]
Thanks for reporting this. Pretty strange behavior but I came up with a workaround solution. The doors will no longer spawn closed, they will always be opened from now on.

**Comment by Z-Ben** [comment]
Oh I missed, yeah that's the mod fault. This will be fixed in next vsh update.
