### ISSUE TITLE
Vagineer softlocks Engineers in VSH

### ISSUE THREAD

**Issue by DarkDragonian** [DFS-Servers/BugReportsAndSuggestions#104]
**Steam Profile**
https://steamcommunity.com/id/Fatalita

**Describe the bug**
A very situational but fatal bug.
RED Sentries turn into BLU after Vagineers rage but carrying your sentry while the rage has been activated not just removes your sentry but also the ability to use any of your items.

**To Reproduce**
1. Wait for Vagineers rage to fill up
2. Pick up your own sentry (as an engineer)

**Expected behavior**
Nothing would happen to your sentry while holding.

**Screenshots or error logs**
Not yet but I'll upload one as soon as the bug reoccurs.

**Server Info (please complete the following information):**
 - Region: EU | UK
 - IP: 89.35.29.11:27145

**Edit:**
This bug had occured to me yesterday but now you either put down a BLU Sentry or nothing at all.
The thing yesterday was through Gunslinger but it has been tested today with the stock Wrench.

**Comment by Z-Ben** [comment]
Thank you for the report, Vagineer's rage is been revisited anyways.

**Comment by Dispenz0r** [comment]
Should be fixed now, will re-open unless if actually isn't.

Given a Community Box, thanks.
