### ISSUE TITLE
Affinity particle shown while spectating someone 

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#105]
**Steam Profile**
https://steamcommunity.com/id/vilxxu/

**Describe the bug**
The bug is that the affinity particle displays on people who you spectate when dead.

**To Reproduce**
1. spectate someone while dead (works best in arena based gamemodes)
2. Particle will show up on the person you spectate 
**Expected behavior**
Particle being hidden
**Server Info**
 - Region: [EU UK]
 - IP [89.35.29.11:27145]

**Comment by Light08** [comment]
There will be a major overhaul regarding modules and particles and how they'll work in the coming weeks. Basically a lot of fixes. It should also come with a fix for this. Thought I should mention it since there hasn't been a response from me yet.

**Comment by Light08** [comment]
Should be fixed tomorrow, maybe earlier. Should the bug still persist after tomorrow's maintenance, then feel free to reopen this thread and notify me.
