### ISSUE TITLE
my donation stats are not accurate at all

### ISSUE THREAD

**Issue by Jacksper19462** [DFS-Servers/BugReportsAndSuggestions#107]
it says I only donated $5 when I have donated multiple times.

![my current stats](https://user-images.githubusercontent.com/49961352/56695751-74404a80-66f2-11e9-82a1-ec909219843a.PNG)

![evidence3](https://user-images.githubusercontent.com/49961352/56695722-6094e400-66f2-11e9-8f4e-5971a740070b.PNG)
![evidence1](https://user-images.githubusercontent.com/49961352/56695723-6094e400-66f2-11e9-9ede-5a9114e657d8.PNG)
![evidence2](https://user-images.githubusercontent.com/49961352/56695724-612d7a80-66f2-11e9-863c-922d17263b0d.PNG)

**Comment by Light08** [comment]
The donation tracking has only been live since November 2017. Looking at your images, there's only been one trade made since that date, and therefore only one trade that has been tracked.

Sadly we can't do any retroactive magic to register previous donations, since these simply did not track.
