### ISSUE TITLE
Baby Face's Blaster and VSH

### ISSUE THREAD

**Issue by BrightBabyYoshi** [DFS-Servers/BugReportsAndSuggestions#108]
**Steam Profile**
N/A

**Describe the bug**

Whenever you equip the Baby Face's Blaster, you get a persistent slow effect that won't go away until you switch class.

**To Reproduce**

1. Equip the Baby Face's Blaster;
2. Re-spawn on the next round;
3. Now you have the persistent slow effect.

**Expected behavior**

For the slow effect to neither be a thing (Since the BFB is already bad by itself) nor stay even after switching weapons.

**Screenshots or error logs**

N/A

**Server Info (please complete the following information):**

All servers

**Additional context**

N/A

**Comment by ramunecarbonated** [comment]
>For the slow effect to neither be a thing

The BFB does have slow, as noted on this line.
https://github.com/Kenzzer/VSH-Rewrite/blob/597dbd341a00e47abe0e843458b3a7d8d4a3c4ec/addons/sourcemod/configs/vsh/vsh.cfg#L8

**Comment by ramunecarbonated** [comment]
I will be governing changes to the Baby Face's blaster, consider this issue "closed" until changes are actually made.

**Comment by shinsasch** [comment]
The Baby Face's Blaster will receive a small overhaul the next time Versus Saxton Hale is updated on the servers with a new version, increasing the usability of the weapon.
