### ISSUE TITLE
/rules

### ISSUE THREAD

**Issue by Leafpad** [DFS-Servers/BugReportsAndSuggestions#109]
/rules doesn't bring up the menu

To recreate: Type /rules

It will appear in the chat as if it were an unknown command

**Comment by Light08** [comment]
As I said in the chat, temporarily disabled since I'm overhauling it.
Kinda feeling burned out from the update & maintenance and I had bigger prioritizies to work on and fix, so that is being slightly delayed. I'll probably fix it during the weekend.

**Comment by Dispenz0r** [comment]
Re-opening this until it's fixed.

**Comment by Light08** [comment]
Fixed.
