### ISSUE TITLE
dr_valve_hq_beta2 - Reward at end of round not working

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#11]
**Steam Profile**
https://steamcommunity.com/id/thatlimey/

**Describe the bug**
The "Kill everyone (except you)" button at the end of dr_valve_hq_beta2 kills all RED players, but Death survives - all players except for the winner will be dropped down tubes to their death, but the person playing Death will survive. 

**To Reproduce**
1. Reach the end of dr_valve_hq_beta2
2. Press the "Kill everyone (except you)" button

**Expected behavior**
All RED survivors and Death will be dropped down long tubes. RED players will die, but Death will survive.

**Server Info (please complete the following information):**
 EU | UK:  89.35.29.11:27145 

As a guess, Death might be made invulnerable to fall damage from the mode which makes them survive.

**Comment by GreenSwede** [comment]
I have not tested the fix that I made on the servers but it should hopefully work. Instead of dying from fall damage they will die from "generic" damage.

**Comment by GreenSwede** [comment]
This is still an issue. It will likely require a change in the deathrun plugin in order for this to be solved.

**Comment by Dispenz0r** [comment]
The only solution in that case would be removing the map, which I don't want to do just for a minor issue so just ignore it for now.

**Comment by GreenSwede** [comment]
Another solution without removing the map is to add a map check to the deathrun plugin so that it can determine if it should give death any fall damage immunity.
