### ISSUE TITLE
Donator EXP Boost has incorrect chat notification

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#111]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
The chat notification that the user is receiving increased EXP incorrectly states that it is because of their screen name [DFS] tag, which is no longer the case.

**To Reproduce**
1. Log into the servers as a donator
2. Check the chat 

**Expected behavior**
The notification of increased EXP should refer to the user being a donator since the [DFS] tag exp boost has been removed.

**Screenshots or error logs**
![hl2_2019-05-03_10-19-02](https://user-images.githubusercontent.com/42521633/57129089-537c9280-6d8d-11e9-8ecf-fd2a29dfeff4.png)

**Server Info (please complete the following information):**
EU: 89.35.29.11:27145

**Comment by Light08** [comment]
Fixed. Good catch.
