### ISSUE TITLE
Rainbow Lantern Skin Name Change

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#112]
**Is your feature request related to a problem? Please describe.**
The Rainbow Lantern Skin's name makes it seem like it's part of the Model Manager when it actually unlocks a new effect for the Luminous Lantern.

**Describe your suggestion**
Changing the name from a Skin to an Upgrade would more accurately reflect what it does, in line with other Upgrade Modules since they change other cosmetic appearances

**Describe alternatives you've considered**
While I don't think calling the Rainbow Lantern a Skin is the best category of Module for it, the other categories besides Upgrade seem less fitting of it.

**Additional context**
"You have uncrated a Damaged Lootchest Series #1 and obtained: Rainbow Lantern Skin"

**Comment by Light08** [comment]
I'm considering renaming it to just 'Modification', and renaming the category to 'Passive'.
It should be more accurate description. I'll add that sometime later if approved.

**Comment by Light08** [comment]
Done. Several changes towards Module naming were done.
