### ISSUE TITLE
Luminous Lantern visible while cloaked

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#113]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
The Luminous Lantern's effect is visible while cloaked as Spy, making actually using the cloak almost impossible.

**To Reproduce**
1. Use a Luminous Lantern
2. Cloak as Spy

**Expected behavior**
Having the effect be hidden while cloaked in the same way Particles and Footsteps are would make sure using this item doesn't prevent the user from effectively playing Spy.

**Screenshots or error logs**
![image](https://user-images.githubusercontent.com/42521633/57131647-eff66300-6d94-11e9-9966-f6c7726756ce.png)

**Server Info (please complete the following information):**
EU: 89.35.29.11:27145

**Comment by Light08** [comment]
Fixed now. Lights should properly toggle off / on after cloaking with the next hotfix update.
