### ISSUE TITLE
28 Rounds Later Mission inconsistently counting

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#114]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
The 28 Rounds Later mission seems to be counting completed rounds inconsistently - I completed a full map's worth of rounds but none counted. After a few rounds on the next map, I still had no progress. I check again as I was writing this report and found I had 6 rounds counted and the mission has correctly tracked since. 

**To Reproduce**
1. Play and finish a round of SFZ
2. Check mission progress of 28 Rounds Later

**Expected behavior**
The mission should consistently track completed rounds.

**Server Info (please complete the following information):**
EU: 89.35.29.11:27145

**Comment by Limeball** [comment]
After some investigating on the server, we think the issue might be related to the fact that if any one person uses a kill bind, the entire round's progress is not counted. I get that this is to prevent people farming it, but invalidating the entire round over one kill bind, even if the round is played legitimately, seems like overkill.

**Comment by shinsasch** [comment]
Again, why am I being assigned to this? This is part of @Light08's code for the campaign.

**Comment by Light08** [comment]
There's no killbind restrictions. However, there is another tricky condition that prevents this mission from being farmed easily. I'll check myself later if it works properly since you might have just not met the condition. Considering you mentioned kill binds it sounds as if people tried to do it the cheap way...

**Comment by Limeball** [comment]
Nah, the rounds were played properly, the Survivors just didn't make it far. Someone mentioned the killbinds some time after the rounds started counting again.

**Comment by Light08** [comment]
Sounds to me the system works then.
