### ISSUE TITLE
Rise of the Undead Mission not working

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#115]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
The Rise of the Undead mission is not counting killed zombies.

**To Reproduce**
1. Play SFZ
2. Kill zombies
3. Check mission progress

**Expected behavior**
The mission progress should increase as the player kills zombies

**Server Info (please complete the following information):**
EU: 89.35.29.11:27145

**Comment by shinsasch** [comment]
Why am I being assigned to this?

**Comment by Light08** [comment]
Fixed now.
