### ISSUE TITLE
Super Zombie Fortress - New update breaks functionality on some maps

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#116]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
Several map-specific items now aren't usable (e.g. ammo pack and keyblade on szf_turtle_attack)

**To Reproduce**
1. Find a map item as mentioned above
2. Attempt to pick it up

**Expected behavior**
The item should be picked up but nothing (E key, F key, both mouse button and scroll click) has any effect

**Server Info (please complete the following information):**
EU: 89.35.29.11:27145

**Comment by shinsasch** [comment]
Will elevate with the map creator to determine exactly what is going wrong here, the code powering carryable entities has not been altered in any way from this update.

**Comment by shinsasch** [comment]
Additional note; you can only pick up carryable items with E key.

**Comment by shinsasch** [comment]
This was caused by incorrectly calculating a player's cooldown on picking up things, as the system now is different.

This fix will be released at a later time together with #119.

**Comment by shinsasch** [comment]
Fixed, box should be in your inventory sometime.
