### ISSUE TITLE
Changing Servers

### ISSUE THREAD

**Issue by Leafpad** [DFS-Servers/BugReportsAndSuggestions#118]
Changing servers gets rid of your multiplier

To Reproduce: 
1. Build up a multiplier on either server
2. Go to the other server
3. Your multiplier is now gone

Unless I am mistaken it should stay across both servers like the quests

**Comment by Light08** [comment]
That's how it works for now. Crosssupport is kind of a difficult task and I'll look into ways to achieve it in the future. For now it's a rather small priority.
