### ISSUE TITLE
New SZF Changes making areas of maps inaccessible

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#119]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
Due to the recent SZF update increasing the sizes of Special Infected, there are now parts of several maps that they cannot traverse through. 

**Screenshots or error logs**
![image](https://user-images.githubusercontent.com/42521633/57179635-b8acb280-6e77-11e9-8a7a-0c7891a360c1.png)

**Server Info (please complete the following information):**
EU: 89.35.29.11:27145

**Comment by shinsasch** [comment]
Noted.

**Comment by shinsasch** [comment]
I added an experimental fix so the size changes from the last update can be maintained while addressing this. In the event it does not fix (as it will likely introduce a bug) things as intended just drop by here again.

**Comment by Dispenz0r** [comment]
Given a Community Box now, thanks for reporting!
