### ISSUE TITLE
ach_villainscity

### ISSUE THREAD

**Issue by Leafpad** [DFS-Servers/BugReportsAndSuggestions#12]
**Describe the bug**
Capturing the intel on Ach_Villaincity brings the round to an end and a round restart

**To Reproduce**
Go to the intel capturing part of the map and capture the brief case 3 times on the same team and the round will restart

**Server Info (please complete the following information):**
198.24.171.83:27185

Grandpa Niko alerted me to this

**Comment by GreenSwede** [comment]
Easy fix, tf_flag_caps_per_round was set to 3 for some unknown reason.

**Comment by Dispenz0r** [comment]
Should be fixed after today's maintenance, thanks for reporting!
