### ISSUE TITLE
Monokuma playermodel not replacing Medic voicelines

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#120]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
The Monokuma playermodel isn't replacing Medic's voicelines.

**To Reproduce**
1. As a Medic, equip the Monokuma playermodel.
2. Use voicelines.

**Expected behavior**
You should hear Monokuma's voicelines, not Medic's.

**Server Info (please complete the following information):**
USA : 198.24.171.83:27185

**Comment by Dispenz0r** [comment]
@ThatAverageJoe Will leave this one to up to you

**Comment by Limeball** [comment]
Seems like this affects multiple classes, not just Medic. Only had this problem on the US server though.

**Comment by Dispenz0r** [comment]
Could you test and see if they work or not in the EU server as well?

**Comment by Dispenz0r** [comment]
Should be an extremely rare bug, the voice lines seem to be set properly on the config, the plugin also somehow thought you weren't connected to the server.

If it happens again do let me know, but I doubt it will occur again

Closing.
