### ISSUE TITLE
Trails enabled in PropHunt

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#121]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
Trails are visible in PropHunt which can make props easily visible, especially when moving around.

**Expected behavior**
To not make props obviously visible, trails should be disabled which, as I understand it, seems to have been a change that was already supposed to be implemented.

**Server Info (please complete the following information):**
USA : 198.24.171.83:27185

**Comment by shinsasch** [comment]
![image](https://user-images.githubusercontent.com/16175575/57200186-c9991900-6f88-11e9-8a2b-05003f2d4846.png)
![image](https://user-images.githubusercontent.com/16175575/57200187-cc940980-6f88-11e9-918e-6a66c841946b.png)

Confirming.

**Comment by Light08** [comment]
Should be fixed now. Along with footprints. Reopen if still persists.
