### ISSUE TITLE
vsh_hakurei_winter_v2 causes some of Team Fortress 2's sounds to be muted until a manual snd_restart is done

### ISSUE THREAD

**Issue by shinsasch** [DFS-Servers/BugReportsAndSuggestions#122]
**Steam Profile**
https://steamcommunity.com/profiles/76561198041374163/

**Describe the bug**
In vsh_hakurei_winter_v2, playing on the map will make certain default (keyword here is that this does not affect custom server content) sounds not play until a manual snd_restart is done.

This bug has been confirmed to also be present for others through text chat.

**To Reproduce**
1. As a player, melee the wall, shoot a gun, hit the boss, etc.
2. (All) sounds from these actions will not play.

**Expected behavior**
Said sounds should play.

**Screenshots or error logs**
No console logs are printed in the chat when this bug occurs.

**Server Info (please complete the following information):**
 - Region: EU
 - IP 89.35.29.11:27145

**Additional context**
There are multiple reasons to get rid of this map, including bad gameplay / horrible layout / being horribly unoptimized (bad framerate but excellent computer). Until then, this map will be one of the reasons for an instant leave regardless of my enjoyment for Versus Saxton Hale.

**Comment by shinsasch** [comment]
updated for clarity

**Comment by Dispenz0r** [comment]
Not sure how you want us to fix this exactly, the best I could do is swap this map for another vsh map. 

Also not sure if this issue can be fixed using Stripper: Source, I'll have a look into this as a later date.

Closing for now.

**Comment by shinsasch** [comment]
A replacement would be very favourable. The map also seems to reduce the amount of players playing last time I saw it on.

**Comment by Kenzzer** [comment]
it doesn't help that this map is also a fps killer for some people.

**Comment by shinsasch** [comment]
re-opening until actually addressed

**Comment by Dispenz0r** [comment]
I've closed this for a good reason so please don't, thanks.

**Comment by Dispenz0r** [comment]
I'll most likely remove or replace this map alongside the few other maps reported as problematic on DFS.
