### ISSUE TITLE
Various changes to surf_rainbow_v2

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#127]
**Is your feature request related to a problem? Please describe.**
Earlier today, we encountered a player with a sentry gun in a room by the jail of the map which covered almost the entire room. Thanks to the map, this sentry gun was invulnerable, making the jail nigh unplayable for anyone on the other team who could not finish the map.
![hl2_2019-05-14_18-28-23](https://user-images.githubusercontent.com/42521633/57728049-d7d2ed80-768a-11e9-9fc9-0ee163ea272a.jpg)

**Describe your suggestion**
This area of the map should not allow players to shoot out from it as, unlike similar areas on surf_utopia, players cannot be retaliated against from within the jail. Building sentries inside the walls in surf_utopia is also not possible.

To prevent these unfair kills, I suggest that players be blocked from attacking players in the jail from this spot, and the area be updated to not allow building placement.

In addition, there are two other areas I feel should be given this treatment as they directly face the spawns. 
![hl2_2019-05-14_18-29-07](https://user-images.githubusercontent.com/42521633/57728107-ff29ba80-768a-11e9-9322-db4b06b5ec88.jpg)
![hl2_2019-05-14_18-29-51](https://user-images.githubusercontent.com/42521633/57728114-0224ab00-768b-11e9-9fff-c2f94393ec71.jpg)

The rooms directly behind the spawns include a button that raises a layer of glass, which I presume stops attacks from reaching the players when it's in the way. This button could be disabled to ensure no attacks from this room reach the players in spawn.
![hl2_2019-05-14_18-29-28](https://user-images.githubusercontent.com/42521633/57728516-09988400-768c-11e9-8e92-9972f8dbba86.jpg)

**Describe alternatives you've considered**
I did consider suggesting disallowing buildings in the jail room, since surf_utopia allows you to shoot through the jail walls upon completing the map. However, I feel that return fire being blocked makes it worse than surf_utopia's case.

**Comment by GreenSwede** [comment]
I have come up with a fix, thanks for the suggestions.

**Comment by Dispenz0r** [comment]
Apparently the same issue(s) are still around and not fixed yet @GreenSwede

**Comment by Afterstormer** [comment]
![2](https://user-images.githubusercontent.com/42520820/60536813-0d956980-9cff-11e9-8217-244fc43539d4.png)
![3](https://user-images.githubusercontent.com/42520820/60536815-0d956980-9cff-11e9-9246-1425cd9a9ba3.png)
![4](https://user-images.githubusercontent.com/42520820/60536817-0d956980-9cff-11e9-84fc-f9710e9aacb8.png)
![5](https://user-images.githubusercontent.com/42520820/60536819-0d956980-9cff-11e9-85c3-b0f2eb10712c.png)
![Untitled](https://user-images.githubusercontent.com/42520820/60536822-0d956980-9cff-11e9-832a-24a77440022f.png)
Here are some more areas that allow you to enter these places.
Only deal with the 2 and 3 gates, as the 1 just takes you to the top part of the jail.

**Comment by GreenSwede** [comment]
The top room above the spawns already has the floor blocked off so you can't shoot down and attack other players, neither can you build any buildings up there.

I have blocked off the floor at these rooms with invisible fences at the jail so you can't place any buildings.
![20190705211929_1](https://user-images.githubusercontent.com/42186507/60742230-c14f6100-9f6c-11e9-9855-df485ce862d0.jpg)

Blocking off every entrance to these hidden rooms feels unnecessary when you can't attack people from the inside anyways. If people want to get into these rooms they should have the option to, they just can't abuse it anymore.
