### ISSUE TITLE
Incorrect weapon names in SZF

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#128]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
Weapons are appearing in chat with strangely formatted names in SFZ.

**To Reproduce**
1. Find a weapon 
2. Interact with it (pick up or call out)

**Expected behavior**
The name in chat should match the weapon name.

**Screenshots or error logs**
![hl2_2019-05-14_19-19-26](https://user-images.githubusercontent.com/42521633/57728977-ffc35080-768c-11e9-921a-53721af10ec7.png)
![hl2_2019-05-14_19-25-11](https://user-images.githubusercontent.com/42521633/57728983-02be4100-768d-11e9-9063-92fe5976ed38.png)

**Server Info (please complete the following information):**
EU: 89.35.29.11:27145

**Comment by shinsasch** [comment]
This is due to an unintended side-effect of the update to name formatting of items, so I reverted it back, now it will show a TF_WEAPON_ on some stock weapons. Will fix when I actually feel like it, it's Valve's fault it has to be this difficult in the first place.

**Comment by Kenzzer** [comment]
It was indeed valve's fault, stuff isn't translated unless they're in 3rd or 4th param of the user message.
Anyway, fixed.

**Comment by Dispenz0r** [comment]
Given a Community Box now, thanks for reporting!
