### ISSUE TITLE
/toggleswap resets upon map change/server rejoin

### ISSUE THREAD

**Issue by Kray0la** [DFS-Servers/BugReportsAndSuggestions#13]
**Describe the bug**
When /toggleswap is used, it works for the rest of the map. Upon server rejoin or map change it resets, having to retype the command.

**To Reproduce**
/toggleswap in chat or sm_toggleswap in console

**Expected behavior**
It should reset after map change.

**Server Info (please complete the following information):**
Any Server

**Additional context**
N/A

**Comment by Light08** [comment]
Not a bug, intentional. For now.

I'll be looking into adding a brand new system that "saves" player states client-side.
For the meantime, please be patient for now.
