### ISSUE TITLE
Fun commands such as /civilian are enabled in Versus Saxton Hale

### ISSUE THREAD

**Issue by shinsasch** [DFS-Servers/BugReportsAndSuggestions#130]
**Steam Profile**
https://steamcommunity.com/profiles/76561193767119342 linking to a different person's profile whom is the reason I made this report.

**Describe the bug**
Fun commands such as /civilian are enabled in Versus Saxton Hale, these command(s) should not be enabled on Versus Saxton Hale.

**To Reproduce**
1. Type /civilian
2. Command is not blocked, making you a civilian.

**Expected behavior**
Fun commands as /civilian should not work in Versus Saxton Hale.

(In addition, gamemodes such as VSH and SZF should not be printing chat 'advertisements' for fun commands that are not enabled on said gamemodes, but that is a different thing and not important at all to be honest.)

**Screenshots or error logs**
![image](https://user-images.githubusercontent.com/16175575/57769681-d519dc00-770e-11e9-9a84-7daa989e9cd8.png)

**Server Info (please complete the following information):**
EU, 89.35.29.11:27145

**Additional context**
Could other 'fun commands' be enabled on accident that should not be active on the gamemode?

**Comment by Dispenz0r** [comment]
Should be fixed now
