### ISSUE TITLE
Trade_clocktown_v1a DFS map sounds broken, possible removal of the map ?

### ISSUE THREAD

**Issue by miniz1994** [DFS-Servers/BugReportsAndSuggestions#131]
**Is your feature request related to a problem? Please describe.**

Getting a bit tiring having that map randomize from say slender ending too soon before the next vote starts, as the map sounds are as you probably know since before this github opened broken.

**Describe your suggestion**

Either an update of some sort too the map that fixes the soundfiles for the map or a removal of the map entirely & replaced with some other map. That doesnt randomly earrape players wearing headsets when something like the belltower is supposed too chime or you shoot one of the explosive barrels that blows up a large boulder blocking a road.

But it's up too you guys in the end on what too do with the map, maybe open a vote on the dfs.boards on what maps you know have bugs with sounds or other quality issues & see which ones can stay and get a possible fix or get removed as well.

**Comment by BimboBumboBambo** [comment]
I'd also like to add myself that even though the map is supposed to be a non-competitive/friendly map, friendly commands like /mm don't work.

**Comment by Light08** [comment]
Intentional. Map is due to structure instable. Some plugins were disabled as a result. Applies to various Nintendo maps.

**Comment by Dispenz0r** [comment]
Should be fixed now, thanks for reporting.
