### ISSUE TITLE
Giving the Wrangler a buff in SZF 

### ISSUE THREAD

**Issue by NeppuTennouboshi** [DFS-Servers/BugReportsAndSuggestions#133]
**Describe your suggestion**
In SZF, when I'm playing Engineer and I see a Wrangler spawn, there is no real reason for me to pick it up over the normal pistol due to how little of an advantage it gives whether you use a mini-sentry or a regular sentry especially considering the sentry's low ammo pool and the fact the ammo drains over time regardless, which means you're putting yourself at a clear disadvantage using manual aim.
For more gameplay variety, I suggest adding some additional attributes to the Wrangler to make it a weapon you can actually consider picking up when you're playing Engineer.
Some attributes I thought of were:

- Pausing the ammo drain while using the Wrangler.
- Making the sentry use less ammo while using the Wrangler to shoot.
- Making the sentry do more damage while using the Wrangler.

I don't mean these as "put all of them at once on the Wrangler", but rather ideas as to what kind of attributes could be used on the Wrangler.

**Comment by shinsasch** [comment]
Very nice suggestion, I left the Wrangler in the back and I agree that it is due that it gets an actual buff.
