### ISSUE TITLE
SZF Expedition C2 1st Cap blockable by blu/zombies.

### ISSUE THREAD

**Issue by miniz1994** [DFS-Servers/BugReportsAndSuggestions#134]
**Steam Profile**
A link to your Steam profile (optional).
https://steamcommunity.com/profiles/76561198024940721/

**Describe the bug**
A clear and concise description of what the bug is, what can be done to reproduce it, if applicable.

first cap seems too be blockable by zombies,

**To Reproduce**
Describe the steps to reproduce the bug.
For an *example*:

Well pretty much just walk over the point as blue/zombie and you block red from capping which is quite an issue when they can constantly spawn there.

err the points too not be blocked by zombies like all other maps as far as i know the server has ?

**Server Info (please complete the following information):**
 - Region: [e.g. EU]
Done on EU as of may 16th 21:08 gmt+1

**Comment by shinsasch** [comment]
https://github.com/DFS-Servers/BugReportsAndSuggestions/issues/126#issuecomment-491523811

Not a bug.
