### ISSUE TITLE
Friendlies being able to destroy sapped buildings

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#135]
Steam Profile
https://steamcommunity.com/id/vilxxu/
**Describe the bug**
This bug is that you are able to destroy sapped buildings while in friendly mode

**To Reproduce**
1. Go friendly
2. Get a spy to sap a building
3. Shoot at the building while in friendly mode
4. You can destroy the building

**Expected behavior**
The building being left unharmed

**Server Info**
 - Region: [EU]
 - IP [89.35.29.11:27145]

**Comment by Dispenz0r** [comment]
There is sadly not much we can do about this for now since the author of the plugin hasn't updated the plugin for a pretty long time.
