### ISSUE TITLE
ctf_steamroll not working properly

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#136]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
ctf_steamroll is not working properly, with rounds not ending as they should when one team successfully captures the intelligence. The round goes on until the timer ends, regardless of how many times the intelligence is captured. The game ends in stalemate since there is no cap limit.

**To Reproduce**
1. Play ctf_steamroll
2. Cap the intelligence

**Expected behavior**
The round should end in victory.

**Server Info (please complete the following information):**
EU: 89.35.29.11:27145

**Comment by Dispenz0r** [comment]
Nothing much we can do regarding this since maps are time based instead of round based.

I'll look into making round based maps run on maxrounds instead of timelimits in near future though.
