### ISSUE TITLE
Super Zombie Fortress - Stalker doesn't cloak

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#138]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
The Stalker special infected does not cloak when not close to Survivors. Cloak can also not be manually activated as the Stalker, either.

**To Reproduce**
1. Spawn as a Stalker
2. Attempt to cloak

**Expected behavior**
The Stalker should automatically cloak when it is not close to Survivors.

**Server Info (please complete the following information):**
EU: 89.35.29.11:27145

**Comment by Dispenz0r** [comment]
Should be fixed now, thanks.

Rewarded with a Community Box
