### ISSUE TITLE
EXP boost issue

### ISSUE THREAD

**Issue by gdfsgdfg** [DFS-Servers/BugReportsAndSuggestions#139]
**Describe the bug**
EXP keeps resetting to 1.0 since Monday's maintenance.

**To Reproduce**
Seems to happen every time the map changes, can barely reach 1.1x.

Server Info:
EU: 89.35.29.11:27145

Steam Profile:
https://steamcommunity.com/id/ohhnoo/

**Comment by Light08** [comment]
Already known and reported. I'll fix it in a bit.

**Comment by Dispenz0r** [comment]
Should be fixed now, thanks for reporting.
