### ISSUE TITLE
Crits not being completely disabled

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#14]
Rocketlauncher still having crits even though nocrits is enabled

1.pick soldier 
2. fire with the rocket launcher until it crits

i expected it to not crit

 - Region: all

**Comment by windflow5** [comment]
Also have seen the scotman's scullcutter crit sometimes

**Comment by Dispenz0r** [comment]
I'll have a look into this soon, while the melee weps being able to crit sounds normal, primaries and secondaries shouldn't have crits at all.

**Comment by Dispenz0r** [comment]
https://i.imgur.com/iEe51dh.png 

?????

blame valve i guess
