### ISSUE TITLE
SF2: Survivor's are able to outrun Alex Jones even without sprint.

### ISSUE THREAD

**Issue by BimboBumboBambo** [DFS-Servers/BugReportsAndSuggestions#140]
**Describe the bug**
This kinda explains itself.

Survivors are able to outrun Alex Jones even without the need of sprint(this goes for Normal, Hardcore and Insane.) This can lead to players getting the boss stuck(like how players get Puppet stuck by having two keeping an eye on her) by making Alex chase them around. Another thing that can happen is for players to use that to get to a certain place and kill themselves(one with other survivors) effectively destroying the round(though it's more of a possibility than something that has happened.)

**To Reproduce**
1. Find Alex
2. Walk whilst he's chasing you.

**Expected behavior**
I hope this bug gets fixed so that Alex Jones is much more of a surprising force to be reckoned with.

**Screenshots or error logs**
https://www91.zippyshare.com/v/T1Q4uneo/file.html

**Server Info (please complete the following information):**
 - Region: EU
 - IP 89.35.29.11:27145

**Additional context**
I've only seen this happen when the boss is Alex Jones. It is unclear if the other chaser bosses have the same thing.

**Comment by ThatAverageJoe** [comment]
Thanks for letting me know about this, I've given a small buff to the boss in relation to his speed and max_speed which will hopefully be up soon.
