### ISSUE TITLE
Slavic Slender Difficulties

### ISSUE THREAD

**Issue by Leafpad** [DFS-Servers/BugReportsAndSuggestions#141]
**Describe the bug**
The difficulty choices in the menu are in some Slavic language. https://i.imgur.com/uGRdwA4.png This occurred on Slender_Lockers on RED
**To Reproduce**
Play Slender
For an *example*:
Play on RED on Slender_Lockers, possibly other Slender as well

**Expected behavior**
Options should be in English 
**Screenshots or error logs**
https://i.imgur.com/uGRdwA4.png

**Comment by Dispenz0r** [comment]
Should be fixed now, given a Community Box.
