### ISSUE TITLE
Slender: Darkibelle not spawning on slender_abandoned & possibly other maps as well.

### ISSUE THREAD

**Issue by miniz1994** [DFS-Servers/BugReportsAndSuggestions#142]
Seemed too never spawn in on slender_abandoned as title mentions, dunno if its specific too that map or others as well here.

Dont need too do anything particular other then have the chance of darkibelle spawning in i guess or possibly force her too spawn on your testserver if possible and look over which maps she doesnt spawn on & either disable her from spawning or fix so she spawns on the map i guess if possible.

**Comment by Light08** [comment]
RNG...

**Comment by Dispenz0r** [comment]
The boss appeared on the server today, the config seems to be set up fine without any problems as well

Closing.
