### ISSUE TITLE
Golden Printers Last Shorter Than Copper Printers

### ISSUE THREAD

**Issue by JimDaFridgeRaider** [DFS-Servers/BugReportsAndSuggestions#143]
Heya! I just want to report an issue I found with one of the supposedly better items in the server: the Golden Printer. I was told that higher tier printers have a lower chance of exploding than lower tiers, but when I used 5 golden printers on ONE map, each one didn't even last a minute. The best I got out of those 5 gold printers, was three minutes. But on the other hand. every time I use a COPPER printer, it literally lasts until the map ends, or at the very least, a good long while. I'm pretty sure this may be a logic error in the gold and copper printer modules, but I don't think I'm the only person having this issue with a supposedly top-tier credit printer. I'm sure the whole DFS community will be more than happy, once printers are fixed.

**Comment by Light08** [comment]
Solved.
