### ISSUE TITLE
Map Categorisation and Related Quests. 

### ISSUE THREAD

**Issue by Argo7200** [DFS-Servers/BugReportsAndSuggestions#144]
**Is your feature request related to a problem? Please describe.**
Right now we have compartmentalisation between friendly and competitive maps, with a few subcategories in the mix. This determines whether or not maps can be fought on and what abilities can be used. 

At the same time, certain quests can only be fulfilled on specific types of maps. This has resulted in a paradigm where people will often squabble over which maps to play purely because of quests instead of voting for what they genuinely want and naturally creates instances where the fun of pursuing quests is obfuscated due to being on non-permitting maps.

**Describe your suggestion**
For this I can imagine a couple of potential measures:

1: Abolish the friendly map categorisation and allow all maps to contribute to competitive quests with damage enabled, with an easily accessible toggle that switches (on respawn) between the friendly (no player-damage, bhop, grapple) and competitive (player-damage, no hop, no grapple) player states, with a visible indication on those that are opted out of combat, such as a symbol above their heads ala dominations (I understand we have friendly system that operates like this already, but suggest it be streamlined to be more quickly accessible. Plus I think transparent players look like butt).

2. Maybe remove game-mode specific quests. The playtime quests for instance are not interesting as challenges anyway. You can fulfil these by being in spectator for crying-out-loud. The capture quest I'm on the fence about, since it is a good challenge but again is restricted to specific maps.

**Comment by Light08** [comment]
I'll look into a new, more-fitting Quest System for DFS at some point later.
I do collect feedback for that purpose, btw. so this is appreciated.

**Comment by Dispenz0r** [comment]
We'll keep the suggestions in mind for later, thanks for the feedback.
