### ISSUE TITLE
A Tweak to the Healing Quests

### ISSUE THREAD

**Issue by Argo7200** [DFS-Servers/BugReportsAndSuggestions#145]
**Is your feature request related to a problem? Please describe.**
The healing quests do not count over-heal, which encourages the practice of not over-healing your teammates, instead waiting for them to go lower than 100% health before healing them, which makes you a pretty crumby medic. Preventative medicine is the best medicine after-all.

**Describe your suggestion**
Simply to have the quests count HP added to players via over-healing towards quest progress. It may blunt the challenge of the quest, but it allows medics to do what they're supposed to uninhibited.

**Comment by Light08** [comment]
The idea is to avoid easy farming by just staying AFK in spawn and heal another AFK person.
Overheal doesn't count as actual healing.

I doubt I'll touch it unless I find a solution for this.
