### ISSUE TITLE
Bugged Projectiles in Slender Competitive 

### ISSUE THREAD

**Issue by Argo7200** [DFS-Servers/BugReportsAndSuggestions#147]
**Describe the bug**
I know the non-functioning flame-throwers have already been reported, but projectiles including rockets, grenades, arrows, jars and so on do not collide with competitors in the Slender arenas. Jars also fail to apply their effects, though if I remember correctly this change was deliberate to mitigate assist farming. 

**Expected behaviour**
Projectile collision and direct damage function as expected. 

**Additional context**
Fighting with certain class load-outs, such as Pyro, Demoman and Huntsman Sniper under these current conditions is a pain in the ass. I think all of these compromises heavily outweigh any benefits brought about by the latest changes to the damage system. I think a roll-back or rethink would be apt.

**Comment by Light08** [comment]
Blame Friendly Fire implementation from Valve.

Fixing it would require massive workaround hacks. It's nothing that is done easily, plus its implemented into Slender, a plugin we do not touch.

**Comment by Argo7200** [comment]
I still think that it's worth fixing, since there's still value in fighting in the arenas for competitive quests or simply for the fun of it. Would it not be worth at least rolling back to how it once was at the expense of assist quests being easier to farm again? Heck, one possibility is to just remove the assist quest as well since many people just find to be a pain in the ass.

**Comment by Dispenz0r** [comment]
A little late on this as well but most of these should be fixed soon thanks to Glub helping us out!

Alongside other PvP arena related changes such as the medigun being able to hurt enemies
