### ISSUE TITLE
Option to Toggle Server Welcome Music 

### ISSUE THREAD

**Issue by Argo7200** [DFS-Servers/BugReportsAndSuggestions#149]
**Is your feature request related to a problem? Please describe.**
A bit of a knit-pick; sometimes game/voice audio that I want to pay attention to is obfuscated by the welcome music. Plus right now it's an extra 64~ MB players have to download just for some superfluous music bites. 

**Describe your suggestion**
I'd be nice to have the option to toggle downloading/playing the welcome music.

**Comment by Light08** [comment]
Download Toggle would be hard to implement, if not even impossible.

Playing the welcome music certainly can be tweaked. I was looking into making the music be dependent of the 'Music Volume' option.

**Comment by Light08** [comment]
Approved.
