### ISSUE TITLE
Randomizer bug: demoman's shields are still equipped

### ISSUE THREAD

**Issue by Madproredmushroom** [DFS-Servers/BugReportsAndSuggestions#15]
**Steam Profile**
 http://steamcommunity.com/profiles/76561198137273362

**Describe the bug**
upon equiping the tide turner in the loadout menu and getting picked as the demoman you still retain it and even get an additional 4th weapon item (any secondary).

**To Reproduce**
1. equip the tide turner
2. wait until you get picked as demoman

**Expected behavior**
the shield shouldnt stay on the player.

**Server Info (please complete the following information):**
 - Region: EU UK
 - IP 89.35.29.11:27145

**Additional context**
it seems to occur because of randomizer version that is older that tf2's summer 2014 update (because other shields dont retain that behaviour). that probably means that the base jumper and other newer weapons may too be affected by this, but i havent yet tested that.

**Comment by Dispenz0r** [comment]
Expect a fix for this soon, hopefully.
