### ISSUE TITLE
No /gold Command while VIP Donator

### ISSUE THREAD

**Issue by Creataurus** [DFS-Servers/BugReportsAndSuggestions#151]
**Describe the bug**
When I typed in /gold into the chat, it says I don't have access even though I'm a VIP Donor. I also tried to use the /gold command in the Gold Commands menu and it did the same thing.

**To Reproduce**
1. Type "/gold" into the chat or use the /gold command in the Gold Commands Menu.

**Expected behavior**
The /gold menu opened up as it usually does.

**Server Info (please complete the following information):**
 - Region: EU
 - IP 89.35.29.11:27145

**Comment by Grandpa-niko** [comment]
seems like it also doesn't work for gold Rank donators
![20190703125002_1](https://user-images.githubusercontent.com/42687863/60610782-a2957280-9d92-11e9-9062-f430a2183052.jpg)
![20190703125006_1](https://user-images.githubusercontent.com/42687863/60610786-a6c19000-9d92-11e9-99f6-f8f065e700e8.jpg)

**Comment by Light08** [comment]
Already fixed. Wait till next update.

**Comment by Light08** [comment]
Reopen if still persists.
