### ISSUE TITLE
Bug: DM Towerleap V2 Dragons fury stops working on CP & elevators.

### ISSUE THREAD

**Issue by miniz1994** [DFS-Servers/BugReportsAndSuggestions#152]
**Describe the bug**

On the map DM Towerleap V2 Dragons fury stops working on CP & elevators entirely on damage.
Discovered initially by rr but said I'd post a github issue.
Spent about 5 minutes trying a few times too confirm it wasn't a one time thing.

**To Reproduce**

It's simple really, either stand on the cp too cap it with dragons fury or inside any of the elevators that goes too the lower levels of the map (not the ones next too the cp, they seem unaffected.) and you'll do 0 dmg with the dragons fury against your enemy.

**Expected behavior**
Well doing damage ofc inside either of the areas mentioned.

Was on the EU server btw, but guessing this bug is on the US server as well.

**Additional context**

Not entirely sure if it affects other weapons on pyro as well, didnt do any damage with melee on the cp as well, though couldn't test more as the map ended just seconds later.

**Comment by Argo7200** [comment]
This is quite bizarre. There aren't any entities occupying those spaces that could somehow cause that effect, apart from the elevators (func_tracktrain entities) themselves. This could be a bug with the game itself. May be worth sending a bug report directly to Valve.

**Comment by Argo7200** [comment]
Follow-up: Entering "bug" in TF2's console will open up a dialogue that you can use to submit a bug report. I've already done so myself, heaven knows if Valve actually pays attention to that feedback channel though. May be better off finding an email address of theirs or something.

**Comment by Dispenz0r** [comment]
Considering this is apparently a TF2 bug and not Argo's fault, I'll be closing this.
