### ISSUE TITLE
Astronaut skin does not replace voice lines on Spy

### ISSUE THREAD

**Issue by shinsasch** [DFS-Servers/BugReportsAndSuggestions#153]
**Steam Profile**
https://steamcommunity.com/profiles/76561198041374163/

**Describe the bug**
The astronaut does not have his voice lines played when you use the model as a Spy.

**To Reproduce**
1. Go to Model Manager.
2. Select Astronaut (1st choice) while playing as a Spy.
3. Try a voice line.
4. It plays the Spy's intended voice line.

**Expected behavior**
Voice line should be replaced with TTS goodness from that NASA game.

**Server Info (please complete the following information):**
 - EU
 - 89.35.29.11:27145
 - tm\_stadium, after Snatcher fight

**Additional context**
A different class, like Pyro, works correctly.

**Comment by Dispenz0r** [comment]
Intentional, the voice lines are meant to work with Pyro only.
