### ISSUE TITLE
Suggestion: Vivi model

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#155]
Been thinking about this for a while now, makes sense hatkid and ralsei are available player models

a model can be found here 
https://sketchfab.com/3d-models/vivi-final-fantasy-ix-3a3f1a4d34564c6d9d0de8059bd39194

**Comment by shinsasch** [comment]
can't see a download link on the sketchfab one so here are other models if needed https://www.models-resource.com/search/?q=vivi&c=-1&o%5B%5D=s&o%5B%5D=p&o%5B%5D=g&o%5B%5D=ig

**Comment by ThatAverageJoe** [comment]
Model wise, there's a few available online, so that's fine. Only potential issue I can see is regarding finding voicelines for it, but I will still consider this for a future update.

Thanks for the suggestion.
