### ISSUE TITLE
Suggestion: Roll-the-Dice (RTD) Tweaks

### ISSUE THREAD

**Issue by Argo7200** [DFS-Servers/BugReportsAndSuggestions#156]
Roll-the-Dice is a pretty fun way of adding momentary game-play modifiers that present interesting and quirky emergent challenges in death-match sessions, whether they be advantageous or limiting. Otherwise RTD serves as a silly, fun gimmick that adds to the eclectic nature of the server. 

However, some of the outcomes of RTD are just straight up ass and don't add anything interesting to the experience. Since any crappy, unfun outcomes can be immediately negated with a quick kill command and respawn, I say they may as well be removed or at least altered so that you'd actually want to stay alive and play with them.

**Effects I'd like to see removed:**
• Explode and Smite - Cool, a suicide bind. Real interesting. Not.
• Spontaneous Combustion - Just a nuisance that can be easily negated with a quick heal. Doesn't amount to much.
• Low Health - Cool, let me just hit my kill bind and get it other with, or find a medic or some health packs; either way this effect doesn't amount to much other than an uninteresting inconvenience. 
• Mystery Sauce - Same league as Low Health and Spontaneous Combustion, only arguably worse since it also effects nearby team-mates. Misery loves company?
• Nostalgia - I'm on the fence about this one, but overall it still seems kind of lame since it doesn't amount to much of a game-play change, especially since telling player teams apart is easy without colour thanks to HUD elements.
• Lag - Just obnoxious, really. Impossible to actually play with. Instant kill bind. 
• Forced Taunt - See above.
• Drugged - Too disruptive to play with and uncomfortable. Whenever I get this, I just don't bother and hit the kill bind.
• Wasted Roll - **_Why?_** 

**Effects I'd like to see tweaked:**
• Frozen - This is actually quite funny, but not for the victim when it lasts as long as it does. I'd say the duration should only be between 5-10 seconds.
• Funny Feeling - Another decent one, but I think the effect is a bit extreme. Apparently the resulting field-of-view is 160, so maybe 140-150 would be better? 
• Earthquake - Due to the way the Source  screen-shake effect decays sharply, the full effect of this roll is only experienced during the first 1/3 or so of the duration. To compensate, the code could set the shake duration to something much longer, but the timer is unaffected and immediately disables the effect when it runs out, resulting in a more 1/0, ON/OFF effect. (fun fact: I sometimes have to employ the same technique when using env_shake in my maps). 

**Effects I'd like to see re-enabled:**
• Timebomb - OK, this one has the potential to be hilarious if implemented properly. Maybe give it a lower probability, a longer fuse time and/or a reduced blast radius. I think I'd be a shame to not have it since the sudden panic shared by both teams puts a smile on my face whenever I even think about it. Though I think the effected player should be given a health buff so it's not so easy to buzz-kill and a collective effort for the other team to take down before it goes off. Heck, maybe it could be modified to use the sentry-buster? Double-heck, this could potentially replace Power-Play as a more interesting roll to play as and against, at least to me. 

Just a note: My objective here isn't to just remove all of the bad effects; I get that it's called "Roll the Dice" for a reason. Instead I want to only retain the _interesting_ game-play effects, whether they be beneficial or detrimental to the player. I know this whole suggestion is biased towards my own subjective view on what is or isn't fun, but I can't help but feel like many would feel the same way about this, hence why I'm making this suggestion.

**Comment by Dispenz0r** [comment]
Some of the effects will get disabled for conflicting with other plugins such as Allowance or Friendly.

Feel free to suggest any other changes to the plugin author here: https://forums.alliedmods.net/showthread.php?t=278579
