### ISSUE TITLE
Professor layton model

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#157]
Saw a couple people saying they'd like to see it as a model

https://www.models-resource.com/3ds/professorlaytonvsphoenixwrightaceattorney/model/15122/

**Comment by ThatAverageJoe** [comment]
The model seems fine, and voicelines are available on the sounds resource so I can see this as a future playermodel.

 I'll consider this as a possibility for after the summer update, thanks for the suggestion.
