### ISSUE TITLE
Suggestion: restrict modules only for non-competitive maps

### ISSUE THREAD

**Issue by Pro100RedMushroom** [DFS-Servers/BugReportsAndSuggestions#158]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

modules are quite annoying to fight with and against:  
1. big particle modules (like rainbow fire) obstruct the player's hitbox with flashy, vivid particles which makes it harder to hit them. this is an issue moslty with melee battles and and hitting headshots as sniper.
2. it also helps identify spies more easily since they stand out a lot in a dark enviroment/while uncloaking.
2.1 from testing i can also say that the particles can be seen by players on the other team even while disguised. by memorising the exact module a plyaer has you can potentionally seek that spy every time.

> **Describe your suggestion**

restrict modules to friendly maps and maps that arnt affected by the issue (like deathrun, saxton hale(?))

> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

disable only those modules that emmit (distracting) particles on comp maps or make those modules less distracting

> **Additional context**
> Add any other context or screenshots about the feature request here.

example with the rainbow fire module:
https://www.dropbox.com/s/apwhryehb9d0bdw/uyX4qD38co.mp4?dl=0
https://www.dropbox.com/s/0yvtzwtxsrge2bu/8KeIw5ycb7.mp4?dl=0
this should show how difficult it may be to hit the target from behind since the module leaves a huge trail behind it (couldnt get better angles or another player to chase me to better demonstrate this, sorry in advance)

**Comment by Pro100RedMushroom** [comment]
how do i engrish

**Comment by Argo7200** [comment]
Perhaps only the larger effects should be selectively disabled? I don't think certain categories of modules such as footsteps and death effects are too pervasive. Plus kill effects have to remain obviously.

**Comment by Pro100RedMushroom** [comment]
already mentioned in **Describe alternatives you've considered**, but i probably should've explained that more

**Comment by Argo7200** [comment]
Derp :blep:

**Comment by Light08** [comment]
I might consider disabling particles for comp maps.

**Comment by Light08** [comment]
I have disabled all particle-category modules for most comp gamemodes. Some are excluded like Deathrun or Dodgeball, where it shouldn't really matter that much.

This is fully experimental and we'll see how things turn out. I might revert upcoming changes anytime.
