### ISSUE TITLE
Auction with equipped pets

### ISSUE THREAD

**Issue by Grandpa-niko** [DFS-Servers/BugReportsAndSuggestions#159]
**Steam Profile**
https://steamcommunity.com/id/nikoiro680

So today I decided to auction a pet, it was an unboxed Gaster blaster , the pet was equipped and during the process was normally okay until i set the sale and got an error message
The error message indicates a problem during the auction and could retry for later, however, checking my equipped pet is no longer in my inventory
_I also checked if the auction was made but neither that was existing
-I tried to wait for nextmap but the pet was still gone, and the auction wasn't made
-I checked if modules would also cause the same problem but they work normally 

**To Reproduce**

> **Be sure to have the pet equipped**

1. go to /auction
2. I clicked on "put item on sale"
3. select the equipped pet
4. set any offer and/or buyout
5. **check if the error happened**

I dont have any screenshots right now sadly, otherwise i couldn't have know this issue in the first place

**Server Info:**
 - Region: EU (only tried on this server)

**Comment by Light08** [comment]
Issue was related to the name. A part I missed when coding the system. It's fixed now, and the auction has been properly restored now too. Thanks for the report.
