### ISSUE TITLE
/global

### ISSUE THREAD

**Issue by Leafpad** [DFS-Servers/BugReportsAndSuggestions#16]
**Describe the bug**
/global is broke again. We can see messages from the players in the server but we are unable to see messages from other server's players
**To Reproduce**
Type /global in chat and try to contact the other servers

**Server Info (please complete the following information):**
 It appears that it is the same problem as before but this has only been tested on EU DE and US VA

**Comment by Light08** [comment]
Will investigate. The plugin is still pretty much in Beta, so issues might occur for the meantime. If anything new happens after updates, please let us know.

**Comment by Dispenz0r** [comment]
Should hopefully be fixed now, make another issue if you see it happening again.

**Comment by Dispenz0r** [comment]
Given you a Community box now, thanks for reporting!
