### ISSUE TITLE
MicroTF2 Intermission Skipping

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#160]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
The Intermission period in WarioWare, which is meant to give players a chance to calmly vote on the next map, is skipped and the map vote occurs during the next round, making it hard to vote for a map while playing.

**To Reproduce**
1. Play WarioWare
2. Complete enough rounds to trigger a map vote

**Expected behavior**
The Intermission period should play out, with no microgames being played and giving players a time to vote on the next map without distraction.

**Server Info (please complete the following information):**
EU: 89.35.29.11:27145

**Additional context**
The countdown to a map vote triggers during the brief moment Intermission is active, but Intermission is then skipped and the vote itself occurs after the next round has started.

**Comment by Dispenz0r** [comment]
I have absolutely no idea what causes this, I'd recommend opening up an issue at https://github.com/gemidyne/microtf2/issues and reporting this to Stevu instead.
