### ISSUE TITLE
New Badge/Achievement Suggestion

### ISSUE THREAD

**Issue by Creataurus** [DFS-Servers/BugReportsAndSuggestions#161]
I'm going off of a limb and just saying that there should be a badge for getting to the 5x exp boost without using cookies, and the badge name be called "Addicted" with a title being of the same title. This is mostly due to me getting to 4.9x without cookies, and dear christ I need to fix my sleep schedule because of it.

**Comment by Light08** [comment]
An interesting idea, but difficult to pull off. The system is not able to track wether items were used or not, considering it saves all the boost stuff on the database. Overall not worth the effort, I'm afraid.
