### ISSUE TITLE
Bugged Item: " What's in the box " Not working as it should currently.

### ISSUE THREAD

**Issue by miniz1994** [DFS-Servers/BugReportsAndSuggestions#162]
**Steam Profile**
https://steamcommunity.com/id/miniz1994/

**Describe the bug**
using whats in the box does no longer kill you and freeze you in place only now, (can get out of it asking too get frozen for 3 seconds or 1 second.)

**To Reproduce**
Use a What's in the box and watch it not kill you pretty much.

**Expected behavior**
Well its supposed too kill you ofc.

**Server Info (please complete the following information):**
EU server currently.

**Comment by Light08** [comment]
Fixed.
