### ISSUE TITLE
Bugged Map DR_Retroland_fix one of the traps does 0 dmg on both sides, screenshots.

### ISSUE THREAD

**Issue by miniz1994** [DFS-Servers/BugReportsAndSuggestions#163]
https://steamcommunity.com/id/miniz1994/

**Describe the bug**
The map doesn't seem too do damage on one of the traps as of today as im posting this.

**To Reproduce**
Walk through the trap on the activated side, thats it.

**Expected behavior**
fire is supposed too kill you there, same with the laser but people can walk through them fine atm.

**Screenshots or error logs**
https://steamcommunity.com/sharedfiles/filedetails/?id=1818117064
https://steamcommunity.com/sharedfiles/filedetails/?id=1818135370

EU server currently

**Comment by GreenSwede** [comment]
I don't know how to fix this, perhaps one of our plugins are causing a compatibility issues with that trap? @Dispenz0r

**Comment by Light08** [comment]
Seems indeed to be caused by a plugin, but which one is the question.

**Comment by Dispenz0r** [comment]
Should hopefully be fixed after the upcoming server update.
