### ISSUE TITLE
[Items/TFDB] Revive not being blocked from using in TFDB

### ISSUE THREAD

**Issue by MrAori** [DFS-Servers/BugReportsAndSuggestions#165]
**Steam Profile**
https://steamcommunity.com/id/mrcallie/

**Describe the bug**
When I was playing some few rounds of TFDB, I noticed that someone could use revives with no issue, even though it's should of been disabled in arena like gamemodes like this one, due to the unfair advantage that player gains from it.

**To Reproduce**
Describe the steps to reproduce the bug.
For an *example*:
1. Buy/Craft a Revive
2. Die by a the homing rocket by someone from the enemy team
3. Use a revive you have inside your inventory
4. You get revived by the item, therefore alive again

**Expected behavior**
Upon using the item in this gamemode, the plugin should disallow the player from using the item with a Message in Chat "You are not allowed to use this item in this gamemode"

**Server Info (please complete the following information):**
Dispenz0r's Fun Server [EU]
IP: 89.35.29.11:27145

**Additional context**
I only found this issue in TFDB and not DR. Due to them being both Arena-based gamemodes, I haven't tested it out in DR if the same issue occurs.

**Comment by Creataurus** [comment]
Pretty sure DR has that safeguard already in place iirc, because people used to spam revives, albeit getting punished in the process.

**Comment by Light08** [comment]
I disabled Revive on Dodgeball and Prophunt for now.
