### ISSUE TITLE
Bugged map: tm_stadium_rc1 Causes my TF2 to crash (Using Linux)

### ISSUE THREAD

**Issue by pokemonpasta** [DFS-Servers/BugReportsAndSuggestions#166]
**Steam Profile**
https://steamcommunity.com/id/pokemonpasta/

**Describe the bug**
So I know this might not be the best place for this but I can't think of anywhere else to report it, since it is a map for DFS. Whenever I try and load tm_stadium_rc1, it causes TF2 to crash. I get through to sending client info and then the whole software just closes. It doesn't matter if I'm connecting to DFS or loading it locally, it just crashes anyway. I'm pretty sure it's a problem with the map since I haven't experienced this problem on any other server/map. I should note as well I'm on linux (Ubuntu 18.04) and running steam and TF2 natively.

**To Reproduce**
1. Launch TF2 on Linux
2. Either connect to DFS while it's in tm_stadium_rc1, or type `map tm_stadium_rc1` in console
3. Wait for the game to load
4. Crash

**Expected behavior**
Load the map without any problems, or at least not crash TF2.

**Server Info (please complete the following information):**
 - Region: EU 
 - IP 89.35.29.11:27145

**Additional context**
Like I said I've only experienced this problem on Linux, although I have not tried it on a windows machine as I don't currently have one. I know it's not a server issue so if it's irrelevant here, that's fine. Finally, I don't know where to look for TF2 crash reports if it even generates any, so I don't have any, but if you can tell me where to look/what to do for any logs I can take a look.

**Comment by Dispenz0r** [comment]
You can't host it in a local server or on any server other than DFS, it is intended to work that way to keep it exclusive for DFS only.

It shouldn't crash on DFS though, try re-downloading the map from the server again after deleting the map file from your maps folder.

**Comment by pokemonpasta** [comment]
Did that and tried joining again, same problem (although I am getting the `Out of memory or address space.  Texture quality setting may be too high.` error. I've turned down the texture quality and still no change)

I do have a [console.log](https://github.com/DFS-Servers/BugReportsAndSuggestions/files/3461025/console.log) now though.

**Comment by Light08** [comment]
Crash outside of DFS is a feature.
Crash inside DFS seems to be an engine / OS issue. Not much we can do there.
You'd have to pinpoint the issue since you're literally the only one with that problem.

**Comment by Dispenz0r** [comment]
Haven't seen anyone else having a problem with the map before

I did do several changes today, let us know in the discord server if you still keep having the same issues after today's server update.
