### ISSUE TITLE
Map Bug: ctf_vikings possible too grab intel through the glass case suddenly.

### ISSUE THREAD

**Issue by miniz1994** [DFS-Servers/BugReportsAndSuggestions#167]
**Steam Profile**
https://steamcommunity.com/id/miniz1994/

**Describe the bug**
Essentially you can grab the intel/money through the glass thats supposed too protect it.

**To Reproduce**
Go up too the intel & glass surrounding it on the enemy side & grab it.

**Expected behavior**
glass is ofc supposed too prevent you from grabbing it until its destroyed after a few minutes of shooting it.

**Server Info (please complete the following information):**
EU, certain it works on US as well.

**Comment by Light08** [comment]
Likely related to the model change from our Charity plugin. It will likely be fixed once we revert the changes on 11th.

**Comment by Dispenz0r** [comment]
Should be fixed now
