### ISSUE TITLE
DR_Playstation Possible Crash Risk

### ISSUE THREAD

**Issue by Creataurus** [DFS-Servers/BugReportsAndSuggestions#168]
**Describe the bug**
If you shred the bud/cheat codes memory card at the end of the map at 100%/120%, it crashes the server as a feature.

**To Reproduce**
1. Go to the Bud Room (The buds are the buzz lightyear cups)
2. Collect the Bud Card
3. Make it to the end of the map
4. Shred the Bud Card instead of putting it into the Playstation
5. The server crashes.

**Expected behavior**
The server crashes when you shred the bud card as it's a feature put into the map if you shred the bud card.

**Screenshots or error logs**
There are several videos of this happening on Youtube, Here's one of them: https://www.youtube.com/watch?v=JFGc1qQ4hKc

**Server Info (please complete the following information):**
None, I just did research.

**Additional context**
Just put a box covering the shredder to prevent this from happening.

**Comment by Light08** [comment]
...and the point of this thread is what exactly? It's, as you already said, a feature. And that's been a thing since before release. It's difficult to pull it off anyway since u have to survive until the end, and I'd encourage our community not to abuse it anyway.
