### ISSUE TITLE
Suggestion: changes too a map: Extend round timer for silent hill or add more players

### ISSUE THREAD

**Issue by miniz1994** [DFS-Servers/BugReportsAndSuggestions#169]
https://steamcommunity.com/id/miniz1994/

As the title, Silent hill is by far the largest slender map the server has.
Which either turns into a walking simulator until the time runs out.
(Pretty common 4 or less die due too lack of time too find them all.)
Or until theres no one left alive from dying too slender monsters.

**Describe your suggestion**
Extending the round timer so there is more of a chance too find every glyph in time, perhaps 4:30 instead of the 3 minute time limit would help keeping the rounds a bit easier.

Or as mentioned have more players per round like say 12 players per round instead of the standard 8 could help covering more of the map in the set timelimit regardless of map monster.

3rd option is reducing the required glyphs down too perhaps 6 instead.

**Comment by Dispenz0r** [comment]
I've increased the maximum amount of players to be 12 instead of 8 for this map, thanks for the suggestion
