### ISSUE TITLE
Deathrun issue: Sandman & Wrap Assassin

### ISSUE THREAD

**Issue by Rasphelon** [DFS-Servers/BugReportsAndSuggestions#17]
**Describe the Bug**
The Sandman and Wrap Assassin are enabled for deathrun. In maps where death and the Players can see each other, such as vsh_dr_crash_bandicoot_v6, both sides if using these weapons are able to attack and kill the opposite side, as the projectiles will pass through invisible walls.

**To Reproduce**
Find a deathrun map where Death and the Players can see each other without anything in the way (save for invisible walls), switch to Scout and use either weapon, then harass the opposite side with the projectiles.

**Expected Behavior**
Death and the Players are able to attack and kill each other using these weapons. For Death specifically, this can mean attacking / killing players without using traps, or making traps even more difficult. For the Players, this means potentially ruining the game mode if enough players switch to this loadout with the intention of killing Death.

**Server Info**
 - Region: All Servers

**Additional Context**
This also applies to maps with certain minigames where there's only an invisible wall between Death and the Players, such as dr_aconian, with it's revolver roulette minigame. These weapons used to be white-listed as they could be used to break walls during the bulldozer section of dr_safety_first, but now they aren't.

**Comment by Dispenz0r** [comment]
Will be fixed on next maintenance, should be an easy fix. Although I could also replace the map with something new as well, we'll see how it goes.
