### ISSUE TITLE
New gamemode idea: Instagib

### ISSUE THREAD

**Issue by Kray0la** [DFS-Servers/BugReportsAndSuggestions#170]
**Is your feature request related to a problem?**
No.

**Describe your suggestion**
Best known from Unreal Tournament, everyone knows how it functions. Since I managed to pull it off in events, I thought it would be a cool idea to bring it into our regular rotation of game modes. Events restrict an annoying wait time of about 5 seconds of respawning time, while an official game mode for it is faster, quicker, and more fun in the long run. The only real question is which plugins and maps would be best for it.

**Describe alternatives you've considered**
So far I have found this on AlliedModders, however, the plugin seems to have hit past its golden age, as the last update for it was in 2012. Giving it a shot wouldn't hurt, I bet:
https://forums.alliedmods.net/showthread.php?p=736105

I do also know that *certain TF2 communities* hold their version of Instagib, which are open source somewhere on other websites. However, I was not able to find them at this point. They might be superior to the version given above.

**Comment by qli-p** [comment]
Also needs UT announcer and if not that then the quake 3 announcer for maximum authenticity

**Comment by Kenzzer** [comment]
You're probably referring to: https://github.com/haxtonsale/TF2Instagib

Currently running on The Red Sun Over Paradise tf2 community.

**Comment by Dispenz0r** [comment]
The plugin you linked to is very outdated and will most likely not continue to work properly anymore

I might consider using the plugin Kenzzer posted above in the future though.

**Comment by Dispenz0r** [comment]
ok fine
