### ISSUE TITLE
Mario Kart Map Gamemode Confusion (dm_mariokart_b3)

### ISSUE THREAD

**Issue by Creataurus** [DFS-Servers/BugReportsAndSuggestions#171]
**Is your feature request related to a problem? Please describe.**
It's quite confusing to me that some of the mario kart maps before used to have different gamemodes than they currently do.
dm_mariokart_b3 used to be friendly but now it's considered competitive, this is my primary issue.
mario_kart_2012_b3 as far as I remember was always comp so that's fine.
mario_kart_2_b3 is friendly but is designed to be a comp map, albeit it being considered friendly seems fine by me.

**Describe your suggestion**
I'd suggest reverting dm_mariokart_b3 back to being considered a friendly map so that we can continue to have shenanigans on that map like we did before.

**Describe alternatives you've considered**
I've also considered making every mario kart map friendly maps but I don't know how the rest of the playerbase would react to that, primarily with mario_kart_2012_b3 being comp for long enough for DFS to get used to it.

**Comment by Dispenz0r** [comment]
It all boils down to personal preference honestly, I don't really find it confusing for a dm_ map to be treated as a comp map

I _might_ consider swapping their gamemodes in the future but I feel like they are fine as of now.

**Comment by Creataurus** [comment]
I know this is closed, but I'd just like to add the exception to the dm_ maps being comp rule with dm_SDM_final being considered friendly.

**Comment by Dispenz0r** [comment]
Don't reply to closed issues.
