### ISSUE TITLE
Spies being able to disguise into friendlies

### ISSUE THREAD

**Issue by MrEdzilla** [DFS-Servers/BugReportsAndSuggestions#172]
On the map koth_frostmoon_event_rc2b, I was backstabbed and killed by a spy who, while disguised as a Scout, had the _alpha_ from friendly-mode, because he was disguised as a Scout on my team who had friendly-mode on. This is the first time it has happened to me, so I can't say for sure if it was a one-time thing or if it's simply not triggered that often.

**Comment by Light08** [comment]
Need more confirmation if that's really the case.

**Comment by Dispenz0r** [comment]
That shouldn't be possible at all, but I'll test it soon to confirm if it happens or not

**Comment by Dispenz0r** [comment]
Just tested this, there seem to be no issues whatsoever with the disguises
Could have been somebody toggling alpha on themselves manually.
