### ISSUE TITLE
Novelty Feature Suggestion: tf_playergib 0

### ISSUE THREAD

**Issue by Argo7200** [DFS-Servers/BugReportsAndSuggestions#173]
**Describe your suggestion**
This is a silly suggestion, but I think it'd be quite fun if from time to time tf_playergib was set to 0. 

This forces all kills to produce a ragdoll. Kills that cause gibs usually exert a great amount of force on physics objects and so this server command would result in ragdolls flying around everywhere during play, which I think would be quite amusing as a bonus novelty mode in the same vein as the weapon randomiser vote.

**Comment by Light08** [comment]
Sounds more like an idea for a Module.

**Comment by Argo7200** [comment]
Perhaps, but I still personally think I'd be more fun if it were a server-wide function.

**Comment by Light08** [comment]
Could be considered for events or usual root shenanigans. The module might be a perma solution for individual players.
