### ISSUE TITLE
Implementing a Proper Instant Respawn 

### ISSUE THREAD

**Issue by Argo7200** [DFS-Servers/BugReportsAndSuggestions#174]
**Is your feature request related to a problem? Please describe.**
I know I've made this suggestion before, but I feel compelled to ask  again. This would be a quality-of-life change that I think many would appreciate. Right now, pretty much everybody bypasses the odd 3-4 second respawn peroid by switching classes, which is a cumbersome workaround that gets tiresome when one has to respawn over and over. 

**Describe your suggestion**
Many other servers seem to feature this functionality so I can't imagine it being hard to implement. Either that or, if you insist on there being a brief respawn-time period, implement a change that prevents people from bypassing the period by switching classes.

If I recall correctly, @Light08 figured that this wouldn't be hard thing to fix, so I implore you to reconsider.

**Comment by Light08** [comment]
Just change respawntime to 0.1 seconds lmao. But disp refuses so... *shrug*

**Comment by Argo7200** [comment]
So it'd literally take just 1 minute to adjust...

**Comment by Dispenz0r** [comment]
It does not matter if it takes 10 hours, 10 minutes or even 10 seconds to change, the decision of making the change is up to me only and nobody else.

That being said, the "fix" attempt you've mentioned did not work at all the last time I tested it @Light08.

I'll see if I can work around implementing proper instant respawns in the near future though.

**Comment by Dispenz0r** [comment]
The cvar method as I expected and tested before does not work the way you expected it to work. 
It will probably require a plugin to properly implement instant respawns, I'll consider adding it if I can get my hands on one in the future.

**Comment by Light08** [comment]
Weird, it used to work before.
