### ISSUE TITLE
Make buildings unbuildable on air_hockey

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#175]
People use them to block off the goals and it often means that one team has an unfair advantage over the other

**Comment by Dispenz0r** [comment]
Doesn't really matter that much since the map is a friendly map and not meant to be a competitive map to begin with.

**Comment by GreenSwede** [comment]
If the unfair advantage is that the other team gets crits, let me know and I can look into it. Otherwise I can't see what advantage they get as the puck doesn't score any goals anymore after the edited config I have added.
