### ISSUE TITLE
dm_SDM_final Not Working

### ISSUE THREAD

**Issue by Creataurus** [DFS-Servers/BugReportsAndSuggestions#178]
**Describe the bug**
When I attempted to join the US server earlier, the map was dm_sdm_final, and the game said the following: "Your version of dm_sdm_final.bsp doesn't match." And I was unable to join.

**To Reproduce**
1.) Connect to a DFS server with dm_sdm_final as the map
2.) Disconnect due to your bsp file apparently being different.

**Expected behavior**
I should be able to connect to the server without any issues.

**Server Info (please complete the following information):**
 - Region: US
 - IP 194.24.171.83:27185

**Additional context**
I tried to remove my bsp file of the map and install a supposed correct version of the file and it didn't work either.

**Comment by Dispenz0r** [comment]
Try removing the .bsp file again and download the map directly from the server itself, should work properly after.

**Comment by Light08** [comment]
Not exactly a server issue, but a client issue. Remove the .bsp from your maps & download/maps folder and redownload it from the server or any other source that uses our version.

**Comment by Creataurus** [comment]
I've tried that, but I don't exactly know which version to chose from, I tried the version from the steam workshop and it didn't work. The server didn't even download a new version when I tried it regardless.

**Comment by Light08** [comment]
Workshop maps are **never** compatible with custom maps outside of the workshop. They're treated as their own version. May be good for vanilla servers but interms of custom servers, the workshop is just horrible.

**Comment by Dispenz0r** [comment]
Try downloading the map from scratch from the server itself, that should solve your problem.

**Comment by Creataurus** [comment]
Unfortunately, I don't know how to download files directly from the server other than joining it, and that didn't seem to work.

**Comment by Dispenz0r** [comment]
Delete your own version of the .bsp file and download it from https://steamcommunity.com/sharedfiles/filedetails/?id=456095137

If it doesn't work it could be related to your TF2 or you very likely didn't properly delete the map file.
