### ISSUE TITLE
Slender Fortress bug: Proxies still have models applied from model manager pluign

### ISSUE THREAD

**Issue by Pro100RedMushroom** [DFS-Servers/BugReportsAndSuggestions#179]
> **Steam Profile**
> A link to your Steam profile (optional).

> **Describe the bug**
> A clear and concise description of what the bug is, what can be done to reproduce it, if applicable.

the model doesnt change after being picked up as a proxy

> **To Reproduce**
> Describe the steps to reproduce the bug.

1. open the sm_mm menu and apply any model
2. wait until you are a proxy

> **Expected behavior**
> A clear and concise description of what you expected to happen.

the model should be changed to a model that is more appropriate for the boss (crab for the crab boss etc)

> **Screenshots or error logs**
> If applicable, add screenshots or error logs to help explain your problem.
> 

https://www.dropbox.com/s/mavks6r2yadj8vp/hl2_1hCogULRcI.png?dl=0 a screenshot where i was picked up as a proxy while having a playermodel on

> **Server Info (please complete the following information):**

Region: [e.g. EU]
IP [e.g. 89.35.29.11:27145]

> **Additional context**
> Add any other context about the problem here.

its more difficult to survive since there is almost no way of distinguishing between a player and a proxy

**Comment by Light08** [comment]
Aware. I might have a possible fix later this week.

**Comment by Glubbable** [comment]
You'll need to add the following as checks in the command or menu function itself. Preferably both to be safe.

SF2_IsClientProxy
SF2_IsClientInGhostMode

Also make sure to use MarkNativeAsOptional on them under AskPluginLoad2 otherwise you might encounter errors if SF2 isn't active.

**Comment by Light08** [comment]
Yeah, that was exactly the solution I wanted to apply before I went on vacation.

**Comment by Dispenz0r** [comment]
This should hopefully be fixed now, thanks for the report!
