### ISSUE TITLE
[BUG] Avoiding gag with global chat

### ISSUE THREAD

**Issue by RealStrade** [DFS-Servers/BugReportsAndSuggestions#18]
As the title says, it is possible to avoid a source gag by simply typing in global chat. 

**To Reproduce** : Get gagged, use /global <text>.

**Expected behavior** : Gagged people shouldn't be able to type anything whatsoever.

**Screenshots** : ![capture d ecran 40](https://user-images.githubusercontent.com/42638723/44516999-cd209480-a6c6-11e8-8c01-d238cf1f9a6f.png)
![capture d ecran 41](https://user-images.githubusercontent.com/42638723/44517009-d4e03900-a6c6-11e8-9a2c-8b9d1157226a.png)

**Server Info** :  - Region : EU | UK
IP : 89.35.29.11:27145

**Comment by Light08** [comment]
Easy fix. Thanks for the report. Will be fixed with the next hotfix, possibly on monday.
