### ISSUE TITLE
Affinity Particle visible on cloaked Spy, only when disguised

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#181]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
The Affinity Particle can be seen on cloaked Spies, but only when they are wearing a disguise.

**To Reproduce**
1. Have an enemy equip the Affinity Particle and a disguise
2. Have the enemy Spy cloak and observe

**Expected behavior**
The particle should not be visible while cloaked.

**Server Info (please complete the following information):**
EU - 89.35.29.11:27145

**Comment by Afterstormer** [comment]
Apparently, the same applies to every module.
![MyMovie](https://user-images.githubusercontent.com/42520820/65717346-04672f00-e099-11e9-979a-d074ff3aa35f.gif)

**Comment by Light08** [comment]
Seems to be fixed now since the bug cannot be replicated anymore.
To be honest, I'm not even sure what I did or what caused it but whatever I did seemed to have fixed it?
Good enough for me.
