### ISSUE TITLE
Every slender map having 12 max people for rounds

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#182]
**Steam Profile**
https://steamcommunity.com/id/vilxxu/

**Describe the bug**
I believe that this is a bug that every slender map has 12 max people for rounds

**To Reproduce**
1. Go on the EU server on DFS 
2. Play slender there
3. Max players for every round is 12 people
 
**Expected behavior**
Slender maps having their dedicated player amount for round.

**Server Info**
 - Region: [EU]
 - IP [89.35.29.11:27145]

**Comment by Dispenz0r** [comment]
Yep I'm aware, gonna change it to only have 12 max players on the silent hill map only. 
Should be fixed this Monday.

**Comment by Dispenz0r** [comment]
This should be fixed now, thanks for the report.
