### ISSUE TITLE
Bug: Payload carts can be sapped, prevents healing from cart.

### ISSUE THREAD

**Issue by miniz1994** [DFS-Servers/BugReportsAndSuggestions#184]
**Steam Profile**
https://steamcommunity.com/id/miniz1994

**Describe the bug**
pretty much in payload gamemode the carts can be sapped by any red spy, if its done the kart doesnt heal any blue anymore & sapper is also not removable by anyone until round ends via a win or running out of time.

**To Reproduce**
Describe the steps to reproduce the bug.
1. Sap dispenser floating that used too be bombcart up until some update.
2. watch the other team struggle too finish the map without healing from the cart.

**Expected behavior**
Ofc it shouldnt be possible too sap it at all and it's also not supposed too be invisible, not sure if its something among my game files that messes that up or something with the server plugins that causes it as im writing this, ive verified the gamefiles and it remains invisible (can see the dispenser still ofc ontop of it.)

**Screenshots or error logs**sapped here & invisible as mentioned.
https://steamcommunity.com/profiles/76561198024940721/screenshot/781858739040965572

**Server Info (please complete the following information):**
Both servers that it works on probably, currently as im writing this on EU

**Comment by Dispenz0r** [comment]
We don't really work on the STT plugin so I'll redirect you to https://github.com/akowald/StopThatTank/issues instead.
