### ISSUE TITLE
Stickybomb Launcher not working

### ISSUE THREAD

**Issue by Nardor** [DFS-Servers/BugReportsAndSuggestions#185]
**Steam Profile**
https://steamcommunity.com/profiles/76561198394404946

**Describe the bug**
When I tried to launch a sticky bomb it didn't appear so I tried launching it in the air and noticing it dissapear when hitting the ground

**To Reproduce**
1. Go on the EU server on DFS
2. Launch a stickybomb

**Expected behaviour**
The sticky bomb should do it's job by standing in the point from it was launched

**Server Info**
- Region [EU]
- IP [89.35.29.11:27145]

**Additional context**
I tought this problem was just in MicroTF2 but I noticed later that this problem was in normal comp too.

**Comment by Dispenz0r** [comment]
Should be fixed now, thanks for reporting.
