### ISSUE TITLE
Class Selection in Randomizer

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#186]
**Is your feature request related to a problem? Please describe.**
Randomizer proves to be an unpopular plugin, rarely getting used and causing a lot of annoyance when it's turned on. One of the main problems is that it gets in the way of working on quests, especially class quests since you can't select your class in Randomizer.

**Describe your suggestion**
I think changing the way Randomizer works to allow players to choose their class would reduce how much the mode gets in the way of completing quests and may make it less poorly received.

**Describe alternatives you've considered**
Honestly, I can't really think of any other ways to reduce how much Randomizer gets in the way of completing quests without undermining the randomness of the mode.

**Comment by Dispenz0r** [comment]
Classes should no longer get randomized in Randomizer
