### ISSUE TITLE
Can we nerf the hard hitter quest?

### ISSUE THREAD

**Issue by vyquad** [DFS-Servers/BugReportsAndSuggestions#187]
**Is your feature request related to a problem? Please describe.**
i think that 1K damage for the hard hitter quest is a bit excessive and hard

**Describe your suggestion**
i was thinking maybe putting it to 600-700 damage, nothing too huge too small

**Comment by Creataurus** [comment]
Personally, this could go hand in hand for the bulletsponge and first aid quests as well, but that's up to the devs to decide.

**Comment by Dispenz0r** [comment]
I'll be working on adjusting the quests, their requirements as well as their rewards soon

**Comment by Dispenz0r** [comment]
Expect revamped quests as well as revamped quest requirements and rewards soon
