### ISSUE TITLE
Dodgeball doesn't count as a Custom Gamemode

### ISSUE THREAD

**Issue by Leafpad** [DFS-Servers/BugReportsAndSuggestions#188]
I had a Custom Gamemode quest sitting for a few days and Dodgeball did not register on the quest for time. I was not in spectator, I was an active participant.

Have that quest, play Dodgeball

**Comment by Light08** [comment]
Do you know which map it was?

**Comment by Leafpad** [comment]
TFDB_Blockland iirc

**Comment by Light08** [comment]
The plugins should work properly in that case. Not sure what went wrong but I'd like to hear if someone else can confirm this or not.
