### ISSUE TITLE
Quest Daily Broken

### ISSUE THREAD

**Issue by OneTwoThreeA** [DFS-Servers/BugReportsAndSuggestions#19]
So I Quest Complete In Din't Do Anything is said On Cooldown 1 Day I Woke Up I open Team Fortress 2 I Get In A Server I Type Commands A Quest Is Still Cooldown Fix Please Thanks !

My Username: [DFS] HHH111111..... 
IP: 89.35.29.11:27145

**Comment by Light08** [comment]
It was actually implemented since release but the damn event just won't work on the database.
Worst case I'll just do the same thing as with daily logins.

**Comment by Dispenz0r** [comment]
Should be good now, thanks for reporting.
