### ISSUE TITLE
New Module Suggestion

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#190]
**Is your feature request related to a problem:**
Yes, my unhealthy addiction to a weeb MMO.

**Describe your suggestion:**
When I got my hands on an Ascendant weapon in MS2, I wondered how cool it would be if this was a Legendary effect in one of those Lootchests.

**Describe alternatives you've considered:**
There are other badges that I can find in the game, so I can keep bugging you for them. :>

**Additional context:**
![Effect](https://user-images.githubusercontent.com/42520820/65378884-d65ba680-dcb6-11e9-8d25-81940ba9a4e3.gif)
(What it looks like.)

**Comment by Light08** [comment]
Custom particles are impossible to properly achieve in TF2.
