### ISSUE TITLE
Can we disable civil war on slender?

### ISSUE THREAD

**Issue by vyquad** [DFS-Servers/BugReportsAndSuggestions#192]
Is your feature request related to a problem:
Yes

Describe your suggestion:
I want Civil War to be disabled because a lot of people including me do not really like it and some other people would like it removed
and if i recall, someone said something along the lines of "im fine with slender but i dont like the class wars"

**Comment by Glubbable** [comment]
The Class Civil War ony applies to PvP and was intended to spice up the PvP arena from time to time from the usual free for all.

Regardless, Disc can set set sf2_pvp_classwar_threshold to 0 to disable Class Wars for PvP.

**Comment by Dispenz0r** [comment]
I've made the threshold a little longer than the default setting, thanks @Glubbable
