### ISSUE TITLE
Rat King Proxy Models

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#193]
**Describe the Bug:**
The proxies for Rat King still have their models equipped from /mm.

**To Reproduce:**
1. Equip a model from /mm
2. Wait for the boss to be Rat King
3. Get selected as a proxy

**Expected Behaviour:**
Our model should be those karate "things" that kick RED's ass.

**Screenshots or Error Logs:**
![Untitled](https://user-images.githubusercontent.com/42520820/65994592-9d2bef00-e48b-11e9-9f7d-e0299865f684.png)

**Server Info:**
 - Region: EU | UK
 - IP: 89.35.29.11:27145

**Additional Context:**
Crog Brute has been fixed since I can see their proxy model perfectly fine.

**Comment by Dispenz0r** [comment]
Issue should be completely resolved now, thanks for reporting.
