### ISSUE TITLE
Resize commands are availible in stadium bosses

### ISSUE THREAD

**Issue by vyquad** [DFS-Servers/BugReportsAndSuggestions#194]
**Steam Profile**
A link to your Steam profile (optional).

**Describe the bug**
Resize commands are usable where they should not be

**To Reproduce**
1. Go to stadium
2. Go into any boss
3. Do any resize command

**Expected behavior**
Resize commands are blocked

**Screenshots or error logs**
No errors

**Server Info**
EU Server 89.35.29.11:2714

**Additional context**
Certain resize commands such as resizeme can provide a competitive advantage

**Comment by Light08** [comment]
Fixed.
