### ISSUE TITLE
Conductor/DJ Grooves Boss Fight Not Playing Music Nor Sound

### ISSUE THREAD

**Issue by Creataurus** [DFS-Servers/BugReportsAndSuggestions#196]
**Describe the bug**
When you fight the Conductor/DJ Grooves, their battle music will not play, nor will sound effects play out as they usually would in the Shadow Realm. The music when the hat appears still plays as normal however.;

**To Reproduce**
1. Start a Conductor/DJ Grooves Fight
2. Wait until the elevator stops and the door opens
3. Initiate the fight
4. The music won't play nor sound effects will play.

**Expected behavior**
The music and sound effects should play as before the update.

**Server Info (please complete the following information):**
 - Region: EU
 - IP  89.35.29.11:27145

**Comment by Light08** [comment]
Should _probably_ be fixed by the next server update.
