### ISSUE TITLE
Various issues after disabling Instagib

### ISSUE THREAD

**Issue by synoptlc** [DFS-Servers/BugReportsAndSuggestions#197]
**Describe the bug**
Any changes made by Instagib in order to avoid any complications with the game mode, still remain even after disabling it, such as:
Any objective given in normal gameplay is removed. (Example being locked control point in dm_flood_redux)
Health kits, ammo kits and the resupply lockers remain removed from the map.
Player Destruction game mode (Used mainly for scoring each kill during Team Deathmatch as an example) still remains, also being able to pickup the flags to become the team leader, receiving unfair advantages during normal gameplay.

**To Reproduce**
Enabling then disabling Instagib.

**Expected behavior**
Any changes made by Instagib will revert once disabled, changing to normal gameplay with returning the original objective and entities.

**Comment by Light08** [comment]
It's the way how Instagib works. Might be a little bit tough fixing this without influencing Instagib Gameplay too much, but I'll take a look at it whenever I have time for this.

**Comment by Creataurus** [comment]
Also I believe certain things are removed from the map as well, such as dm_towerleap's doors for the elevators.

**Comment by Dispenz0r** [comment]
Should hopefully be fixed now(?)

Feel free to post a comment into here if these issues occur again and I'll re-open it.
