### ISSUE TITLE
Event Quests "Skeleton War" and "Dreadful Encounter" are not working.

### ISSUE THREAD

**Issue by gdfsgdfg** [DFS-Servers/BugReportsAndSuggestions#198]
**Steam Profile**
https://steamcommunity.com/id/ohhnoo/

**Describe the bug**
Killed a bunch of skeletons and hhh/monoculus. Tested on stadium and frantic factory.

**Expected Outcome**
Getting points in the quests.

**Server Info (please complete the following information):**
198.24.171.83:27185

**Note**
If those quests were meant for valve's halloween maps those can't be nominated.

**Comment by Light08** [comment]
Due to last minute changes these missions ended up unobtainable.
I changed them to two new ones as backups. Should work now.
