### ISSUE TITLE
Skins from pumpkin baskets being tradeable 

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#199]
**Steam Profile**
https://steamcommunity.com/id/vilxxu/

**Describe the bug**
This bug is that you can trade the former campaign skins from pumpkin baskets.

**To Reproduce**
1. Obtain a pumpkin basket
2. Unbox a former campaign skin 
3. Item seems to be tradeable
**Expected behavior**
As said before in the patchnotes, the item should be untradeable

**Server Info**
 - Region: [EU]
 - IP [89.35.29.11:27145]

**Additional context**
This could severely decrease the prices of the campaign skins.

**Comment by Light08** [comment]
Citation needed.

**Comment by Dispenz0r** [comment]
This is intentional, just so you know.
