### ISSUE TITLE
A bug after a maintenance

### ISSUE THREAD

**Issue by xWhiteWolfx** [DFS-Servers/BugReportsAndSuggestions#2]
So today I've done prestige to the bronze tier in the server now before the maintenance I bought 2 shiny stones and leveled up to ''Bronze Leader'' now after the maintenance I bought 3 more shiny stones and found that my progress is lost like instead of being champion which is the 5th rank ''Bronze Champion'' I found myself in the 3rd rank ''Bronze Elite''

**Comment by Dispenz0r** [comment]
Should be fixed now.
