### ISSUE TITLE
Fire Freakshow changes have auto-completed the quest for players with between 33-65 kills, making the rewards and Jungle Inferno inaccessible.

### ISSUE THREAD

**Issue by BrokeMachine** [DFS-Servers/BugReportsAndSuggestions#200]
**Steam Profile**
https://steamcommunity.com/id/BrokeMachine/

**Describe the bug**
This bug has made the rewards for Fire Freakshow inaccessible to anyone who hadn't previously completed it, but are above the current point threshold. The Jungle Inferno mission is also inaccessible to anyone who had previously completed the other 3 Forest Fire missions beforehand.

**To Reproduce**
1. *Have had between 33-65 mmmph kills before the change.*
2. Go to the Forest Fire campaign node.
3. Fire Freakshow will be completed, but will say __/33 kills instead of a 100% progress bar. 
4. Jungle Inferno will be locked and you wont receive the Pumpkin Baskets.

**Expected behavior**
Players would automatically be accredited for the mission completion upon their next login, gaining access to the rewards and Jungle Inferno.

**Screenshots or error logs**
![bug1](https://user-images.githubusercontent.com/57463798/68340514-8017bb00-00de-11ea-9163-f51b21c2e09e.PNG)
![bug2](https://user-images.githubusercontent.com/57463798/68340537-860d9c00-00de-11ea-9b7a-188649bc7b3e.PNG)

**Server Info (please complete the following information):**
 - Region: EU + USA
 - IP 89.35.29.11:27145 + 198.24.171.83:27185

**Additional context**
I've relogged multiple times since discovering this issue and nothing has changed.

**Comment by Light08** [comment]
Fixed. Just reconnect.
