### ISSUE TITLE
Boss battle arena bug

### ISSUE THREAD

**Issue by synoptlc** [DFS-Servers/BugReportsAndSuggestions#201]
**Steam Profile**
https://steamcommunity.com/id/synoptlc/

**Describe the bug**
In tm_stadium, after defeating Conductor/DJ Grooves, a teleport to the private apartment in form of a hat will spawn. However if someone spawns a boss (that also spawns a teleporter after defeat) from boss battle arena the teleporter breaks, unable to teleport and reward anyone who has beaten the boss.

**To Reproduce**
Spawn any boss in boss battle arena's master room that spawns a teleporter once killed during the battle with Conductor/Grooves.

**Expected behavior**
To avoid any complications during the boss battle, a teleport to the boss battle arena's master room will be disabled.

**Comment by Light08** [comment]
This makes absolutly no sense. The fuck did Valve break this time again...

**Comment by Light08** [comment]
Unless there's proof of this occuring more than once, I'll close this issue since I don't recall anyone ever report this besides you. Might have been a one-time case.
