### ISSUE TITLE
Classes cannot change in Randomizer

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#202]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
Classes cannot be changed in Randomizer, either by the mode itself, or by the player. Attempting to change class will result in the player respawning as the same class. It seems that the player can only play as the class they were using when Randomizer activated.

**To Reproduce**
1. Enable Randomizer
2. Attempt to change class

**Expected behavior**
You should be able to change class and not be respawned as your current class.

**Server Info (please complete the following information):**
EU 89.35.29.11:27145

**Comment by BimboBumboBambo** [comment]
I think as far as my knowledge goes, this isn't a bug and a feature of randomizer to prevent people from getting the strongest loadouts constantly.

You have to damage/kill to make it randomize again.

**Comment by Limeball** [comment]
Normally, that is the case, but our most recent update was intended to change it so you could manually change classes in order to avoid Randomizer interfering with Quests (as per this closed suggestion: https://github.com/DFS-Servers/BugReportsAndSuggestions/issues/186) 

Now, not only is this not possible, your class doesn't change on death either.

**Comment by Light08** [comment]
Aye, I'll investigate. As for the broken Flamethrower, that's a tough one.

**Comment by FortyTwoFortyTwo** [comment]
I would've commented about Flamethrower in #208 but that's locked.

Jungle Inferno added several new attributes to control how Flamethrower flames act like. "No flame distance" is because given flamethrower don't have any of those new attributes, plugin will need to give those to fix it.

From `item_game.txt`, new flames attribute and default values used for new Flamethrower.
```
		"weapon_newflame"
		{
			"static_attrs"
			{
				"flame_gravity"							"0"
				"flame_drag"							"8.5"
				"flame_up_speed"						"50"
				"flame_speed"							"2450"
				"flame_spread_degree"					"2.8"
				"flame_lifetime"						"0.6"
				"flame_random_life_time_offset"			"0.1"
			}
		}
```

**Comment by Light08** [comment]
Updated Randomizer to allow class changing now.
