### ISSUE TITLE
Super Zombie Fortress End of Round Suggestion

### ISSUE THREAD

**Issue by Creataurus** [DFS-Servers/BugReportsAndSuggestions#204]
**Is your feature request related to a problem? Please describe.**
It intrigues me how the game abruptly ends when a szf round's map timer turns to 0, so I think that it could be improved a bit.

**Describe your suggestion**
I'd like it as to where when the map timer turns to 0, the round will continue until either every human is dead or the humans win.

**Describe alternatives you've considered**
There are no alternatives to this to be honest.

**Comment by Light08** [comment]
Are you referring to the actual "round" timer or the maptime limit?
As for the former one, that one is decided by maps themself. In other words, it's intentional and we won't change that.
As for the later, it shouldnt abruptly end the round when the maplimit goes 0.

**Comment by Creataurus** [comment]
I'm referring to when the map timer reaches 0, it abruptly ends the round. The round timer is just fine, but as you stated, the maptimer reaching 0 shouldn't abruptly end the round.

**Comment by Dispenz0r** [comment]
I know what causes this issue, I'll get it fixed for an upcoming server update.

Do you happen to know if other gamemodes are having the exact same issue as this or is it just SZF alone?

**Comment by Creataurus** [comment]
I do actually, and surprisingly one of them Deathmatch, particuarly with dm_flood and the round ending abruptly when the maptimer reaches 0 as well as all szf maps. I think I know some more but I don't remember at the top of my head when typing this, maybe we could try to test some maps in a testing session on the us server to figure out the problem?

**Comment by Dispenz0r** [comment]
The issue mentioned above should now be completely fixed.

The issue with slender and other maps changing too early before the map timer ends should also be fixed and work properly now.
