### ISSUE TITLE
Being able to cap the third point outside of the base in szf_pen15

### ISSUE THREAD

**Issue by BimboBumboBambo** [DFS-Servers/BugReportsAndSuggestions#205]
**Steam Profile:** http://dfs.boards.net/thread/1758/application-bock?page=1&scrollTo=31235

**Describe the bug:** As simple as it sounds, you're able to capture the third point outside the base by standing on a ramp outside the base. This counts as standing inside the upstairs section of the base and as a result you start the capture.

**To Reproduce:**

- Take the left side lift towards the second entrance.

- Only soldiers/demos/wrangler engies can reach the ramp. Rocket/sticky jump or bullet knock yourself onto the ramp.

- Stand on the ramp and you start the capture.

- The ramp also gives zombies no chance to hit you, with the exception being Hunters and Smokers who can take you down from the ramp.

**Expected behavior:** I hope this is fixed. As of now no one does it, however if someone knows of the bug a match quickly can become tedious and campy.

**Server Info:**
> EU
> 89.35.29.11:27145

**Additional context:** Depending on the amount of zombies present, this bug either works in favour of the survivor acting it out or basically makes him a target practice.

![bock](https://user-images.githubusercontent.com/41446589/68999483-0b543600-08c1-11ea-80a8-fd1d7debb552.png)

**Comment by BimboBumboBambo** [comment]
NOTE: I found this bug on pure accident. After that I went back to take the screenshot(seen above,) seeing as I was going to be knocked out anyway.

**Comment by Dispenz0r** [comment]
Not really a DFS specific issue so not much we can do about.

Though I've been told by Alex Turtle (the author of this map) that the map will receive an update sometime in the future which should have this issue fixed completely.
