### ISSUE TITLE
tm_stadium snatcher problem: puppets can cause lag

### ISSUE THREAD

**Issue by Pro100RedMushroom** [DFS-Servers/BugReportsAndSuggestions#207]
**Profile link**
http://steamcommunity.com/id/Pro100_Mad_Pro_Red_Mushroom

**Describe bug**
when the puppets appeared during the snatcher fight the whole eu server started to lag

**To reproduce**
1. we went to stadium while being on the eu server
2. we opened well and started the snatcher boss fight
3. when the puppets appeared, it started to heavily lag for all of the players on the server

**Expected behaviour**
the lag should not be happening

**Screenshots/proof**
https://www.dropbox.com/s/nyvhar6mu30a930/when%20puppets%20appeared.png?dl=0
https://www.dropbox.com/s/v7xx20g0poox71w/hl2_CZfF3b1rGM.png?dl=0
https://www.dropbox.com/s/mveor78w02nvip6/when%20puppets%20disappeared%20during%20the%20fight.png?dl=0
https://www.dropbox.com/s/46gr32jxenqoyua/when%20snatcher%20was%20defeated.png?dl=0
https://www.dropbox.com/s/5kbl59vk38i9wm1/right%20after%20bossfight.png?dl=0

notes: 
1. the lag wasnt client-sided
2. it seemed to happen because there were about 20 players in the arena
3. when the puppets disappear the lag seems to stop

**Server Info**
EU server
https://www.dropbox.com/s/u36vagtlayx70v4/ShareX_4yG99Bv6kj.png?dl=0

**Comment by Creataurus** [comment]
Might be some sort of NPC overload of some sorts, where there's too many npcs for the game to handle, though we've had situations where we've had more players and this issue didn't occur I don't think.

**Comment by Light08** [comment]
Some changes towards the pathing have been done.
It might fix the lags, time will tell.

**Comment by Dispenz0r** [comment]
Issue should be fixed now, thanks for reporting.
