### ISSUE TITLE
Broken Flamethrower Hit Registration in Randomizer

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#208]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
Flamethrower weapons have no range in Randomizer, requiring players to get extremely close to enemies to deal damage (only been able to test on Heavy due to https://github.com/DFS-Servers/BugReportsAndSuggestions/issues/202)

**To Reproduce**
1. Enable Randomizer
2. Acquire a Flamethrower weapon
3. Attack an enemy

**Expected behavior**
The flamethrower should act as normal and be able to damage enemies with its normal range

**Server Info**
EU 89.35.29.11:27145

**Comment by Dispenz0r** [comment]
Not much we can do regarding this due to how the Randomizer plugin works, will re-open this in the future if we ever find a solution for it.

**Comment by Light08** [comment]
This feels familiar to the Prophunt issue we had with the inferno update.
I got reason to believe its related to that update's changes to the Flamethrower, might dig this up once I have the time for it.

**Comment by Light08** [comment]
Fixed.
