### ISSUE TITLE
Issue | Guild Rank | Can't level up twice (passing though MEP limit)

### ISSUE THREAD

**Issue by Grandpa-niko** [DFS-Servers/BugReportsAndSuggestions#21]
**Steam Profile** : https://steamcommunity.com/id/nikoiro680

I would like to report an issue where players may get pass though the rank exp to level up.

**Describe the bug**
let's think about a new player (rank 1) completed a normal quest, and grants 50 MEP which is the exact needed for level up rank 2, you finish it and you level up, not an issue at all, carry on.
However, By finishing a a weekly quest (1000 MEP) should grant you to level up 3-4 times instantly, but instead it only makes you level up once and your MEP limit is being passed though your gained
example : 
New player (rank 1) completed a weekly challenge quest, you only needed 50 MEP to level up to Rank 2 and you are aware that you can go even rank 4 instantly, but instead you only reach level 2 with that extra MEP you gained and says in the title "rank 2| 1000/150 MEP"

Now this can be fixed if you complete another quest, doing so the MEP will update again and level up normally, but once again if you still have more MEP than the required, you would have to complete another quest to level up again
I also Tried to rejoin the same server or join in another server from DFS but the Issue is still there.

Here, In the attached image (You can see it at the bottom) We can see that I am **rank 4** but for some reason my MEP is **1400/1000 MEP** 
That is because I completed a Weekly Challenge Quest, Being rewarded 1000 MEP  and it should have leveled up 2 times (rank 5) instantly, but instead it only did once

**Server Info**

Region: [US|EU Servers]

**Screenshot(s)**
![inked20180824220145_1_li](https://user-images.githubusercontent.com/42687863/44614459-2f7ab180-a7fb-11e8-9a2b-65ea4c58befc.jpg)

**Comment by Light08** [comment]
Will be fixed today.
