### ISSUE TITLE
Weapons Enabled in Slender Fortress

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#210]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
Weapons are enabled in certain areas they should not be in Slender Fortress, notably on RED Team in the main Slender play space and for proxy players on BLU Team, which reportedly allows proxies to shoot and kill RED Team players.

**To Reproduce**
1. Load a Slender Fortress map
2. Enter a round as a RED Team member/be selected as a proxy
3. Select primary or secondary weapon

**Expected behavior**
Only melee weapons should be accessible by RED Team and proxy players

**Server Info**
EU 89.35.29.11:27145

**Comment by Dispenz0r** [comment]
Should be fixed now, thanks for reporting!
