### ISSUE TITLE
Donator Commands Not Working

### ISSUE THREAD

**Issue by biguty** [DFS-Servers/BugReportsAndSuggestions#212]
Steam Profile: https://steamcommunity.com/id/maxxprofithaltmann/

Describe The Bug: Using donator commands says "You do not have access to this command." in chat and prevents it from being used.

To Reproduce: Simply try to use a command such as /pose on a vip or gold account.

Expected Behaviour: The donator command should function for people who have donated.

Server Info: EU 89.35.29.11:27145

Additional Context: Donator models such as john wick still work despite the commands not working.

**Comment by Light08** [comment]
That's because DFS-embedded plugins run mainly on your membership donation level.
Regular non-DFS plugins still work on a permission level... **yet**.

In your case you probably weren't properly granted the permission level. You should get it relativly soon.

**Comment by Dispenz0r** [comment]
Apologies for the inconvenience @biguty, I've completely fixed this issue for you now.
