### ISSUE TITLE
Toning down the amount of metal in SZF/Damage of Flame Throwers during last man standing

### ISSUE THREAD

**Issue by BimboBumboBambo** [DFS-Servers/BugReportsAndSuggestions#213]
**Is your feature request related to a problem? Please describe.**
The fact that there's a forgiving amount of ammo in all SZF maps I know is something that gripes me, but manageable. What I don't like is when I see 4 engineers constantly spamming sentries, so the zombies have to bumrush one engi at a time. Even then it's gonna be a chore because of the amount of other survivors you have to deal with.

Another problem is that a good Pyro is near unstoppable when he's the last man standing. Twisting and thwirling like a ballarina, spewing flames everywhere destroying everything in sight but a good Tank. Pyro is just very unfun to play against and it doesn't help that even when you get the pyro there's always another one left.

I'd love Engineer and Pyro to be toned down a bit, so here are my suggestions.

**Describe your suggestion**
For the Engineer, I'd love a toning down the amount of metal they get from small and medium packs from 40 to 20 and from 100 to 50 respectively. This not only makes it that sentries aren't as spammable, but forces the Engi to move themselves all over the map to collect said metal.

As for Pyro: decrease Flame Thrower damage. They'd be forced to blast zombies away more often and count on their shotguns/flares to do the job. This gives the feeling that you are the last man standing instead of Doom Guy ripping and tearing through the whole zombie team.

**Describe alternatives you've considered**
If the metal nerf/Flame Thrower nerf is too much, I've considered some alternatives:

- Make sentries weaker and easily more damageable, for example like the sentries in one of the Turtle bossfights. They will be spammable, but are easily whooped around.

- Give the dispenser more value, like it's ammo restore feature. Of course, have this not be too strong.

- Make the Flame Thrower use ammo more rapidly. The damage will still be there, but it has to be used more carefully. This makes secondary weapons even more viable.

- Remove mini-crits from the Pyro. The normal Flame Thrower damage will still remain, but it won't mow down zombies as quick as it used to.

**Additional context**
I believe it can make the gamemode even more teamwork necessary than it is now. Zombies will stand a better chance in certain maps(especially on szf_bossrush_b4a) and the Engineer and Pyro are forced to think instead of turret spamming and W + M1-ing the whole enemy team.

**Comment by Dispenz0r** [comment]
We don't really maintain or work on the current SZF plugin we use, so I'll redirect this to the author of the plugin instead

**Comment by Dispenz0r** [comment]
You can open an enhancement/issue regarding this through this repo instead:
https://github.com/redsunservers/SuperZombieFortress
