### ISSUE TITLE
Truce Mode for PumpKing

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#214]
**Is your feature request related to a problem:**
When the PumpKing spawns, it's treated as a boss enemy, and most of the time, bosses in TF2 have a "truce mode" which allows both teams to not damage one another until it's killed or time runs out.

**Describe your suggestion:**
Truce mode should be enabled so accidental kills aren't possible since we need to work together to take down this foe.

**Describe alternatives you've considered:**
Ban everyone on the server except 1 person so they can't kill anyone.

**Additional context:**
Disp said it was a good idea and that I should suggest this, so I did. :>

**Comment by Light08** [comment]
Will be properly implemented in a future update, along with a potential CP map support.
For now, I have other prioritizies that needs to be taken care of for the upcoming Winter update.

**Comment by Dispenz0r** [comment]
Boss is mostly intended for friendly maps, defeats the purpose of comp gamemodes (koth only for now) if we enable truce mode on it.

We'll have to pass on this for now, this _may_ or _may not_ be implemented in the future with cp map support.
