### ISSUE TITLE
Cannot change class during instagib

### ISSUE THREAD

**Issue by Phal0** [DFS-Servers/BugReportsAndSuggestions#215]
**Steam Profile**
https://steamcommunity.com/profiles/76561198071184624/

**Describe the bug**
You cannot change class when instagib is enabled through a vote.

**Expected behavior**
The latest update is supposed to allow you to change class in instagib.

**To Reproduce**
1. Go to any deathmatch map.
2. Enable instagib through a vote.
3. The only class you can play as is soldier.

**Server Info (please complete the following information):**
 DFS EU - London, UK: 89.35.29.11:27145

**Additional context**
Map: dm_bloodcov_b1a

https://steamcommunity.com/groups/Dispenz0rsFunServer/announcements/detail/1690470748529405145
"Fixed Randomizer and Instagib locking people to specific classes, you can now choose your class in these modes."

**Comment by Light08** [comment]
Incorrect, the changes were for Randomizer only. Instagib has not been modified in any way.
