### ISSUE TITLE
Invalid Furniture

### ISSUE THREAD

**Issue by Phal0** [DFS-Servers/BugReportsAndSuggestions#216]
**Steam Profile**
https://steamcommunity.com/profiles/76561198071184624/

**Describe the bug**
The new Strongbox crates that give you building materials for the new Sandbox gamemode sometimes give you "Invalid Furniture".

**Expected behavior**
You shouldn't be able to obtain unusable furniture.

**To Reproduce**
1. Go to any friendly map.
2. Navigate to the Builder Guild's Guild Store and buy "Furniture Strongbox Series 5".
3. Use "Furniture Strongbox Series 5" (the other Strongbox crates might also have this problem).
4. After unboxing enough crates you will eventually get "Invalid Furniture".

**Screenshots or error logs**
![invalidfurniture](https://user-images.githubusercontent.com/59568345/71825225-adabc100-309b-11ea-8b96-f5e939ea84c5.png)

**Server Info (please complete the following information):**
DFS EU - London, UK: 89.35.29.11:27145

**Additional context**
This also happened to me once earlier but I don't remember which crate it was.

**Comment by Light08** [comment]
Fixed. Strongboxes that havent distributed anything will be returned to the users.

Thank you for the report.
