### ISSUE TITLE
Can camp in hell on ig_hangar if rtd rollls dispenser or other things that gives lots of hp, invincibility etc...

### ISSUE THREAD

**Issue by miniz1994** [DFS-Servers/BugReportsAndSuggestions#217]
https://steamcommunity.com/id/miniz1994/

**Describe the bug**
As mentioned roll rtd and you + the rest of your teammates can camp in the hell part of this map if it happens too be a dispenser that is supposed too drain your hp and kill you

**Expected behavior**
uh that rtd is perhaps disabled on instagib maps.

**To Reproduce**
rtd a dispenser or massive hp or similar on instantgib_hangar & other maps that might have this teleporter thing going.

**Screenshots or error logs**
https://steamcommunity.com/sharedfiles/filedetails/?id=1961907044

**Server Info (please complete the following information):**
 Us server but probably applies too eu the same.

That is all

**Comment by Dispenz0r** [comment]
This should be fixed now, thanks for reporting!
