### ISSUE TITLE
Damaging the Tank in STT as a friendly

### ISSUE THREAD

**Issue by Mattamech** [DFS-Servers/BugReportsAndSuggestions#218]
**Damaging tank while friendly**
When Stop that Tank is enabled and you are assigned to Humans, you can use !friendly to avoid getting hurt from the robots but you can damage the tank.

**Expected behavior**
You do no damage to tank. (sm_removeweapons maybe?)

**To Reproduce**
1. Go to either a payload or stop that tank map
2. If payload enable stop that tank.
3. When assigned to humans become friendly.
4. Go attack the tank

 - Can occur on both servers.

**Comment by Dispenz0r** [comment]
This should be fixed now, thanks for reporting!
