### ISSUE TITLE
No collision on blocks during the beat box minigame during wario ware

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#220]
Steam Profile

https://steamcommunity.com/id/oopsmysystemcrashd/

Describe the bug

During the beatbox special minigame that can occur at the end of the round, players are tasked by navigating an obstacle course wherein blocks disappear and reappear to the beat of the background music. After passing the large 4x2 set of changing green and yellow blocks, if players attempt to jump on the green blocks when they're supposed to appear solid, players fall right through.

Expected behavior

Players should be able to stand on the blocks as it is required to progress

**Comment by Dispenz0r** [comment]
Fixed now, thanks for reporting!

**Comment by Light08** [comment]
or did you...
