### ISSUE TITLE
Suggestion: add the "Engineers vs. Medic zombies" (a.k.a. "Zombie Survival") gamemode

### ISSUE THREAD

**Issue by Pro100RedMushroom** [DFS-Servers/BugReportsAndSuggestions#222]
> **Describe your suggestion**
> A detailed description of your suggestion.

Add the "engineers vs. medics" gamemode as an alternative to the "super zombie fortress" gamemode.
The gamemode is about surviving (instead of escaping until a certain end) as engineers a wave of zombie medics.

> **Describe alternatives you've considered**
> Describe and discuss any suggestions or alternative solutions you've considered.

To my knowledge, there are currently no other zombie survival gamemodes that are still being updated.

> **Additional context**
> Add any other context or screenshots about the feature request here.

Right now noone likes the existing system of szf since its a bit exhausting and overwhelming (example: on most of the current maps the best that human team can do is to go through until about 50% of the map).
Szf mainly follows the "escape from the zombies" concept, which a big majority of players think should be either remade in some places or be reserved for a more fun alternative to the zombie survival genre because playing only it is a bit dull.

**Comment by Dispenz0r** [comment]
Can't seem to find a _stable_ plugin for said gamemode, I personally have no idea how said gamemode works so we can't really work on creating such gamemode ourselves.

SZF is a good gamemode, people might have different opinions on it but I doubt _everyone_ hates the gamemode itself.
