### ISSUE TITLE
Boss Michael Myers gets stuck on stairs in sl_containmentbreach_v2a

### ISSUE THREAD

**Issue by BimboBumboBambo** [DFS-Servers/BugReportsAndSuggestions#223]
**Steam Profile**
https://steamcommunity.com/id/BimboBumboBambo

**Describe the bug**
As it sounds, the boss gets stuck on the stairs on the map and is unable to move. This happens specifically on the stairs leading to SCP-106's control room.

**Expected behavior**
I hope this gets fixed, as it can abuse the boss's pattern and give people a super easy win.

**To Reproduce**
- Just go down the stairs and hope the boss spawns.

**Screenshots or error logs**
![Naamloos 3](https://user-images.githubusercontent.com/41446589/72682967-5e21b800-3ad3-11ea-8649-efac68b67bd3.png)

**Server Info (please complete the following information):**
EU (89.35.29.11:27145)

**Additional context**
It is unknown if it happens to other bosses.

**Comment by Dispenz0r** [comment]
Should be fixed now
