### ISSUE TITLE
Bug on dr_backrooms v3

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#224]
Steam Profile:

https://steamcommunity.com/id/oopsmysystemcrashd/

Describe the bug:

As soon as the round starts, two things can happen:

Either players are teleported to the place where the map is supposed to start, or rise through the ceiling to where the map is supposed to start. In both situations, players become stuck. In the former scenario, players become stuck out of bounds and are unable to move, requiring an admin to teleport them inside the map, or otherwise suicide. In the latter scenario, there's a random chance that players will succesfully be elevated to the start of the map, however the majority of people become stuck in the floor and have their health drained and die.

Expected behavior:

Players are placed at the beginning of the deathrun course once the round starts.

To Reproduce:

Just start a round on the map.

Server Info (please complete the following information):
EU (89.35.29.11:27145) map: dr_backrooms_v3

**Comment by Dispenz0r** [comment]
Map will be removed to be replaced with another deathrun map, thanks for reporting.
