### ISSUE TITLE
[Sort of a bug] "[SM] You are flooding the server!" during typing minigame on wario ware

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#226]
Steam Profile: 

https://steamcommunity.com/id/oopsmysystemcrashd/

Describe the bug:

This isn't exactly a bug perse but its caught my attention as it caused me and presumably some others issues in the past

The whole point of the minigame is that you type the words on screen as fast as possible, yet you get punished for going fast. 

I would have a video showcasing this but nvideo game capture decided to just not work so I've only got screenshots instead

![image](https://user-images.githubusercontent.com/52565186/73611484-2a1dbb00-45da-11ea-985f-13bffd814b30.png)

![image](https://user-images.githubusercontent.com/52565186/73611489-3efa4e80-45da-11ea-848f-4a063c6e8ae3.png)

To Reproduce:

Get in the typing end of round minigame during warioware, type the words that show up on screen as fast as possible. Looking at the word that comes up next helps a lot with timing. Just keep typing the words correctly and if you're fast enough it should trigger the "You are flooding the server" message.

Server Info:

EU, [89.35.29.11:27145]

**Comment by Dispenz0r** [comment]
Already aware of this one and already prepared a fix for it which should come out sometime soon along with a server update.

**Comment by Dispenz0r** [comment]
Fixed, thanks for the bug report!
