### ISSUE TITLE
Server crash on round start on dr_marioparty_v04

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#227]
Steam Profile

https://steamcommunity.com/id/oopsmysystemcrashd/

Describe the bug

Seems to be semi-random but after one or two rounds on the map the server crashes. Appeared to happen yesterday after a player had gotten to the end and died, same happened today.

Expected behavior

Server doesn't crash.

To Reproduce

Not entirely sure of the trigger but my hunch is that it's either activating the last trap, or its random - a player died in the last trap yesterday and after the round ended, and a new one started, there was a crash. Happened today after a player made it to the end of the map after the final trap was activated. Might be a coincidence but checking the last trap may be worth a shot.

Screenshots or error logs

![image](https://user-images.githubusercontent.com/52565186/74182172-756b4580-4c3a-11ea-9eee-921f3b52385a.png)

![image](https://user-images.githubusercontent.com/52565186/74182205-874ce880-4c3a-11ea-8759-239faa9759ac.png)

**Comment by Dispenz0r** [comment]
Looks like this is something very likely map related, will see what I can do about it soon

**Comment by Dispenz0r** [comment]
Map has been replaced now, thanks for reporting.
