### ISSUE TITLE
Exit Portal from Noodle Boss Fight no work

### ISSUE THREAD

**Issue by Leafpad** [DFS-Servers/BugReportsAndSuggestions#228]
Yellow Dice and Snipeslayer3 had just finished a boss fight with mr. Purple noodle and were not stuck in the water, however, the exit portal was not working. They could approach it and touch it but it would not teleport them

**Comment by Dispenz0r** [comment]
Must have been an extremely rare occurance, I've tested it multiple times and haven't experienced this issue myself and therefore will be closing this issue for now.

**Comment by Light08** [comment]
There's an extremly rare instance in which certain triggers are not triggered inside the plugins. I have no clue why what's causing it, be it source engine, sourcemod or (very unlikely) my own plugins.
Scenarios like these can happen yes. Sadly not much I can do as long as I don't know the source of the issue.
