### ISSUE TITLE
Being able to choose custom weapons while in randomizer 

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#23]
The bug is that you can use /c in randomizer mode which i presume is not supposed to be able to happen
**To Reproduce**
1. Get a comp map to go randomizer
2. Type /c
3. Choose a weapon in /c

**Expected behavior**
Server to disallow the weapon change

 - Region: All

**Comment by Dispenz0r** [comment]
Shouldn't be a big problem to fix. We'll change it so Custom Weapons plugin is completely disabled when Randomizer is enabled, and vice versa.

Expect a fix pretty soon.

**Comment by Light08** [comment]
Fix will be applied in tomorrow's maintenance.
