### ISSUE TITLE
Counter strike gamemode breaks win conditions, times in others.

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#233]
Steam Profile

https://steamcommunity.com/id/oopsmysystemcrashd/

Describe the bug:

I know the gamemode isn't fully optimised for the servers just yet, its in development, but its better to make a report, just in case.  It causes win conditions to overlap with other gamemodes or something. After changing to a smash bros map, the following happened:

Round times were significantly shortened - to that of the counter strike gamemode's round times.
All rounds ended in stalemate regardless of one team having more kills/lives than the other.
Players at the start of round had uber's removed earlier than normal but were still locked in place, and could fire weapons.

To reproduce:

Start up the counter strike gamemode on any map, then switch to a map catered to a specific gamemode, ie smashbros or slender. Round times and round win conditions should still be counter strike win conditions.

**Comment by Dispenz0r** [comment]
I'll be closing this as the gamemode event was meant to be completely experimental
