### ISSUE TITLE
Pumpking spawning on maps without control points

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#235]
Steam Profile

https://steamcommunity.com/id/oopsmysystemcrashd/

Describe the bug:

Noticed this on a couple maps, though I forget the names of them, however I can report that he spawns on dm_boostertower, by blue spawn, where there is no visible or capturable spawn point.

To reproduce:

Spawn pumpking on booster tower, he spawn by the blue spawn, despite there being no control point there.

Expected behaviour: 

Boss either spawns towards the middle of the map, or not at all due to the lack of a proper control point.

Screenshots:

![image](https://user-images.githubusercontent.com/52565186/75571975-2ef75280-5a52-11ea-9c8e-e7c0648aa36e.png)

Map:

dm_boostertower_v2

**Comment by Dispenz0r** [comment]
Fixed, thanks for reporting.
