### ISSUE TITLE
Playtime on tfdb_lithium (and possibly dodgeball as a whole) not counting towards custom gamemodes playtime quest.

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#236]
Steam Profile

https://steamcommunity.com/id/oopsmysystemcrashd/

Describe the bug:

Noticed this on tfdb_lithium though I'm just reporting now without trying on other dodgeball maps - it might be tied to the gamemode as a whole but I'm not certain. Basically time played doesn't seem to count towards the quest on the map.

To reproduce:

Start up tfdb_lithium.
Start a custom gamemodes quest.
Wait several minutes.
Check quest progress.
Quest progress should still be at 0%.

![image](https://user-images.githubusercontent.com/52565186/79151162-e4dbed80-7dc1-11ea-95e9-cf4aea23d746.png)

**Comment by Light08** [comment]
Issue related to the prefix "tfdb", since only "db" is registered as a custom gamemode.
Will be fixed with the next update. Thanks for the report.
