### ISSUE TITLE
Suggestion: Add the zombie survival (maybe zombie escape too) gamemode(s) and the class wars plugin.

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#237]
Seen a lot of people saying they'd like zombie survival added in. Some have said they'd like it to replace sfz in its entirety, and I would like that too but I don't see that as a good idea. Instead I'm going to offer a suggestion to add the gamemode as its own seperate thing:

https://wiki.teamfortress.com/wiki/Zombie_Survival

It isn't to be confused with zombie fortress or zombie escape - its an entirely different thing.

Zombie escape: https://wiki.teamfortress.com/wiki/Zombie_Escape (I don't see much going on regarding this gamemode plus having three seperate zombie gamemodes would probably confuse people so this is just a little bonus in case it could get considered)

And class wars: https://wiki.teamfortress.com/wiki/Class_Warfare

As class wars is a plugin and not a proper gamemode it could be a toggable plugin that gets turned on based on a vote similar to randomizer or instagib

**Comment by Dispenz0r** [comment]
Will consider adding/testing these to the servers if I can find a working plugin for them in the future
