### ISSUE TITLE
Bug where randomiser gives no weapons.

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#238]
Steam Profile

https://steamcommunity.com/id/oopsmysystemcrashd/

Describe the bug:

Have no idea what caused this but randomiser doesn't seem to work at the moment. No weapons are given to players, not even equipped ones. Everyone just turns into an a-pose.

To replicate:

This happened on dm_towerleap, so it might be just that map, or this is a 1/10000 chance that this happened. Either way, set up towerleap and vote randomiser and have it go through. Everyone should be in an a-pose like the image below.

![image](https://user-images.githubusercontent.com/52565186/79643577-89cc4100-819b-11ea-9358-2a150aa3e4b2.png)

**Comment by Dispenz0r** [comment]
Just saw the issue and fixed it right away, thanks for reporting!
