### ISSUE TITLE
[Sorta bug?] Crushing walls at the end of the "escape the factory" boss minigame in warioware.

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#239]
Steam Profile

https://steamcommunity.com/id/oopsmysystemcrashd/

Describe the bug:

Reason I say sorta bug is because I feel this is more a quirk of the source engine than the actual minigame, or this could be intentional, making this less of a bug report and more of a suggestion but I can't be sure, but its been bugging a lot of people, so this could also act as a sorta suggestion to remove the final crushing walls at the end of the minigame as its a significant difficulty spike compared to everything before it.

Basically what happens is the walls kill people hugging them (or seemingly only near them and not actually touching them) when they retract. I'm talking about the fast crushing walls that act as the second to last obstacle in the minigame, and considering their fast speed it would make sense to hug them in order to pass as soon as the opportunity arises. Instead it kills players who do this, and it almost guarantees all players are killed upon reaching it, often resulting in no one winning the minigame, even when people stay away from the walls and attempt to pass normally.

Expected behaviour:

Players should be able to hug the wall of the crusher and pass through un harmed when it reopens. (Or as a suggestion, either slow down the crusher significantly or remove it entirely). Considering the previous, much slower ceiling crusher does not kill players who hug it while it retracts, and is much easier to get past anyway.

**Comment by Dispenz0r** [comment]
Redirecting you to https://github.com/gemidyne/microtf2/issues
