### ISSUE TITLE
Item Issue | Rainbow Lantern doesn't work in gamemodes

### ISSUE THREAD

**Issue by Grandpa-niko** [DFS-Servers/BugReportsAndSuggestions#24]
**Steam Profile**
https://steamcommunity.com/id/nikoiro680

**Describe the bug**
If the player gets the epic module "Rainbow colorful Lantern", the player will unlock an extra option called "Colorful rainbow" when using the item Luminous Lantern
**but**, Sometimes when The player does it, instead of the colorful rainbow effect, it leaves us with a static red color lantern

Now before explaining how to reproduce this, I have tried with different gamemodes if this happens
So far in comp gamemodes (surf, normal comp maps) & deathrun would have these problems in the first place
I need to try for other gamemodes to see if this happens in all gamemodes but friendly maps

> Friendly maps works normally in the first try, but if you remove the effect via "/profile > options > item settings > remove luminous lantern effect" then using the item again would cause the problem aswell.

other players can also see the problem if they look at the player with "supposed" effect

**To Reproduce**
Remember, We need the epic module "colorful Rainbow lantern" to reproduce this
1. Try to join to a server with a competitive/friendly map( if the map is friendly, please try the method told in the text marked as quote)
2. Buy or have already a Luminous lantern
3. Use it and select the color "colorful rainbow"
4. wait for results with /tp

**Expected behavior**
when this problem persisted,I tried to respawn (suicide), wait for next round,reconnect the server,change server, and even restart the game but the problem still persist (no changes)

**Screenshots or error logs**
These screenshots are taken in US VA
1° set : Dr_valve_hq
![20180825214538_1](https://user-images.githubusercontent.com/42687863/44624182-22be9200-a8bd-11e8-88e9-d4c7a208dfa6.jpg)
![20180825214539_1](https://user-images.githubusercontent.com/42687863/44624186-26521900-a8bd-11e8-823d-19cb739f11c7.jpg)
![20180825214541_1](https://user-images.githubusercontent.com/42687863/44624189-28b47300-a8bd-11e8-941d-5e37ae8e804f.jpg)
![20180825214545_1](https://user-images.githubusercontent.com/42687863/44624191-2b16cd00-a8bd-11e8-82b9-c56b087d079d.jpg)
![20180825214547_1](https://user-images.githubusercontent.com/42687863/44624193-2f42ea80-a8bd-11e8-9540-8e00b0d5cc3d.jpg)

2° set: Tm_stadium (after removing effect by the steps from quote)
![20180825224853_1](https://user-images.githubusercontent.com/42687863/44624195-3cf87000-a8bd-11e8-9020-87e5763ff656.jpg)
![20180825224855_1](https://user-images.githubusercontent.com/42687863/44624196-3e299d00-a8bd-11e8-82c2-85dcf32a576a.jpg)
![20180825224857_1](https://user-images.githubusercontent.com/42687863/44624197-3f5aca00-a8bd-11e8-8bee-09ac839552e5.jpg)

**Server Info:**
 - Region: tested in [US VA] & [EU UK] servers
 

**Additional context**
If you need someone with this module to reproduce, Feel free to add me in steam and ask, I will try my best to answer and test for this issue

**Comment by Light08** [comment]
I applied some changes to the code. Hopefully its going to work once the next maintenance is out.

Once the maintenance is out, please let us know if the issue still persists or is fixed.

**Comment by Light08** [comment]
Fixed.

Made also a big discovery while hunting down the issue for an entire hour. Guess there's always new stuff to learn...

**Comment by Dispenz0r** [comment]
Given you a Community box now, thanks for reporting!
