### ISSUE TITLE
Pumpking spawn underneath the map on dm_flux_b4

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#240]
Steam Profile

https://steamcommunity.com/id/oopsmysystemcrashd/

Describe the bug:

Might've reported this before, unsure though.

Pumpking spawns underneath the map, making it completely inaccessible and unkillable.

To replicate: 

Spawn pumpking on dm_flux_b4

![image](https://user-images.githubusercontent.com/52565186/79767014-aa71d380-8320-11ea-8959-7aac41cf8f8e.png)

**Comment by Light08** [comment]
The pumpking is set up to spawn on accessible navmeshes. I wonder if this is a plugin or map issue tho.

**Comment by Dispenz0r** [comment]
Since I've not heard of this issue re-occurring since the recent map updates I'll be closing this, feel free to post a comment here if it happens ever again.
