### ISSUE TITLE
Listing auction items for 0 credits 

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#241]
Unsure if this is intended or not, but I'm reporting anyway.

Steam Profile

https://steamcommunity.com/id/supermareoinrealloife/

Describe the bug:

The auction lets you put up things for 0 credits. Reason I think this isn't intentional is because of the fact that you can trade or gift things away for free, and the fact that a request to bring back the gift credits command has been rejected recently.

To reproduce: 

Put up any item on the auction for 0 credits.

Expected behavior(?):

Users should not be able to list items for 0 credits.

![image](https://user-images.githubusercontent.com/52565186/79778163-3b03e000-8330-11ea-9fe9-6121f369dac1.png)

**Comment by Light08** [comment]
![Fixes](https://user-images.githubusercontent.com/11878289/79778640-5cb59500-8339-11ea-9b39-4b59e30d442d.png)

**Comment by Dispenz0r** [comment]
Re-opening this issue because the said build is already up on the servers @Light08

**Comment by Light08** [comment]
Yea and its been fixed 2 weeks ago. This auction is from 2 weeks ago. (Deadlines are always 2 weeks after being put up.)

I closed this for good reason.
