### ISSUE TITLE
WarioWare Freecam [B]roke

### ISSUE THREAD

**Issue by cxx2845** [DFS-Servers/BugReportsAndSuggestions#242]
**Describe the bug**
No idea why, but freecam spec (fly around without being tied to a player) is broken, with it instead dropping you to the floor from wherever the camera was, leaving you unable to move.

**Expected behavior**
For you to be able to move around like on any other map

**To Reproduce**
1. Go to the spectator team, preferably with another player selected.
2. Press [jump key] until you're in freecam.
3. Have fun falling to the ground and getting stuck there!

**Screenshots or error logs**
If applicable, add screenshots or error logs to help explain your problem.

**Server Info:**
 - Region & IP:
EU, 89.35.29.11:27145

**Additional context**
N/A

**Comment by Light08** [comment]
I think that's been a thing since always. And if anything it would have to be "reported" to the creator of the gamemode, if that isn't intentional.

**Comment by Dispenz0r** [comment]
Redirecting you to https://github.com/gemidyne/microtf2/issues
