### ISSUE TITLE
Item cooldown not working properly

### ISSUE THREAD

**Issue by RealStrade** [DFS-Servers/BugReportsAndSuggestions#243]
**Steam Profile**

https://steamcommunity.com/id/gabranth125/

**Describe the bug**

Any item can be used multiples times without delay.

**Expected behavior**

There is supposed to be a cooldown before using any item again.

**To Reproduce**

- Type /pack
- Select any item
- Hit the key bound to "slot1" (by default, uses the item)
- Repeat

**Screenshots or error logs**

![hl2_Cws2XFosDG](https://user-images.githubusercontent.com/42638723/79921505-8c949380-8432-11ea-9251-d9ea3603f47f.png)

![hl2_m6QWLqSteu](https://user-images.githubusercontent.com/42638723/79921526-9e763680-8432-11ea-8de8-d08597e94e6b.png)

**Server Info**

Happened on EU : 89.3529.11:27145

**Comment by Dispenz0r** [comment]
Late but this was a part of the slight plugin hiccup at that time, this has already been fixed since then, thanks for reporting.
