### ISSUE TITLE
Slender mode not working properly and other shenanigans

### ISSUE THREAD

**Issue by RealStrade** [DFS-Servers/BugReportsAndSuggestions#244]
**Steam Profile**

https://steamcommunity.com/id/gabranth125/

**Describe the bug**

- Noone spawns in Red.
- The round lasts indefinitely, until someone in Blu dies.
- Any next round shows the same behaviour.

**Expected behavior**

At the beginning of each round, players should be put in Red team.

**To Reproduce**

- Go to any DFS slender map.

**Server Info**
 
 EU : 89.35.29.11:27145

**Additional context**

Multiple things stopped working at once, including but not limited to : 

- Item cooldown (cf. last issue),
- Several sourcemods commands (probably every last one of them),
- Friendly mode,
- Replicating item drops.

**Comment by Dispenz0r** [comment]
A really extremely weird/rare bug, should be fixed now.
