### ISSUE TITLE
"Mercenary Guild" Menu not working properly.

### ISSUE THREAD

**Issue by Nardor** [DFS-Servers/BugReportsAndSuggestions#245]
-**Steam Profile**
https://steamcommunity.com/profiles/76561198394404946

-**Describe the bug**
When I write the command /guild and press on "Quest List" the menu closes and gives no access to the current quests/challenges.

-**Expected behaviour**
When "Quest List" is pressed there should be the menu with the quests/challenges.

-**To reproduce**
Join EU/US Server, open the Mercenary Guild menu and press on "Quest List".

**Comment by Light08** [comment]
Just a tiny hiccup related to another issue which caused more than this. Expect it to be fixed soonish.
