### ISSUE TITLE
Changing weapons (in the loadout menu for tf2) while in spawn after grace ends swaps you to blu in sfz.

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#246]
Steam Profile

https://steamcommunity.com/id/supermareoinrealloife/

Describe the bug:

Changing weapons from your current class' loadout menu to something else will move you to blu team if done so after grace period has ended. Class changing is disabled after grace period as well, meaning the only intended ways to become a zombie are to manually join blu, killbind/suicide in the console, or die to zombies.

Expected behaviour: 

Players should not be moved to blu. I'm assuming what causes this is the fact that in normal tf2, changing your class' loadout in spawn will respawn you instantly. Since the game tries to respawn you, it thinks you're spawning in similarly to how you would from joining a team in spectator, and forces you onto blu.

Might be exclusive to certain maps, so in this instance it ocurred on expedition c2

**Comment by Dispenz0r** [comment]
ok, gonna force @FortyTwoFortyTwo to fix it soon 😄

**Comment by Dispenz0r** [comment]
[Has now been fixed](https://github.com/redsunservers/SuperZombieFortress/pull/68)
