### ISSUE TITLE
Make Pumpking reward players after its defeat.

### ISSUE THREAD

**Issue by synoptlcal** [DFS-Servers/BugReportsAndSuggestions#247]
**Is your suggestion related to a problem?**
After the campaign (assuming most players have already beaten "Pumpking Carnage"), Pumpking has no rewards for defeating them whatsoever.

**Describe your suggestion**
I suggest to add regular/rare rewards for every player that participated in fighting the Pumpking, it can be credits, items, or modules. As long as it makes the fight worth the effort.

**Describe alternatives you've considered**
In relation to another suggestion I had in mind, one method for selecting the rewarded players is everyone who's currently in the server. Or chosen players depending on how much damage they've dealt to Pumpking. It goes in a similar fashion of announcing the players that have "defeated" the Halloween bosses.

**Comment by Light08** [comment]
I'm thinking of giving it some unique rewards rather than default rewards, hence why the boss doesn't have any yet. But I'll have to think of something first. Expect a reward as late as... Halloween I'd guess.

**Comment by Dispenz0r** [comment]
Planned, thanks for the suggestion anyways.
