### ISSUE TITLE
Halloween meteor shower spell still able to damage and kill players on friendly maps.

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#248]
Steam Profile

https://steamcommunity.com/id/supermareoinrealloife/

Describe the bug:

Not sure how they're aquired, I dunno if its a donor command or something, but I've noticed that the meteor shower halloween spell is still able to damage and kill players, only through the afterburn effect it causes, however. 

![image](https://user-images.githubusercontent.com/52565186/80318084-8f5f0200-87ff-11ea-9ed9-cd5f5454e7a9.png)

**Comment by Light08** [comment]
I'm pretty sure the only way to obtain the spell itself is by making use of a dead skeleton king's drop. Even if we had a plugin to give out spells, it would be staff only. This scenario is only possible with maps that spawn skeleton kings (we barely have any), or staff that spawns them. After that it's their responsibility to not abuse it.
While griefing might be against the rules, this scenario would still be a rare one to occur. We have moderators to keep the server in check, in case someone abuses this on purpose.
Fixing an almost non-existing issue like this wouldn't be worth the effort, personally.
