### ISSUE TITLE
Leaderboard Name Swap Error

### ISSUE THREAD

**Issue by Frunken** [DFS-Servers/BugReportsAndSuggestions#25]
**Steam Profile**
https://steamcommunity.com/id/frunken/

**Describe the bug**
While using the leaderboard command, all listed postions held by Afterstormer are listed as Frunken instead.

**To Reproduce**
Describe the steps to reproduce the bug.
1. Type sm_leaderboard
2. Press 2 for Check Achivement Records
3. Press 1 for Achivement Progress

**Expected behavior**
You should see [90%] Frunken, even though I only have 65% progress and Afterstormer is the one who  has 90%.

**Screenshots or error logs**
https://steamuserimages-a.akamaihd.net/ugc/947333334942429214/2BC6304B3D13A323492B46506D68273E8A003C92/

**Server Info (please complete the following information):**
 - Region: EU
 - IP 89.35.29.11:27145

**Additional context**
Limeball and Leafpad have both confirmed that they also see this error.

**Comment by Light08** [comment]
Issue seems to be resolved? I can't re-produce this issue on the database.
