### ISSUE TITLE
Commands not working 

### ISSUE THREAD

**Issue by Nardor** [DFS-Servers/BugReportsAndSuggestions#251]
**Steam Profile**
https://steamcommunity.com/profiles/76561198394404946/

**Describe the bug**
Many commands (example: /commands, /mm, /nominate) don't work. When I type a Gold command it just says that I don't have access to it. I don't know if the same thing counts for VIP commands. Some commands like /guild, /pack, /shop seem to work fine.

**Expected behavior**
The commands should work as always.

**To Reproduce**
Go to EU server and try to type a command like the ones I told in the example.

**Server Info (please complete the following information):**
 DFS EU - London, UK: 89.35.29.11:27145

**Comment by Dispenz0r** [comment]
No idea why this happens at all, but it seems to happen rarely and randomly at least once a week or two. Sourcemod just randomly stops working completely, I tried contacting Asherkin regarding it so hopefully we should have a certain fix on this soon

Should be at least temporarily fixed for now.
