### ISSUE TITLE
Suggestion: Integrate stock/casual maps into the server in a controlled way

### ISSUE THREAD

**Issue by Pro100RedMushroom** [DFS-Servers/BugReportsAndSuggestions#253]
> **Describe your suggestion**
> A detailed description of your suggestion.

The suggestion is to add a system that allows players to play _some_ of the stock maps on the servers in a way that doesnt interfere with the servers' usual map rotation. 
As i see it, they should be in a seperate "group", where they can only be nominated once per 2-3 (or more) map rotations.

> **Describe alternatives you've considered**
> Describe and discuss any suggestions or alternative solutions you've considered.

Add stock maps that have aesthetic edits and/or gameplay modifications.

> **Additional context**
> Add any other context or screenshots about the feature request here.

I think it would be a good addition to the current map pool, since they were tested by time and are more known to players. A lot of times people try playing competitive-based maps that are new for them and then immediately forget about them either because of an annoying gimmick that made a bad impact on them or bad/confusing/complex map design. And in the end, everything just defaults to either flood, towerleap, jungle, aps_siberia, some other maps, which are more appealing.

**Comment by Dispenz0r** [comment]
This is going to be very very difficult to do with the upcoming system changes, would rather stick with custom maps for now but might consider it for the future.
