### ISSUE TITLE
vanessa missing texture

### ISSUE THREAD

**Issue by gobaoscar** [DFS-Servers/BugReportsAndSuggestions#254]
**Steam Profile**
https://steamcommunity.com/id/gobaoscar/

**Describe the bug**
in slender vanessa has no texture like if was no texture installed

**Expected behavior**
only see the red eyes he has

**To Reproduce**
Describe the steps to take to reproduce the bug.
[e.g.
1. I went to '...'
2. I clicked on '....'
3. Purchase did not '...'
4. No credits]

**Screenshots or error logs**
![20200512130144_2](https://user-images.githubusercontent.com/61912627/81677667-6ec6b700-9451-11ea-962c-c79a9d77650f.jpg)

**Server Info (please complete the following information):**
 - Region & IP: [EU ,89.35.29.11:27145]

**Additional context**

**Comment by ThatAverageJoe** [comment]
I've fixed this issue in v2 of the model, it should be up soon.
