### ISSUE TITLE
Affinity Particle still appears in first person

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#255]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
The Affinity Particle is still visible in first person, especially when moving down stairs, after the fix that should have changed this.

**Expected behavior**
The particle should not be visible in first person.

**To Reproduce**
1. Equip Affinity Particle
2. Look straight ahead

**Screenshots or error logs**
![hl2_M7n9MCKw0c](https://user-images.githubusercontent.com/42521633/81695033-f9abaf80-9459-11ea-8af8-557ec9d2aa0b.jpg)
![hl2_Bq7fb2ZmKf](https://user-images.githubusercontent.com/42521633/81695038-fa444600-9459-11ea-9dbc-80d07ef62132.jpg)

**Server Info (please complete the following information):**
EU, 89.35.29.11:27145

**Comment by Light08** [comment]
This module isn't affected by the changes. It will come a bit later due to the complexity of this module.
