### ISSUE TITLE
"Last man alive lock the door" does not record progress

### ISSUE THREAD

**Issue by Kray0la** [DFS-Servers/BugReportsAndSuggestions#256]
**Steam Profile**
https://steamcommunity.com/id/pikalenni95/

**Describe the bug**
The quest "Last man alive lock the door" from the newly added Campaign doesn't track properly. I was Soldier and the last survivor standing as the quest demands, and I have not seen any progress on the quest. Considering how hard it can be sometimes to be the last one standing, this is a real bummer. 
 
**Expected behavior**
It should have shown 50% progress.

**To Reproduce**
1. Be Soldier and the last one standing
2. Tracking should not take place

**Screenshots or error logs**
https://i.imgur.com/djtfzZp.png

**Server Info (please complete the following information):**
EU, 89.35.29.11:27145

**Comment by Light08** [comment]
Fixed now. Thanks for the report.
