### ISSUE TITLE
Changing the SZF quest for the soldier campaign

### ISSUE THREAD

**Issue by Blanni** [DFS-Servers/BugReportsAndSuggestions#257]
**Is your suggestion related to a problem?**
The current problem is that the SZF quest is taking too long to complete, being the last survivor in this gamemode is not only hard in itself, it locks the quest to only one person able to advance at a time (unlike Smash where the whole winning team gets to advance)

**Describe your suggestion**
I've suggested in the chat to change the condition to "Win a SZF round or be the last survivor as Soldier", I think this would allow the quest to be more fair, so a winning team of survivor can all get rewarded for managing to win with teamwork, espcially since teamwork is supposed to be the main way to win in SZF

**Comment by Light08** [comment]
nah
