### ISSUE TITLE
Corrupted/glitched audio on arctf_titans_a6_dfs

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#259]
Steam Profile

https://steamcommunity.com/id/supermareoinrealloife/

Describe the bug:

When the wario head and cat heads rise in the skybox as part of a timed event on the map, sound effects are supposed to play. Currently they are glitched and sound corrupted, leading to high pitched static noises.

Expected behavior:

Sound effects play without issues.

**Comment by Light08** [comment]
Delete all your sound.cache files.
