### ISSUE TITLE
Sort all forms of items in an alphabetical order.

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#261]
**Describe your suggestion**
Sorting all forms of items in an alphabetical order, consumables are already sorted in this way, modules, pets and furnitures aren't sorted in this way currently.

**Describe alternatives you've considered**
Changing all items to be sorted in an alphabetical order.

**Comment by Light08** [comment]
Might have been or might not have been planned for summer to some degree.

**Comment by Light08** [comment]
Falls under the same Item Managment Request as with Issue #203 
Might or might not happen in the future, but I'll keep it in mind once I find a good solution for this.
