### ISSUE TITLE
Disable Bhop and all-class Double Jump in Surf/Semi-Comp maps

### ISSUE THREAD

**Issue by synoptlcal** [DFS-Servers/BugReportsAndSuggestions#262]
**Is your suggestion related to a problem?**
Bhop and Double Jump allows you several ways to gain an advantage in both modes.
In surf, with bhopping you are able to gain more speed in spawn to give yourself a headstart in the start area (doesn't apply in a few maps). With double jump it can be used to reach the end of the map with insufficient speed.
In semi-comp, (mostly tm_stadium) bhopping serves as a run-away advantage in boss battles, giving you an easier time with dodging projectiles and enemies. Both plugins can be also utilized in PvP areas to gain an unfair advantage in movement, with right classes it becomes a much bigger benefit for the player.

**Describe your suggestion**
Ditto. 
Disable both plugins to give a fairer experience for both modes and cutting most advantages listed.

**Describe alternatives you've considered**
If possible, create a system that disables the plugins inside of covered zones. (Surf area, shadow realm, pvp arenas)

**Comment by Dispenz0r** [comment]
Could work out for tm_stadium and semi-comp maps which we might consider doing, but for surf maps it has conflicted views from people who still might want bhop enabled therefore we won't be considering it.
