### ISSUE TITLE
Map suggestion dump

### ISSUE THREAD

**Issue by synoptlcal** [DFS-Servers/BugReportsAndSuggestions#263]
One of these again, also gonna include some maps that were already suggested in the forums.

**SURF**

surf_akai (Can be found in this map pack: [click here](https://steamcommunity.com/sharedfiles/filedetails/?id=182746532))
surf_forbidden_ways (Can be found in this map pack: [click here](https://steamcommunity.com/sharedfiles/filedetails/?id=732688922&searchtext=surf+map+pack))
surf_overcast ([click here](https://gamebanana.com/maps/124767))
surf_overlook ([click here](https://tf2maps.net/threads/overlook.22016/))
surf_lament ([click here](https://steamcommunity.com/sharedfiles/filedetails/?id=649656353&searchtext=surf))
surf_horizon ([click here](https://gamebanana.com/maps/164697))
surf_nameless ([click here](https://gamebanana.com/maps/200500))
surf_twilight ([click here](https://gamebanana.com/maps/186372))
surf_blackout ([click here](https://gamebanana.com/maps/179853))
surf_greatfissure ([click here](https://gamebanana.com/maps/104065))

**VSH**

vsh_rockslide ([click here](https://gamebanana.com/maps/161292))
vsh_grid_walls_reworked ([click here](https://gamebanana.com/maps/209250))
vsh_portside ([click here](https://gamebanana.com/maps/206742))
vsh_egyptyspot ([click here](https://gamebanana.com/maps/188909))
vsh_snowglobe (Can be found in this map pack: [click here](https://steamcommunity.com/sharedfiles/filedetails/?id=2027769723))
vsh_aperture (Can be found in this map pack: [click here](https://steamcommunity.com/sharedfiles/filedetails/?id=2026720000))
vsh_minegay (Can be found in this map pack: [click here](https://steamcommunity.com/sharedfiles/filedetails/?id=2026720000))
vsh_volcanic (Can be found in this map pack: [click here](https://steamcommunity.com/sharedfiles/filedetails/?id=2026720000))
vsh_chamber_of_exigency (Can be found in this map pack: [click here](https://steamcommunity.com/sharedfiles/filedetails/?id=2026720000))
vsh_hl1_crossfire_bunker (Can be found in this map pack [click here](https://steamcommunity.com/sharedfiles/filedetails/?id=2030796513))
vsh_spaaaaace (Can be found in this map pack [click here](https://steamcommunity.com/sharedfiles/filedetails/?id=2030796513))
vsh_intrusion ([click here](https://steamcommunity.com/sharedfiles/filedetails/?id=2028022028&searchtext=))

**STANDARD GAMEMODES**

cp_snowpiercer ([click here](https://gamebanana.com/maps/209812))
cp_station ([click here](https://gamebanana.com/maps/196521))
Laserfight ([click here](https://tf2maps.net/downloads/laserfight.9216/))
koth_overgrowth [click here](https://steamcommunity.com/sharedfiles/filedetails/?id=2037517959&searchtext=)
ctf_eggwar ([click here](https://tf2maps.net/downloads/egg-war.607/))
cp_blackmesa ([click here](https://gamebanana.com/maps/94083))
cp_container ([click here](https://gamebanana.com/maps/180821))
ctf_bloodgulch ([click here](https://gamebanana.com/maps/168045)) DM VERSION: ([click here](https://gamebanana.com/maps/167879))
koth_aperture_science ([click here](https://gamebanana.com/maps/180520))
koth_spaaaace ([click here](https://gamebanana.com/maps/163004))
koth_persia ([click here](https://gamebanana.com/maps/127793))
The Hat Factory ([click here](https://steamcommunity.com/sharedfiles/filedetails/?id=642446800&searchtext=))
plr_vegas ([click here](https://gamebanana.com/maps/112212))

**DEATHRUN**

dr_castle_steveh ([click here](https://gamebanana.com/maps/180295))
dr_paradoxal ([click here](https://gamebanana.com/maps/207349))

**DODGEBALL**

tfdb_brokenglass ([click here](https://gamebanana.com/maps/165387))
tfdb_castle (Can be found in this map pack: [click here](https://gamebanana.com/maps/163145))
tfdb_virtual ([click here](https://gamebanana.com/maps/171969))

**Comment by Dispenz0r** [comment]
Good one, took a look at all if not most of them already, thanks.
