### ISSUE TITLE
move in setup time

### ISSUE THREAD

**Issue by gobaoscar** [DFS-Servers/BugReportsAndSuggestions#264]
**Steam Profile**
https://steamcommunity.com/id/gobaoscar/

**Describe the bug**
you can move free in setup time

**Expected behavior**
you cant move in setup time
**To Reproduce**
go to a any map

**Screenshots or error logs**
![20200607153159_1](https://user-images.githubusercontent.com/61912627/83970095-178ef780-a8d4-11ea-9f50-f7683434fbd6.jpg)
![20200607153201_1](https://user-images.githubusercontent.com/61912627/83970110-2aa1c780-a8d4-11ea-9a8c-bb299c2aac07.jpg)
![20200607153204_1](https://user-images.githubusercontent.com/61912627/83970116-35f4f300-a8d4-11ea-89fb-76f506518d37.jpg)

**Server Info (please complete the following information):**
 EU, 89.35.29.11:27145

**Additional context**

**Comment by Dispenz0r** [comment]
Fixed
