### ISSUE TITLE
New Deathrun map.

### ISSUE THREAD

**Issue by Coronarena** [DFS-Servers/BugReportsAndSuggestions#265]
Greetings, all.

Today I suggest to you a new deathrun map, that I think would go down well with the DFS community. **DR_STARDUST** is a deathrun map, with the theme of the anime _JoJo's Bizarre Adventures_, that has a few new interesting concepts for the deathrun gamemode. For example, one of these concepts is instead of having the reds choose which minigame they want at the end of the map, they're instead required to beat minigames placed throughout the map in order to progress. The map also features a colossal secret unlike anything ever seen in DR.

I'd love to post screenshots, but I'm on the wrong device to do so, so I'm afraid you'll have to do to the gamebanana page for that. Speaking of which, here's the link: https://gamebanana.com/maps/209846

Thank you for your time.

**Comment by windflow5** [comment]
No.

**Comment by GreenSwede** [comment]
We can take a look at it and see how it plays out, though we can't promise that we will add it. Thanks for the suggestion.

**Comment by GreenSwede** [comment]
After a quick examination the map file size is a little too big for us. The map's materials folder alone takes up a whopping **170 MB**. Are all of these different textures actually necessary or have they been included by mistake from your TF2 installation?

If you can reduce the file size so the map ends up being around 40 - 60 MB minimum then that would interest us a lot more to try it out.

**Comment by Coronarena** [comment]
Due to how big the map is, with its large amount of content, I'm afraid that to keep it with its current quality and all of its content intact, [that's next to impossible](
https://user-images.githubusercontent.com/24157059/85022593-6b6acd80-b16b-11ea-82fd-1053f8483782.png). The map size before any actual custom content is packed in is [around 80MB](https://user-images.githubusercontent.com/24157059/85022521-542be000-b16b-11ea-84fb-3c81d77d45ac.png) and so to get it 40 - 60 MB would require removing a lot of stuff, something that I am unfortunately not willing to do.

Either way, I thank you for at least checking out this thread. Enjoy the rest of your day :)
