### ISSUE TITLE
Ghostly Goose more ghost than goose

### ISSUE THREAD

**Issue by Leafpad** [DFS-Servers/BugReportsAndSuggestions#266]
https://i.imgur.com/qLObf5P.png 
https://i.imgur.com/TPcKGbL.png 

I can barely see this pet. Maybe we can increase the opacity on this pet to make them more visible?

**Comment by Macwithav** [comment]
Isolated the issue in the .VMT file and is now fixed; alpha mask edited accordingly to compensate for this fix.

**Comment by Dispenz0r** [comment]
Should be fixed with an upcoming update soon, thanks for reporting!
