### ISSUE TITLE
Enable team balancing and/or scrambling on af_tf2_party

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#267]
**Is your suggestion related to a problem?**
There seems to be no team balancing or scrambling (including by use of votescramble) on af_tf2_party, which can lead to games being very one-sided either by a major imbalance of team skill or numbers.

**Describe your suggestion**
Enable team balancing and/or scrambling.

**Describe alternatives you've considered**
Either team balancing or team scrambling would help prevent unbalanced matches.

**Comment by Dispenz0r** [comment]
This will be implemented with an upcoming update soon, thanks for reporting.
