### ISSUE TITLE
When I oath someone, the date of the Oath should be saved and shown to me

### ISSUE THREAD

**Issue by sascheh** [DFS-Servers/BugReportsAndSuggestions#268]
**Is your suggestion related to a problem?**
Something I felt was missing while working on the Summer Update and thought would make sense in general.

**Describe your suggestion**
Add a `DATETIME` columns to the table where the Oaths are stored in which the date and time of the oath is stored, that way you can display the date of the oath to the lovers.

**Describe alternatives you've considered**
None.

**Additional context**
You could also calculate anniversaries, which would make oaths more special.

**Comment by Light08** [comment]
Sounds good, I'll keep this in mind for later.
