### ISSUE TITLE
Issue | /donate command is no longer working

### ISSUE THREAD

**Issue by Grandpa-niko** [DFS-Servers/BugReportsAndSuggestions#27]
**Steam Profile**
https://steamcommunity.com/id/nikoiro680

**Describe the bug**
/donate command is not working (no response) ,very self explanatory
trying to type would not do anything ,no redirecting, no info (literally it's like if the command doesn't exist)
the problem goes that the command is listed in /commands, this would make confusion for players
trying to do only /command or "/command 5"

**To Reproduce**
1. type /donate or /donate |amount|
2. you will realize that it's not working

**Screenshots or error logs**
you can see that there is no interaction after you type this command
![20180826184616_1](https://user-images.githubusercontent.com/42687863/44633355-a9787b00-a960-11e8-860e-a7f45a10782c.jpg)
![20180826184626_1](https://user-images.githubusercontent.com/42687863/44633356-aa111180-a960-11e8-8609-318e9d41bb2a.jpg)
![20180826184630_1](https://user-images.githubusercontent.com/42687863/44633358-abdad500-a960-11e8-9750-d884e20bbfcb.jpg)

**Server Info:**
 - Region: [all servers]

**Comment by Light08** [comment]
Do you have html disabled?

**Comment by Grandpa-niko** [comment]
no ,actually I asked another players to do the same but it's not working

**Comment by Limeball** [comment]
Just tested it myself and I can confirm that the command does nothing.

**Comment by Dispenz0r** [comment]
The command has been removed since the last update, use http://dfs.tf/donate instead to donate.
