### ISSUE TITLE
Becoming civilian after successful randomizer vote

### ISSUE THREAD

**Issue by synoptlcal** [DFS-Servers/BugReportsAndSuggestions#270]
**Describe the bug**
After a successful randomizer vote, most if not all players turn into a civilian and have no weapons at all, the only way to respawn with random weapons is to be killed by someone (suicide didn't work previously).

**Expected behavior**
Everyone respawns back to their spawn with their randomized weapons received.

**To Reproduce**
1. Start a vote for Randomizer in any competitive map.
2. Vote for "Yes", and let the gameplay change.

**Comment by Dispenz0r** [comment]
Fix for this is on the way very soon, thanks for reporting.
