### ISSUE TITLE
Possible to enter enemy spawns on dm_flood while disguised as spy.

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#271]
Steam Profile

https://steamcommunity.com/id/supermareoinrealloife/

Describe the bug:

The spawn entrances on dm_flood don't block the enemy team from entering if the door is opened. This can allow spies to easily walk into enemy spawn and potentially spawn camp. (Welz helped me test this by killing me with Your eternal reward, having me open the spawn door for them and allowing them through and killing me a couple times to see if it really does work)

Expected behavior:

Players should either be killed upon touching the spawn entrance barrier in the image attached below or be unable to damage and therefore kill players if they get into enemy spawn.

![image](https://user-images.githubusercontent.com/52565186/89057785-26cf7600-d356-11ea-86b1-026603a19177.png)

To reproduce: Disguise either by killing a player with your eternal reward or disguising manually. Wait by the enemy team's spawn for the door to open and walk in while disguised. It should be possible to still damage people while in there.

![image](https://user-images.githubusercontent.com/52565186/89057687-fc7db880-d355-11ea-98b6-d74afce43a3f.png)

**Comment by Argo7200** [comment]
Damn. I've identified the issue and will work on an update in a little bit.

**Comment by Argo7200** [comment]
Heres rc3, which should fix the issue as well as add a few more tweaks 

https://mega.nz/file/NVRiAKDK#L0-Y9FyCRqOqBs-DiS7mfGmlbMOC3mnh1SuM5cqYIC4

**Comment by Dispenz0r** [comment]
Will update the map soon, thanks.
