### ISSUE TITLE
No-Touch protected props can't kill a player riding a kart

### ISSUE THREAD

**Issue by Ter157ian** [DFS-Servers/BugReportsAndSuggestions#272]
**Hello DFS team, I want to report a bug that appeared while I was playing DFS.**

While I was riding a kart via typing /kartme command in a trade map, I have accidentally touch/hit a No-Touch prop constructed by another player, suddenly it appeared that I didn't get auto-bindkill by the protected prop, instead it only brings me a message: "This prop is protected by No-Touch.". If a player continues pressing the key "W", it causes a spam of the same sentence creating a wall of text (The messages only appears to the player touching the prop).

_And also here is a photo showing this problem, sorry for such a messy and chaotic image!_

![20200821161320_1](https://user-images.githubusercontent.com/67838753/90902291-eacb8600-e3d4-11ea-8a6e-647a20adfb90.jpg)

I hope this might be helpful and I will look forward to report anything else if I see any errors on sight in the future.  Thank you and I will be waiting for a response anytime.

**Comment by Light08** [comment]
Fixed now.
