### ISSUE TITLE
Map voting system broken

### ISSUE THREAD

**Issue by Jamigum** [DFS-Servers/BugReportsAndSuggestions#273]
The map voting system that usually fires at ~7 mins left on a map no longer occurs and a random map is selected instead. 
/nextmap command always returns "Pending Vote". 
Nominating a map also doesn't fix the problem.

![bug](https://user-images.githubusercontent.com/70715730/92146601-de521f00-ee11-11ea-9c5b-e7f947b1ca10.jpg)
![bug2](https://user-images.githubusercontent.com/70715730/92146607-df834c00-ee11-11ea-9ccd-4fb2a9d8b765.PNG)

**Comment by Jamigum** [comment]
Additional note: Rock the Vote no longer works either.

**Comment by Dispenz0r** [comment]
Already fixed
