### ISSUE TITLE
[Bug] Deathrun gamemode broken.

### ISSUE THREAD

**Issue by Jamigum** [DFS-Servers/BugReportsAndSuggestions#274]
Might already be known, but I'll make a report anyway.

Deathrun maps have been broken, multiple players can be death and all weapons are allowed.

Teams are also no longer scambled at the end of every round.

Screenshots were taken from the map dr_home_sweet_home_v4

![bug4](https://user-images.githubusercontent.com/70715730/92624688-b35b4580-f2bf-11ea-98a3-b32cd9a619ab.jpg)
![bug3](https://user-images.githubusercontent.com/70715730/92624640-a8081a00-f2bf-11ea-937b-48099d3fc90e.jpg)

**Comment by Dispenz0r** [comment]
Already known, will be fixed sometime soon.
