### ISSUE TITLE
Allow us to choose our profile's color on dfs.tf

### ISSUE THREAD

**Issue by NeppuTennouboshi** [DFS-Servers/BugReportsAndSuggestions#276]
**Is your suggestion related to a problem?**
This is a suggestion I had when I first saw the new dfs.tf profiles, and seeing how my profile's bronze color didn't look good with my profile background and avatar.

**Describe your suggestion**
I think we should have an option on the new dfs.tf website that allows us to choose which profile color we want. 
Right now if you are a Bronze member, your profile will be bronze, if you're gold, your profile will be gold. However sometimes the color of the profile and the color of the user's background doesn't work together and it can be visually unpleasant to users who care about this sort of thing, which is why I suggest that we're allowed to go back to previous rank colors if they fit better, considering default & silver are fairly neutral. The rank would still be displayed above the user's name with the appropriate color.
For example, If I am a regular member, I'd only get access to the default color. If I'm bronze, I should get access to bronze and the default color, with a silver rank i'd have access to silver, bronze, and default, and so on. 
This is a minor thing but I think it would help players who like customization and it could definitely make some profiles much nicer to look at.

**Describe alternatives you've considered**
An alternative that came to mind is letting the user customize the color themselves but that would probably be more trouble than what it's worth. I feel like having at least the default color as an option would be very good for a lot of profiles.

**Comment by sascheh** [comment]
This feature is ready to be rolled out in a major website update coming this month.

**Comment by sascheh** [comment]
https://dfs.tf/settings/profile
