### ISSUE TITLE
Some weapon are highly inaccurate.

### ISSUE THREAD

**Issue by Treetalk1** [DFS-Servers/BugReportsAndSuggestions#277]
**Steam Profile**
https://steamcommunity.com/id/Treetalk_/

**Describe the bug**
Flare Guns, Bows, Crossbows, Rescue Ranger, Direct Hit, Liberty Launcher have enormous inaccuracy.

**Expected behavior**
There is little to no inaccuracy with most of these weapons.

**To Reproduce**
1. Select any weapon mentioned above, Huntsman for example.
2. Fire the weapon, deviation is entirely random

**Screenshots or error logs**
https://www.youtube.com/watch?v=dEmHWbVHWyE

**Server Info (please complete the following information):**
 - Region & IP: [e.g. EU, 89.35.29.11:27145]

**Additional context**
This doesn't happen on regular servers.

**Comment by Dispenz0r** [comment]
Should be fixed now, thanks for reporting!
