### ISSUE TITLE
SF2 seems to still crash the server.

### ISSUE THREAD

**Issue by TheRealNexion** [DFS-Servers/BugReportsAndSuggestions#28]
Was on USA | VA, map was slender_containmentbreach, roughly 15-20 minutes after me joining, server crashed. Seems that baldis_education wasn't the only map that crashed, apparently the gamemode itself is busted. Might need proper re-testing.

**Comment by Dispenz0r** [comment]
This issue is known for a while now, we don't exactly know what is causing it but we're trying our best to find out what and get it solved asap, bear with us for now.

**Comment by Dispenz0r** [comment]
Think this is fixed now, big thanks to Konkey for helping out

Closing this.
