### ISSUE TITLE
Pumpking's model appearing upside down

### ISSUE THREAD

**Issue by synoptlcal** [DFS-Servers/BugReportsAndSuggestions#281]
**Describe the bug**
Title.

**Expected behavior**
Model should be on its fixed rotation value while active.

**To Reproduce**
Passive after Pumpking randomly/manually spawns

**Screenshots or error logs**
![image](https://user-images.githubusercontent.com/60464705/96604222-86a63f00-12fd-11eb-8546-6d845354e9ed.png)

**Server Info (please complete the following information):**
 - Region & IP: EU - 89.35.29.11:27145

**Comment by Light08** [comment]
Already known issue with newest NPC system update.
We're investigating already.

**Comment by Light08** [comment]
Fixed.
