### ISSUE TITLE
Suggestion: Questboard HUD tracking

### ISSUE THREAD

**Issue by Darkita162** [DFS-Servers/BugReportsAndSuggestions#282]
If possible, I would like to have an option to have up to 1 to 3 guild quests be displayed somewhere on the DFS HUD, somewhat similar to the TF2 contracts. I'm not certain of the possibilities of this suggestion, so if having it display isn't possible, maybe have something appear in the chat. An exemple being: "20 out of 50 points earned for your healing quest" or something along that format.

**Comment by Light08** [comment]
Totally possible.
I might add it for the Christmas Update.
A little bit too late for Halloween, probably.

**Comment by gdfsgdfg** [comment]
I wish we could disable the hud instead.
