### ISSUE TITLE
Bug report: Holiday punch laugh on crit still effective in friendly mode

### ISSUE THREAD

**Issue by Darkita162** [DFS-Servers/BugReportsAndSuggestions#283]
**The problem:** The holiday punch still has it's "Force enemies to laugh upon attacks from behind or crits" effect still active within friendly mode on competitive maps. I haven't seen anyone use this to their advantage as it cant allow the user to taunt kill them in friendly mode, however it can be used as a way to cripple the enemy team into becoming vulnerable in their forced laughter state.

**Comment by Dispenz0r** [comment]
This should now be fixed with an upcoming patch, thanks for reporting!
