### ISSUE TITLE
No Progress on Military Strike Campaign Mission

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#285]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
Winning a round of Versus Saxton Hale and surviving as a member of RED Team does not progress the Military Strike mission.

**Expected behavior**
Mission progress should be granted

**To Reproduce**
1. Win a round of VSH as a member of RED Team
2. Check mission progress

**Server Info (please complete the following information):**
EU, 89.35.29.11:27145

**Comment by Light08** [comment]
Spotted the issue and fixed it. Should be live with 8.1.2 soon.
