### ISSUE TITLE
Change the sell price of Crow Pet

### ISSUE THREAD

**Issue by PixelatedPyro** [DFS-Servers/BugReportsAndSuggestions#288]
I recently saw that Crow pet is 9000 credits in the shop but when selling it you are being informed you will recive only 2500. You get half the credits from the Pet's price in the shop, Crow's past price was 5000. Is it possible to fix this and change the sell price to 4500 instead? Or just make the crow cost 5000 like it did in the past?
![Sell Price](https://user-images.githubusercontent.com/59366255/97777448-8bc28400-1b70-11eb-959b-a1caaf69d250.png)
![Buy Price](https://user-images.githubusercontent.com/59366255/97777451-8feea180-1b70-11eb-8eb7-46b523422c12.png)

**Comment by Dispenz0r** [comment]
Fixed this now, thanks for reporting.
