### ISSUE TITLE
Kill quests progressing the wrong quest with assists

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#289]
**Steam Profile**
https://steamcommunity.com/id/vilxxu/

**Describe the bug**
The bug is that when you get an assist kill from a for example a soldier, it will give progress to the offensive quest instead of whatever it's supposed to give progress to.

**Expected behavior**
The quests should giving progress to the class group that you are.

**To Reproduce**
1. Go medic for example.
2. Get an assist kill by healing someone for example a soldier
3. This should progress the support quest but it instead progresses the offensive quest

**Server Info**
 - Region & IP: [EU, 89.35.29.11:27145]

**Comment by Light08** [comment]
Fixed now.
