### ISSUE TITLE
Double Pumpkin Kills

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#291]
**Describe the Bug:**
In the quest KaPump!, killing someone with a pumpkin bomb awards 2 points instead of 1.

**Expected Behaviour:**
Pumpkin bomb kills should only reward one (1) point.

**To Reproduce:**
1. Someone stands next to a pumpkin
2. Shoot the pumpkin to blow them up
3. Check your progress and it should increase by 2 points

**Server Info:**
 - Region & IP: EU: 89.35.29.11:27145

**Additional Context:**
I don't know if this is intentional or not but I'm gonna report it anyway because I'm a good boy. Jami's being a bitch and wanted to be credited for assistance so I'm putting him here.

**Comment by Light08** [comment]
Does it, by chance, actually give assist kill or something?

**Comment by Afterstormer** [comment]
I never thought of that so I'm not sure. I'm welcome to test it if you'd like.

**Comment by Light08** [comment]
Checked the code and found an issue related to pre-rework questing system. Should be fixed with the next patch.
Thanks for reporting. Should the issue still persist, feel free to recreate the issue.
