### ISSUE TITLE
Server Suggestion (only an update to 1 map)

### ISSUE THREAD

**Issue by Coronarena** [DFS-Servers/BugReportsAndSuggestions#295]
(I tried using issue template properly this time)
My suggestion isn't related to a _problem_ as such, as it's more just a recommendation to update a map that I've noticed is on DFS.

I can't get much more descriptive than what's said on the GB page for the map which can be found here: https://gamebanana.com/maps/209846

I guess the alternative is to just stick with v1a of the map? I wouldn't suggest that since v1b is much nicer to play, especially in the key area of the map.

There's not much else I can add in terms of context since everything you need is on the Game Banana page.

Thanks for your time!

**Comment by Dispenz0r** [comment]
We'll be updating this map pretty soon, thanks for letting us know!
