### ISSUE TITLE
dfs.tf/profile displaying incorrect Level/Rank information

### ISSUE THREAD

**Issue by Welzhum** [DFS-Servers/BugReportsAndSuggestions#296]
**Describe the bug**
The required EXP/GEP needed to progress doesn't align with the amount the TF2 server demands. It is also noteworthy that the profile section does not correctly display your GEP amount.

**Expected behavior**
The website fetches the player's amount of EXP and GEP correctly.

**To Reproduce**
1. Go to a DFS profile in the website
2. Hover over the Level and Rank stats to see your EXP and GEP respectively
3. Compare the two stats with the ones provided by the TF2 server

**Screenshots**
![hl2_hwbOAXz6Wr](https://user-images.githubusercontent.com/43702452/106784924-28ebf780-664d-11eb-82b5-4fb20faba2f4.png)
![firefox_DAKmspyDgh](https://user-images.githubusercontent.com/43702452/106784931-2be6e800-664d-11eb-98cd-89d2e46765ad.png)
![firefox_fTW68mitDe](https://user-images.githubusercontent.com/43702452/106784944-2d181500-664d-11eb-930b-dc6e464078b2.png)

**Desktop:**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [85.0]

**Comment by sascheh** [comment]
Hey, thanks for the report. The formula used on the website are the same as supplied by Light, so I am curious myself as well where the issue could be.

**Comment by Light08** [comment]
The formulars are correct, but they weren't properly implemented. They'll be fixed once the website gets another update.

Thanks for reporting.

**Comment by sascheh** [comment]
Should be fixed for v1.1.2, if not, make a new report and I will look at it in a more timed fashion along with asking for exact values per level so this can be properly investigated.
