### ISSUE TITLE
/gimme causing game to crash when giving a weapon to myself 

### ISSUE THREAD

**Issue by FrozenOcelot** [DFS-Servers/BugReportsAndSuggestions#3]
I've been trying to give myself a melee weapon like the golden pan or saxxy but every time I do my game crashes. However when giving random players weapons now and then it does not crash for them.

**Comment by Dispenz0r** [comment]
Does it only happen with those specific weapons or with all weapons? Will need further information to investigate further.

**Comment by FrozenOcelot** [comment]
I have tried using other weapons just recently e.g. the prinny machete as another example and I get the same result. My game completely crashes and I have to start it up again. Seems this only happens to giving yourself a weapon and not when giving other people weapons.

**Comment by Light08** [comment]
It's RNG to be honest. I tend to either crash or not crash from giving out weapons (to myself).
It's a big mystery...

**Comment by Light08** [comment]
Has always been...

**Comment by Dispenz0r** [comment]
We'll be investigating this real soon.

**Comment by Dispenz0r** [comment]
Seems to be happening to specific people only, I literally have zero ideas why.

I'd say avoid using the command until we can figure something out and fix it, other than that there is nothing we can really do about it right now.

Although we did notice that it seems to be happening on specific weapons only, just try to be careful on which weapons you give yourself and you should be fine as well.
