### ISSUE TITLE
SF2 crash, again.

### ISSUE THREAD

**Issue by TheRealNexion** [DFS-Servers/BugReportsAndSuggestions#30]
Testing slender_containmentbreach, server crashed yet again after 20-30 minutes of gameplay.

Happened over at USA | VA.

**Comment by Dispenz0r** [comment]
>:(

**Comment by Dispenz0r** [comment]
We updated the gamemode files again a bit, let us know if it happens again please.

**Comment by Dispenz0r** [comment]
Upon doing further changes (disabling certain plugins on SF2 maps), the issue seems to have completely stopped on all of the servers so I guess we can assume it's safe now?

If you spot anymore crashes, do post here whenever you can, otherwise I'll be closing this issue in a few days or so.

**Comment by Dispenz0r** [comment]
Should be fixed now.
