### ISSUE TITLE
Similar potential bug as #300, but it's manor1

### ISSUE THREAD

**Issue by Toykyle** [DFS-Servers/BugReportsAndSuggestions#301]
**Steam Profile**
https://steamcommunity.com/id/NotThisTypeOfUser/

**Describe the bug**
It is a similar bug as #300, but it affects stealth-based bosses as well (like Squidward and Chris-Chan).

**Expected behavior**
Similarly to #300, I expected the boss to jump on and kill me.

**To Reproduce**
1. I went the left side of the Manor from its spawn (RED Team).
2. I went to a large well-lighted room with boxes and three possible Potion locations.
3. I jumped up to the thing next to the door at the edge of the corner.
4. I got the boss's attention through either toggling the flashlight, taunting (Kazotsky Kick, Conga, or Mannrobics), or triggering any voice responses.

**Screenshots or error logs**
This time, not one, but several screenshots, few of which are included here.
![image](https://user-images.githubusercontent.com/67622169/109060448-6de6d500-76b3-11eb-94cc-c1bac2e42d04.png)
![image](https://user-images.githubusercontent.com/67622169/109060504-77703d00-76b3-11eb-80eb-4435f1161115.png)
![image](https://user-images.githubusercontent.com/67622169/109060525-7d661e00-76b3-11eb-9efa-1c4945268e39.png)

**Server Info (please complete the following information):**
[EU] [89.35.29.11:27145]

**Additional context**
Not much else that I'm aware. The only exception would be Shaolin Rat King, due to being part Running Boss and part Stealth Slender (at least if you look at it for too long). From what I heard, a bug similar to this was apparently mentioned for the same map. Maybe it's this one?

**Comment by NotNihilanth** [comment]
This spot is blocked off now, thanks for reporting
