### ISSUE TITLE
Friendly Bonus Objective possibly bugged

### ISSUE THREAD

**Issue by Toykyle** [DFS-Servers/BugReportsAndSuggestions#302]
**Steam Profile**
https://steamcommunity.com/id/NotThisTypeOfUser/

**Describe the bug**
The "Spend time on a friendly / trade map" bonus objective did not apply like I thought it would. Whether it's the Tm_Stadium map doing that or maybe it being a US Server, I'm not sure. Maybe a combination of both?

**Expected behavior**
The "Spend time on a friendly / trade map" (every 2 minutes is an extra one progress) was supposed to apply and bring it to at least as close to 45 minutes. (There was no one else on the US server at the time of me coming in and timer ending the map)

**To Reproduce**
1. The map started at the usual 30 minutes.
2. I waited until the timer went out on the map.
3. I checked the "PlayTime Quest" progress with the bonus objective
4. I took a screenshot, almost immediately after the timer went off and the scoreboard appeared

**Screenshots or error logs**
There is just one.
![image](https://user-images.githubusercontent.com/67622169/109424631-590b8980-79b2-11eb-954e-e711fa61c7c7.png)

**Server Info (please complete the following information):**
[US] 198.24.171.83

**Additional context**
Not really, and I really doubt fighting a Shadow Realm boss had anything to do with it.

**Comment by Light08** [comment]
Stadium is treated as a custom gamemode map, not friendly.
