### ISSUE TITLE
Reduce server time for certain gamemodes.

### ISSUE THREAD

**Issue by synoptlcal** [DFS-Servers/BugReportsAndSuggestions#304]
**Is your suggestion related to a problem?**
Custom gamemodes rounds tend to last shorter or have less replayability value than regular competitive gamemodes. Some gamemodes can get either boring or repetitive if played at longer server times.

**Describe your suggestion**
Note that all values are made for reference and purely based on my experiences.
List of gamemodes to change time limits on:
**Deathrun:** 20 minutes.
**Dodgeball:** 15 minutes.
**Glass Attack:** 10-15 minutes.
**Surf:** 20 minutes.

**Describe alternatives you've considered**
It is possible to just set all custom gamemodes' time limit to 20 minutes, but some gamemodes (SZF as an example, but it heavily depends on the map) are more reliant on longer playtime.

**Comment by Dispenz0r** [comment]
I'll consider it for a future update, thanks for the suggestion.
