### ISSUE TITLE
(STADIUM) Shadow Realm's skybox (or others) can be seen via The house aquarium.

### ISSUE THREAD

**Issue by Ter157ian** [DFS-Servers/BugReportsAndSuggestions#305]
**Describe the bug**
Hello. After I have emerged victorious with another player then were sent inside this small apartment, I went around and jumped into the fish aquarium, then found out that you can see the map's sky itself through the aquarium, which means that I can see the other separated maps (and skyboxes) with the use of this error. The Shadow Realm's skybox is an example and first to be seen. In addition, When the other player went past my vision, they have shown nothing but their cosmetics and weapons. 

**Expected behavior**
Well um, see what's outside the aquarium such as the apartment itself rather than this error? (Plus see what's inside without the less noticeable map's sky.)

**To Reproduce**
For short:
1. Go to the apartment via winning any boss fights.
2. Go and then jump into the aquarium by jumping or climbing the ladder.
3. The error will be detected. (Go to the aquarium's corner for a better experience?)

**Screenshots or error logs**

![20210313152826_1](https://user-images.githubusercontent.com/67838753/111037648-c0532000-842d-11eb-89db-e5e1aeced3c6.jpg)
![20210313152836_1](https://user-images.githubusercontent.com/67838753/111037650-c0ebb680-842d-11eb-9326-a28e9d8797eb.jpg)
![20210313153010_1](https://user-images.githubusercontent.com/67838753/111037676-e37dcf80-842d-11eb-9f65-e1b58e41bdb9.jpg)

**Server Info (please complete the following information):**
 - Region & IP: [EU, 89.35.29.11:27145]
 
**Additional context**
If I am not wrong, this problem seems to appear from outside the aquarium but less noticeable. Looking at it appears the same picture I sent, the sky and the other skybox. 

I thank you for reading and will wait for any possible responses.

**Comment by Light08** [comment]
Known feature since day 1.
Might or might not "fix" it with later map builds, depending on player feedback.

**Comment by Ter157ian** [comment]
> Known feature since day 1.
> 
> Might or might not "fix" it with later map builds, depending on player feedback.

Understandable!
