### ISSUE TITLE
VSH Ranks and Queue points get reset each restart

### ISSUE THREAD

**Issue by synoptlcal** [DFS-Servers/BugReportsAndSuggestions#306]
**Steam Profile**
https://steamcommunity.com/id/synoptlc/

**Describe the bug**
Title.
_P.S:_ This also happens in Deathrun each map change, which now points at ClientPrefs storage being the issue.

**Expected behavior**
Ranks and queue points remain intact for all players after a restart.

**Server Info**
 - Region & IP: EU, 89.35.29.11:27145

**Comment by Dispenz0r** [comment]
Nothing is really wrong with our clientprefs file?? But I'll try to reset it sometime soon to see if that fixes it anyways, if it doesn't then it is not an issue on our end.
