### ISSUE TITLE
Reward EXP, Credits and various items for defeating DFS Bosses

### ISSUE THREAD

**Issue by synoptlcal** [DFS-Servers/BugReportsAndSuggestions#308]
**Is your suggestion related to a problem?**
Right now DFS Bosses (e.g: Snatcher, Birds, and especially Pumpking. See: https://github.com/DFS-Servers/BugReportsAndSuggestions/issues/24) have little to no incentive to be fought both for continuous runs (usually solo) and high playercount raids, rare outfit drops have less value/demand with the now declining economy and playerbase's opinions on them. Thus making fights with bosses seem more worthless and not worth the grind for rare skins.

**Describe your suggestion**
Add guaranteed rewards for beating DFS Bosses. The amount of EXP and Credits should scale depending on the level, plus guaranteed items with a chance of a boss exclusive item.

**Comment by Dispenz0r** [comment]
Already planned for the future.
