### ISSUE TITLE
Plugin Bug: Other users' tags get applied on wrong players

### ISSUE THREAD

**Issue by Pro100RedMushroom** [DFS-Servers/BugReportsAndSuggestions#309]
> **Steam Profile**
> A link to your Steam profile (optional).

> **Describe the bug**
> A detailed description of the bug.

Players that currently played between 18:10 and 18:30 EST had gotten other peoples' tags applied onto them. Colour from those tags didn't transfer and instead it was the team colour of the player.
After a rejoin the tag gets "rerolled". (I got "Paper" tag, it got rerolled into a "Protector" tag. Player APGE had "Scout Gaming", got rerolled into "Angery"). The players affected by this didn't have a tag beforehand. Welzhum, a player that did have a tag already, wasn't affected.
The map was trade_icerink_b2a, if that has any meaning here.
> **Expected behavior**
> What you expected to happen instead of the bug.

Tags shouldn't behave like that.
> **To Reproduce**
> Describe the steps to take to reproduce the bug.

Honestly, no idea.
> **Screenshots or error logs**
> If applicable, add screenshots or error logs to help explain your problem.

How it looked like (all players here got a random tag):
https://cdn.discordapp.com/attachments/584078601410969600/843975780438245386/unknown.png
After i rejoined:
https://cdn.discordapp.com/attachments/584078601410969600/843978899611582484/unknown.png
> **Server Info (please complete the following information):**
>  - Region & IP: [e.g. EU, 89.35.29.11:27145]

EU, 89.35.29.11:27145
> **Additional context**
> Add any other context about the problem here.

This is most likely an issue with the current revamped tag/chat colour system

**Comment by Pro100RedMushroom** [comment]
Addition:
The problem persists through map changes and apparently started to happen throughout the evening

**Comment by Light08** [comment]
Has been fixed on devbuild an hour ago, but I appreciate the report.
