### ISSUE TITLE
Smash Fortress timer functioning at double the speed

### ISSUE THREAD

**Issue by Welzhum** [DFS-Servers/BugReportsAndSuggestions#311]
**Steam Profile**
https://steamcommunity.com/id/Welzhum/

**Describe the bug**
The Smash Fortress round timer progresses at twice its intended speed, causing rounds to last half as long as they would. This has been happening during 8 player mode, and I can't verify if this will be the case under "normal rounds".

**Expected behavior**
The timer, and consequently each round should last the expected time. This does not affect, however, the round preparation time.

**To Reproduce**
Does not apply.

**Screenshots or error logs**

https://user-images.githubusercontent.com/43702452/119416073-217f5580-bcf3-11eb-8f6e-5cfa483ee7cf.mp4

**Server Info (please complete the following information):**
EU, 89.35.29.11:27145

**Comment by Kenzzer** [comment]
This should have hopefully been fixed, in yesterday's hotfix. Please report here again if the issue persists. Otherwise I'll close this issue, thanks!

**Comment by Kenzzer** [comment]
I've not noticed the issue on new installation. So I'll assume this is fixed. Please re-open if necessary.
