### ISSUE TITLE
Prophunt gamemode not working on ph_cchotel_b3 (potentially other maps as well)

### ISSUE THREAD

**Issue by BimboBumboBambo** [DFS-Servers/BugReportsAndSuggestions#313]
**Steam Profile**
https://steamcommunity.com/id/BimboBumboBambo/

**Describe the bug**
Prophunt as a whole has been forgotten as a gamemode on the DFS community, so it's unknown how long this bug has persisted.

The issue is that the BLU spawndoors(the props) won't open, at least on this map. It's unknown if it happens on other maps as well.

At the same time, none of the BLU team gets turned into props(or the Scout class as a whole) with every class practically being able to be picked. 

**Expected behavior**
I hope this bug gets fixed very quickly. Even if it's not played as much as it was before, there are some instances that a map of said gamemode is going to be picked. It would be a massive shame if it refuses to function, thus forcing an RTV.

**To Reproduce**
There is no way to reproduce this. This is a problem regarding the map/gamemode

**Screenshots or error logs**

![image](https://user-images.githubusercontent.com/41446589/119573670-e180a700-bdb4-11eb-87b9-9e90d7bfc372.png)

**Server Info (please complete the following information):**
 - EU (89.35.29.11:27145)

**Additional context**
As said earlier, it's not known if it's the map that causes the problem or the gamemode itself.

**Comment by Dispenz0r** [comment]
A small miss on our part, should be fixed now.  Thanks for reporting!
