### ISSUE TITLE
Vehicles clipping through typically inaccessible areas

### ISSUE THREAD

**Issue by Welzhum** [DFS-Servers/BugReportsAndSuggestions#314]
**Steam Profile**
https://steamcommunity.com/id/Welzhum/

**Describe the bug**
Players are normally unable to go through areas that prevent one team from passing or "invisible walls". By using vehicles, however, one can pass through these with ease, allowing the player to access normally spots on the map that they're more often than not supposed to be accessed.

**Expected behavior**
Much like how players cannot pass through these barriers, vehicles should be affected by this.

**To Reproduce**
1. Encounter any wall that a player cannot go through
2. Spawn a vehicle
3. Enter it and ride straight towards it

**Screenshots or error logs**

https://user-images.githubusercontent.com/43702452/119906486-9ac6b480-bf4e-11eb-9acf-8364da0a94ac.mp4

https://user-images.githubusercontent.com/43702452/119906655-eb3e1200-bf4e-11eb-91c1-f8ea3c68d08e.mp4

https://user-images.githubusercontent.com/43702452/119906686-f7c26a80-bf4e-11eb-86c9-1e80e06c3640.mp4

https://user-images.githubusercontent.com/43702452/119906708-014bd280-bf4f-11eb-873e-9cc2fc8f3c9d.mp4

**Server Info (please complete the following information):**
USA, 198.24.171.83:27185

**Additional context**
While accessing unintentional areas may be a lesser problem, being able to enter enemy spawns can prove concerning if the playerbase has their allowance settings to Competitive in a Friendly map.

**Comment by Mikusch** [comment]
Hi, thanks for the report.

Vehicles follow special collision rules and completely ignore player clips and respawn room visualizers. The latter can be fixed, the former is a bit tougher to do.
I'll forward some info to the other developers and work on a fix when I have the time.

**Comment by Mikusch** [comment]
I've updated the plugin, respawn rooms cannot be entered with vehicles anymore. Player clips will need to be fixed on a map-to-map basis as there's no easy way to do this in the plugin.
