### ISSUE TITLE
Slender Fortress 2 Bosses Invisible (MAJOR BUG)

### ISSUE THREAD

**Issue by BimboBumboBambo** [DFS-Servers/BugReportsAndSuggestions#316]
**Steam Profile**
https://steamcommunity.com/id/BimboBumboBambo/

**Describe the bug**
As stated in the title, Slender Fortress bosses don't appear visible to the player. You are still able to hear them, but regarding seeing the bosses it's a no go.

**Expected behavior**
I expect this bug to be fixed as soon as possible, since this renders Slender Fortress completely unplayeable.

**To Reproduce**
There is no way to reproduce this. This is a gamemode bug.

**Screenshots or error logs**

https://user-images.githubusercontent.com/41446589/121073843-59969600-c7d3-11eb-93e6-bcb53ce4d9ed.mp4

**Server Info (please complete the following information):**
 89.35.29.11:27145 [DFS EU]

**Additional context**
This didn't just happen against Jeff, but also against Rat King, Xavier, Jack Baker and Retrobelle. It's likely all Slender Bosses suffer from this.

**Comment by Dispenz0r** [comment]
I almost forgot about closing this issue, this should be resolved since the 9th year anniversary update or earlier, thanks for reporting.
