### ISSUE TITLE
Scottish Resistance unusable in SF2 PvP

### ISSUE THREAD

**Issue by DarkDragonian** [DFS-Servers/BugReportsAndSuggestions#32]
**Describe the bug**
The Scottish Resistance doesn't work properly in SF2's PvP area.

**Server Info:**
 - Region: EU | UK (although I'm pretty sure that it occurs on every server, just hasn't been tested yet)
 - IP 89.35.29.11:27145

**Additional context**
You're able to lay down sticky bombs with it but the "detonation" of the weapon does not any blast damage.
Instead the laid down stickys just break apart (which is the same effect as someone shot them down with hitreg weapons).
_Maybe some other weapons should be tested in the PvP area aswell._

**Comment by Dispenz0r** [comment]
Blame how the gamemode works with its friendly fire, nothing we can really do about it right now.
