### ISSUE TITLE
some plugins wont load

### ISSUE THREAD

**Issue by gobaoscar** [DFS-Servers/BugReportsAndSuggestions#320]
**Steam Profile**
A link to your Steam profile (optional).

**Describe the bug**
some of the plugins wont load propely (like hud,quest,etc)

**Expected behavior**
see the plugins loaded already
**To Reproduce**
Describe the steps to take to reproduce the bug.
-simply log in to the server

**Screenshots or error logs**
If applicable, add screenshots or error logs to help explain your problem.

**Server Info (please complete the following information):**
 - eu.dfs.tf:27015

**Additional context**

**Comment by Dispenz0r** [comment]
Should already be fixed, thanks for reporting.
