### ISSUE TITLE
Will all the plugins for the server.

### ISSUE THREAD

**Issue by gdfsgdfg** [DFS-Servers/BugReportsAndSuggestions#323]
Remain private or will some of them be posted here.

**Comment by Dispenz0r** [comment]
![squidward](https://github.com/DFS-Servers/BugReportsAndSuggestions/assets/39702422/322b8070-e1b2-49e8-9446-b3c6b3762b87)




No, y*llow dice, our code will never go open source. *You* out of all people won't get anything from us.
