### ISSUE TITLE
koth_gravelstone_event not teleporting to Hell on round end

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#33]
**Steam Profile**
https://steamcommunity.com/id/thatlimey/

**Describe the bug**
Players are not properly teleported to Hell at the end of a round on koth_gravelstone_event. Instead, the round is locked in overtime and players suffer FOV zoom until they die.

**To Reproduce**
1. Cap the central point on koth_gravelstone_event
2. Wait for the timer to reach 0

**Expected behavior**
The screen will turn white, but players will not be sent to Hell. You will experience a severe FOV zoom. Dying with this zoom will return you to normal.

**Server Info (please complete the following information):**
EU | UK - 89.35.29.11:27145

**Comment by Dispenz0r** [comment]
This report is kinda old but the issue should now be fixed.
