### ISSUE TITLE
Not gaining treasure finder achievement progress from arcade

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#37]
**Steam Profile**
https://steamcommunity.com/id/vilxxu/

**Describe the bug**
Not gaining achievement progress from arcade for treasure finder

**To Reproduce**
1. Spam arcade until you get a rare item 
2. No rare item finder achievement progress

**Server Info (please complete the following information):**
 - Region: [EU]
 - IP 89.35.29.11:27145

**Comment by Light08** [comment]
That's intended.
The achievement is supposed to be earned from drops mainly.

**Comment by windflow5** [comment]
I would recommend removing the Win rare items part then

**Comment by Light08** [comment]
Epic items still counts towards winning.
