### ISSUE TITLE
/c Custom weapons not saving

### ISSUE THREAD

**Issue by DrAzure** [DFS-Servers/BugReportsAndSuggestions#38]
**Describe the bug**
Custom weapons don't save over with respawns.

**To Reproduce**
Equip a custom weapon and respawn.

**Expected behavior**
To still have the weapon upon respawning.

**Screenshots or error logs**
https://imgur.com/a/PElSqzm
https://imgur.com/a/hbwqAtB

**Server Info**
- Region: USA / VA
- IP 198.24.171.83:27185

**Comment by Dispenz0r** [comment]
Does this happen everytime? On different servers and maps as well?

**Comment by DrAzure** [comment]
It has been happening everytime so far, happening on EU / UK aswell, tried on stadium and the various mariokart maps.

**Comment by DarkDragonian** [comment]
I can actually confirm that.
It happened to me aswell the last time when I've played as a Spy on cp_toy_fort on UK.
My Master Exploder (not sure if it's the right name; custom knife that damages both healer and healed target) didn't save after respawn, forcing me to re-equip it.

**Comment by Dispenz0r** [comment]
no idea, use the command to re-equip the weapon each time i guess


or feel free to contact the author of the plugin here https://forums.alliedmods.net/member.php?u=253065 as this is not our plugin
