### ISSUE TITLE
Pets' hunger is still going down after they are no longer out

### ISSUE THREAD

**Issue by Madproredmushroom** [DFS-Servers/BugReportsAndSuggestions#4]
**Describe the bug**
as the title suggest if you put away your pet the hunger meter still depletes.

**To Reproduce**
1. put away your pet
2. get that pet to be at some hunger % above 1
3. wait some time

**Expected behavior**
the hunger meter shouldnt deplete if the pet is put away. 

**Server Info (please complete the following information):**
 - Region: EU DE
 - IP 88.99.141.199:27155

**Additional context**
when i wanted to check the /pets menu i noticed that all of my pets were at 1% hunger (except my little dispenz0r pet which i maxed out at 100% yesterday but now is at 42%, even though i put him away after using the food items). i never used any of them, except little dispenz0r, and was mildly surprised that all of them were at 1%, even though i distinctively remember them all being at atleast 75%.

**Comment by Light08** [comment]
Will investigate. If this problem should still occur after the next maintenance, please let us know.

**Comment by Dispenz0r** [comment]
Should be fixed according to Light so I'll be closing this.
