### ISSUE TITLE
Change the way maps are picked

### ISSUE THREAD

**Issue by BrightBabyYoshi** [DFS-Servers/BugReportsAndSuggestions#42]
**Is your feature request related to a problem? Please describe.**

Yeah, DFS still have problems with "game-mode/map chaining" (Example being 2 to 3 DR maps chained together or overplayed maps being chained while other maps don't get played **at all**) that kinda turns people off from wanting to play other game-modes or relax on friendly maps instead of playing the same game-mode over and over.

**Describe your suggestion**

My suggestion would be to change single map picks to "Map packs", with map packs we would have better game-modes/map spread and could restrict overplayed game-modes/maps from being constantly picked thus keeping things "fresh".

**Describe alternatives you've considered**

No real alternatives i can think of.

**Additional context**

At the end of the map's time-limit, a prompt would appear with map packs to be picked from;

**1. Competitive pack
2. Friendly pack
3. Death-run pack
4. Slender pack
5. MicroTF2** (MicroTF2 doesn't have a pack since it's a single map game-mode)
**6. Prop-hunt pack**

You get the idea. When a game-mode is picked, it enter a cool-down where it gets unable to be picked again until said cool-down expires. Let's say after 2-3 map packs was played, its cool-down expires and the map pack that was on cool-down will be able to be selected again.

**Comment by Grandpa-niko** [comment]
it's not a bad idea
But let's also consider about players using /nominate
that is one of the reasons why the map chain happens, some players choose maps where its the same gamemode
Example:
The current vote happens to have 2 nominates which are tfdb maps, while by RNG maps we get 1-2 more tfdb maps, so people would either vote the most popular gamemode or just try to avoid them by selecting another even overplayed map that appeared in the vote

if This suggestion gets added, would /nominate make a huge change? or just be removed?

I still liked the idea by the way.

**Comment by BrightBabyYoshi** [comment]
/nominate would be removed of course, there won't be any usage of said command since all map packs would appear during map vote. The idea of having map packs will fix the RNG aspect of the current way we pick them, so no more having players nominating multiple maps of one game-mode and having more maps of the same/current game-mode appearing because of RNG like on your example.

**Comment by Dispenz0r** [comment]
I won't lie, this sounds hard & time consuming to set up as much as I like the suggestion.

Don't count on it too much for now, I may consider this in the future however.

**Comment by Dispenz0r** [comment]
I'll consider this in the future, for now our system seems to be good enough. Closing.
