### ISSUE TITLE
AR-Emitter is missing

### ISSUE THREAD

**Issue by DarkDragonian** [DFS-Servers/BugReportsAndSuggestions#43]
**Describe the bug**
By uncrating a Non-Organic Fossil Pod, I've gotten the notification that it contained an AR-Emitter.
But it cannot be seen inside the inventory.

**Screenshots or error logs**
![](https://i.imgur.com/ISImQZP.png)
![](https://i.imgur.com/0i11Re1.png)

**Server Info:**
 - Region: EU | UK
 - IP: 89.35.29.11:27145

**Comment by Light08** [comment]
Yea seems like there was an issue with giving out the item on obtainance. Will be fixed with the next maintenance.

As for you, I'll hand the item out to you manually.

**Comment by Dispenz0r** [comment]
Given you the AR Emitter back now.
