### ISSUE TITLE
Credit Printer's can't be used

### ISSUE THREAD

**Issue by V1NAlt** [DFS-Servers/BugReportsAndSuggestions#44]
**Describe the bug**
My Gold Printer won't spawn even when there is none present by me. The bug carries on even if I leave, restart my TF2 client, or go through a map change.

**Expected behavior**
Usually printers should spawn once they are used.

**Screenshots or error logs**
>_You already have an active printer!_
>Only used one today that disappeared suddenly after switching teams.

**Server Info (please complete the following information):**
 - Region: USA | VA
 - IP 198.24.171.83:27185

(It does work on the EU server tho)

**Comment by Light08** [comment]
I'll likely rewrite the Printer mechanic in the coming weeks since there are certain stuff I don't like about it, causing a few issues as well.

Anyway, I fixed the issue regarding printers. Should work now again.

**Comment by Dispenz0r** [comment]
Given you a Community box now, thanks for reporting!
