### ISSUE TITLE
dr_retroland_fix progression stopper

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#45]
**Steam Profile**
https://steamcommunity.com/id/thatlimey/

**Describe the bug**
The floor that disappears on the 5th trap is constantly missing, making progressing impossible.

**To Reproduce**
1. Reach the 5th trap of the map

**Expected behavior**
The floor of the 5th trap will be missing.

**Screenshots or error logs**
![image](https://user-images.githubusercontent.com/42521633/44963051-62215a00-af1f-11e8-9def-18a1fbfa6080.png)

**Server Info (please complete the following information):**
USA | VA - 198.24.171.83:27185

**Additional context**
The 5th trap can still be used, pulling players into the pit. The floor will not respawn after using the trap.

**Comment by GreenSwede** [comment]
Fixed yesterday.
