### ISSUE TITLE
Pet status not saving.

### ISSUE THREAD

**Issue by TheRealNexion** [DFS-Servers/BugReportsAndSuggestions#47]
So after joining EU | UK today, I've noticed quite an annoyance.

When I first joined, I noticed my pet missing, I typed /pet, and it was put away, so I sent it out.
Only to notice that after mapchange, it was back to put away again, pet status doesn't save over from mapchanges, at least for me. We've had 10 mapchanges or so since joining today, it only transfered the "Sent Out" status on one map change, the rest, I had to resend out every single mapchange. Will keep looking out in case it keeps happening, if it does, I'll edit later on.

**Comment by Dispenz0r** [comment]
Gonna need a confirmation on if this issue still happens or not

**Comment by TheRealNexion** [comment]
Just tested, it happened again. Seems to happen mostly on friendly maps.

**Comment by Light08** [comment]
I probably know why. Will be addressed soonish.

**Comment by Light08** [comment]
Fixed. (Hopefully)

**Comment by Dispenz0r** [comment]
Given a Community Box now, thanks for reporting!
