### ISSUE TITLE
Backround01 on USA AZ

### ISSUE THREAD

**Issue by biguty** [DFS-Servers/BugReportsAndSuggestions#49]
I was on USA VA and decided to redirect to USA AZ to be all alone and then on the loading screen it didn't say what map i was going to. When I got into the server I saw that the map was on backround01, now i'm pretty sure backround01 is not in the nomination pool for DFS so i'm assuming its a bug. Now if it is a bug it should be fixed to make sure the map wont change to backround01 instead of an actual map.

Server Info

Region: USA|AZ
IP: 184.171.161.67:27015

**Comment by Dispenz0r** [comment]
lol woops i was testing something
