### ISSUE TITLE
Credits Achievement process broken

### ISSUE THREAD

**Issue by Kray0la** [DFS-Servers/BugReportsAndSuggestions#5]
**Steam Profile**
https://steamcommunity.com/id/pikalenni95/

**Describe the bug**
Pretty easy, the process was reset after the update. I was about 40-45% before it was reset.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots or error logs**
https://i.imgur.com/v5V17Ei.png

**Server Info (please complete the following information):**
Any

**Additional context**
Reports from others (e.g. Limey) have the same problem

**Comment by Light08** [comment]
Already fixed in the current devbuild.
