### ISSUE TITLE
Cooldown on Randomiser

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#50]
We all feel that Randomiser is voted too often lately. Yeah, we know it's new, but it tends to get annoying when people want to clear quests.

And when it's enabled, there's almost instantly a vote to turn it off. After about 2 minutes of playing, there's another one that appears, saying that it should be turned on again.

I'd recommend the cooldown for the vote to enable/disable Randomiser to be 15 minutes, so it's not spammed so much.

Thanks for reading and I love you guys! (No homo)

**Comment by Dispenz0r** [comment]
@Light08 Said he set it to 15 minutes or so, might be an issue with the plugin itself.

**Comment by Light08** [comment]
Fixed.

**Comment by Dispenz0r** [comment]
Given a Community Box now, thanks for reporting!
