### ISSUE TITLE
Plugin to remove advertisement from player's name

### ISSUE THREAD

**Issue by BrightBabyYoshi** [DFS-Servers/BugReportsAndSuggestions#51]
**Is your feature request related to a problem? Please describe.**

Obviously, The problem with tags is that they're basically **free advertising** to other servers/websites and since it's stupid to tell someone to remove it just to play on DFS, the solution would be to make the process automatically with the usage of a plugin.

**Describe your suggestion**

It's simple, all you need is a plugin that remove said websites/server tags from player's name to avoid **free, nonpunishable advertising**.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by ramunecarbonated** [comment]
disp summoned me

**Comment by Dispenz0r** [comment]
haha yes

do your beautiful magic

**Comment by ramunecarbonated** [comment]
will be taken care of next maintenance

**Comment by ramunecarbonated** [comment]
ok cya next maintenance

**Comment by Dispenz0r** [comment]
Given a Community Box now, thanks for the suggestion!
