### ISSUE TITLE
Title Change

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#52]
**Is your feature request related to a problem?**
It's not really that big of a deal, but another title to replace 'Lucky' would be a good idea, since we have 2 of them for different badges.

**Describe your suggestion**
Maybe change one of the badge titles to something else, like 'Collector' for the Credit Pile badge?

**Additional context**
![untitled](https://user-images.githubusercontent.com/42520820/45269855-d3678c80-b48c-11e8-926a-98c7296b7323.png)
![2](https://user-images.githubusercontent.com/42520820/45269857-d6fb1380-b48c-11e8-98aa-31961c613cc0.png)
As you can see, they are different badges, but have the same title on them.

**Comment by Light08** [comment]
Fixed.

**Comment by Dispenz0r** [comment]
Given a Community Box now, thanks for reporting!
