### ISSUE TITLE
Auctionhouse not working properly 

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#53]
**Steam Profile**
https://steamcommunity.com/id/vilxxu/

**Describe the bug**
The bug is that auctionhouse listing are not showing

**To Reproduce**
1. I tried the auctionhouse with niko 
2. We both put a module on sale
3. Items not showing up
**Expected behavior**
That the module would show up like it's supposed to

**Server Info (please complete the following information):**
 - Region: [EU]
 - IP [89.35.29.11:27145]

**Comment by Dispenz0r** [comment]
Should be fixed now.

Given a Community Box as well, thanks for reporting!
