### ISSUE TITLE
Surviving the Pits in some maps?

### ISSUE THREAD

**Issue by Sayo-nnamin** [DFS-Servers/BugReportsAndSuggestions#55]
**Steam Profile**
https://steamcommunity.com/id/TFORTRESS2035/

**Describe the bug**
(Gold and Above only) When I turn off Fall Damage in the gold menu and go into a pit, like, tm_stadium's Crumbling Castle's pit, or tfdb_blockland_v5_4, I can actually survive it.

**To Reproduce**
1. Open the Gold Menu
2. Turn Off Fall Damage
3. Fall into a pit

**Expected behavior**
Automatically die from the trigger_hurt.

**Screenshots or error logs**
![20180912214722_1](https://user-images.githubusercontent.com/42822663/45467633-77437900-b6d5-11e8-8eae-e99c3a0795a5.jpg)
 ![20180912203051_1](https://user-images.githubusercontent.com/42822663/45466108-08622200-b6cd-11e8-89a3-359c558eacf3.jpg)
![20180912214653_1](https://user-images.githubusercontent.com/42822663/45467614-6266e580-b6d5-11e8-9e51-ae2b2aba62f5.jpg)

**Server Info (please complete the following information):**
 - Region: US | VA
 - IP 198.24.171.83:27185

**Additional context**
This has actually happened before with me and Nexion on tm_stadium's Crumbling Castle, where I think I turned fall damage off beforehand, and then just walked into the pit, surviving.

**Comment by Light08** [comment]
Not a bug. That's how disabled Fall Damage works. These triggers use Fall Damage to kill people after all.

**Comment by Dispenz0r** [comment]
Re-opening because this is still an issue. We should probably remove the fall damage option from this plugin completely.
