### ISSUE TITLE
Quests changing on their own

### ISSUE THREAD

**Issue by Leafpad** [DFS-Servers/BugReportsAndSuggestions#57]
**Steam Profile**
A link to your Steam profile (optional).

**Describe the bug**
More than once I have had a quest that when I log off then log back in hours later it changes to a different quest. I've only seen this happen on daily quests, and it seems to only be quests without progress on them

**To Reproduce**
Accept a daily quest
Exit quest menu
Log off
Come back on a few hours later
Check the quest

**Expected behavior**
The quests are supposed to stay the same

**Comment by Leafpad** [comment]
The most recent instance of this was when I accepted a Pyro quest this morning, then I come back online hours later without interacting with the quest menu outside of accepting the Pyro quest and find that it has somehow changed into a Spy quest

**Comment by Light08** [comment]
Fix coming Monday. Thx for reporting.

**Comment by Dispenz0r** [comment]
Given a Keyless Community Box, thanks for reporting!
