### ISSUE TITLE
Issue / item commands can spot ph players

### ISSUE THREAD

**Issue by Grandpa-niko** [DFS-Servers/BugReportsAndSuggestions#59]
**Steam Profile**
https://steamcommunity.com/id/nikoiro680

**Describe the bug**
![screenshot_1](https://user-images.githubusercontent.com/42687863/45646272-38c50a00-ba99-11e8-819d-00df33f1a968.png)

Yes I know It sounds stupid but, Yes ,this can be abused to spot ph players ,specially items like luminous lantern where you can simply use spectator and spot the red team by the light around them (no pun intended, okay light)

**To Reproduce**
Luminous lantern:
1.have a luminous lantern
2. use it when you are alive (be sure to use it before round ending)
3. go to spectator
4. try to spot your nemesis red player
5. profit? no that's bad.

**Expected behavior**
it's actually annoying if you feel spotted by items like this
Blank was almost a victim by someone that was using luminous lantern and the light was simply showing for him , this would reveal the player's position and a easy way for blu team to spot them

**Screenshots or error logs**
Not yet.

**Server Info (please complete the following information):**
 - Region: All servers

**aditional information**
now this is one item that i only know this would be abusable in ph, there may be more, i will do edits if other items can also spot ph players

**Comment by Light08** [comment]
Disabled now.

**Comment by Dispenz0r** [comment]
Given a Keyless Community Box, thanks for reporting!
