### ISSUE TITLE
Issue + Suggestion | Broken particles?

### ISSUE THREAD

**Issue by Grandpa-niko** [DFS-Servers/BugReportsAndSuggestions#60]
> Grandpa niko: I should calm down with reporting issues.

.
**Steam Profile**
https://steamcommunity.com/id/nikoiro680
**Describe the bug**

> Suggestion idea at Additional context

There are some module particles that are not working at all.
After maintenance I bought The coldhand particle module from the auction,
So far I tested it and didn't show up,not sure about the rest of the particles.
few of the staff (during game) confirmed me that it's not showing it neither ,even after respawning (suicide or change team)
**To Reproduce**
Very self explanatory
1.Be sure to have coldhand particle
2. /pack > modules > attachment particles > coldhand particles >enable
3. See results, pretty much it is impossible to see?

**Screenshots or error logs**
![20180917210324_1](https://user-images.githubusercontent.com/42687863/45657022-09c18f00-babf-11e8-9b43-0f96a9fd32c5.jpg)

**Server Info (please complete the following information):**
 - Region: [tested in EU|UK after maintenance]
 

**Additional context**
now Here goes a little suggestion for this thread
Yes this is new and shouldn't be important, But I would like if we can have a public Issue Github thread to post only broken particles from modules like this one
This would make people simply go to a single specific thread to post broken modules (like this attachment particle) and not fullfill the the Issue threads in general.
better ideas?

**Comment by Light08** [comment]
It's as if you were implying there are multiple broken particles.

**Comment by Grandpa-niko** [comment]
As I said, This shouldn't be important for that suggestion,I'm actually trying different modules if they are working, because obviously no one knows about the rest of modules unless tested,simply after buying the coldhand particle it got me curious,so I just need more luck for unboxing more modules and not duplicates, so I can at least place them here as a side comment and not place it as a completely different thread

**Comment by Dispenz0r** [comment]
Should be fixed now, thanks for reporting!

Given a Community Box as well.

**Comment by Light08** [comment]
Except I never even mentioned I fixed it. I said I'll look into it.

**Comment by Dispenz0r** [comment]
My mistake, confused particles with trails.

In either case the Particles *are* there, they're just barely visible. we'll look into possibly replacing them in the future.
