### ISSUE TITLE
Server username non-advertisement plugin chat spam problem

### ISSUE THREAD

**Issue by Macwithav** [DFS-Servers/BugReportsAndSuggestions#61]
**Steam Profile**
https://steamcommunity.com/id/macwithavengence/

**Describe the bug**
The non-advertisement username plugin spams the chat with several dozen messages if a user's name contains a potential advertisement.

**To Reproduce**
1. User joins the server
2. The plugin detects a potential advertisement starting with a "."
3. The chat is spammed with a huge amount of notification saying this person's name was changed, but their access to the server is denied. 
4. For example, "[DFS] 💎Honey Slime trade.tf changed name to [DFS] 💎Honey Slime "
-"crouton.net [DFS] changed name to  [DFS]"

**Expected behavior**
The notification comes up once, and (I'm not quite sure how the plugin is meant to run 100%) and the user is able to join, but their name is still changed to not have the advertisement in their name. If they attempt to change their name back, the plugin will keep reverting the change automatically.

**Screenshots or error logs**
https://i.imgur.com/gm5AQzu.png

**Server Info:**
 - US | VA
 - 198.24.171.83:27185

**Comment by ramunecarbonated** [comment]
will fix and discipline my plugin when my commute is done and i get that morning coffee 👷

**Comment by ramunecarbonated** [comment]
plugin adjusted to no longer go into a loop when the name change event from the engine is fired. should be uploaded when disp wakes up and has time to do so.

to correct some misinformation in advance: the plugin **only strips**, it does **not kick**

**Comment by Dispenz0r** [comment]
Given a Keyless Community Box, thanks for reporting!
