### ISSUE TITLE
Problem with custom weapons

### ISSUE THREAD

**Issue by BrightBabyYoshi** [DFS-Servers/BugReportsAndSuggestions#62]
**Steam Profile**

No need.

**Describe the bug**

Custom weapons from "/c" gets replaced with your own equipped weapons upon dying or hitting the resupply locker when it shouldn't.

**To Reproduce**

1. Equip a custom weapon;
2. Die or touch the resupply locker;
3. Custom weapon is gone until unequipped and equipped again while on spawn.

**Expected behavior**

For the custom weapons to not be replaced with your own weapons upon dying or touching the resupply locker as it used to be.

**Screenshots or error logs**

VA: https://i.imgur.com/SdBdUWO.jpg
AZ: https://i.imgur.com/eA8GQ5C.jpg
DE: https://i.imgur.com/Cz7CxG0.jpg
UK: https://i.imgur.com/Px1pwNG.jpg

The Bane (That uses the default SMG model) shows that it's equipped but instead i have my equipped SMG (Which is the Cleaner's Carbine), screenshots show the custom weapons on the ground after hitting the resupply locker.

**Server Info (please complete the following information):**
 
Happens on all four servers.

**Additional context**

Not sure if it is intended or not but it's really annoying to keep having to reequip custom weapons whenever you die or get heal/ammo from the resupply locker.

**Comment by Dispenz0r** [comment]
Should hopefully be fixed now, thanks for reporting.
