### ISSUE TITLE
Shapeshift Übercharge issue

### ISSUE THREAD

**Issue by Welzhum** [DFS-Servers/BugReportsAndSuggestions#63]
**Steam Profile**
https://steamcommunity.com/id/j01nth34c1d

**Describe the bug**
Whenever you spawn as a class that isn't Medic, and swap to the aforementioned class in the same life, activating an Übercharge will change your class back to the one you spawned as after it expires. I'm assuming this is a problem with the Shapeshift plugin.

**To Reproduce**
1. Spawn as someone except the Medic.
2. Change classes to Medic via "sm_setclass user Medic"/the game's change class menu **outside of spawn** [The latter only works for Gold members and above, since Shapeshift doesn't trigger for normal users].
3. Activate an Übercharge.
4. At the end of it, your class will be reverted to the one you've spawned as.

**Expected behavior**
When the über expires, the user should remain as the Medic.

**Screenshots or error logs**
Not exactly a screenshot, but rather footage of the bug in process. https://www.youtube.com/watch?v=2Eu9RjN28XI

**Server Info**
 - Region: US|VA
 - IP : 198.24.171.83:27185
 - This bug happens regardless of the server one is on.

**Additional context**
If you spawn as a Medic, swap to another class, then change back to Medic and apply the Übercharge, this won't apply since you've spawned as the Medic.

**Comment by Dispenz0r** [comment]
Seems like a minor issue? Not something we can currently look into, sorry.
