### ISSUE TITLE
Allowance plugin suggestion.

### ISSUE THREAD

**Issue by TheRealNexion** [DFS-Servers/BugReportsAndSuggestions#64]
So, as the title implies, I have a suggestion for allowance.

We all know how allowance works now, there are two options, one that is player specific, and one that enables global damage. Now the problem is, the global option makes it so players who have allowance off can also hurt you. My idea is: change how global damage works, instead of making it entirely global, set it so only players that also have global damage enabled can hurt you.

Could also try to make allowance more present by giving players a popup when spawning in friendly maps, like: "Would you like to remain friendly, or turn damage on? (This can be changed later at any time with /allowance)"

**Comment by Light08** [comment]
Good suggestions. I'll implement it sometime this month hopefully.

**Comment by Light08** [comment]
Done and updated.
Expect some more changes towards it the coming weeks.

**Comment by Dispenz0r** [comment]
Given a Community Box, thanks!
