### ISSUE TITLE
Weekly Assists

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#65]
**Is your feature request related to a problem:**
Perhaps.
Well, those kill quests you get where you have to get 300+ kills as a certain class. Basically, you have to land the finishing blow to score the point, which can be unfair if people start to kill steal from you.

**Describe your suggestion:**
A good idea would be to add assists to the weekly as well, since it is a large number of kills to achieve. People who would be good at comp are more likely to complete this in a week than others, so people who are not the best will still be able to complete this. It would also be better since you get credited for the kill too. It could help people not to complain about kill steals that much.

**Describe alternatives you've considered:**
N/A, sry. :<

**Additional context:**
It probably would put less stress on people while playing comp, since some of them probably like to complete their weeklies before the next batch arrive.

**Comment by Light08** [comment]
Might as well enable it for all quests. Will consider.

**Comment by Dispenz0r** [comment]
Given a Community Box now, thanks for the suggestion!
