### ISSUE TITLE
Medic quest not counting assists

### ISSUE THREAD

**Issue by MrEdzilla** [DFS-Servers/BugReportsAndSuggestions#67]
Simple enough: _Get 7 kills or assists as Medic_. However, despite the game clearly indicating that I had assisted someone in killing an enemy, the quest would not count them. However, whenever I got kills, either through the Crossbow, the Solemn Vow or environmental kills, then it would count them. First time it has happened to me, I have done Medic quests before and they all counted assists.

**Comment by MrEdzilla** [comment]
**UPDATE:** This is something that is happening with every class. If would seem that the update that was meant to have the assists counted for every class ended up removing that ability from the Medic.

**Comment by Light08** [comment]
Consider it fixed very soon, mostlikely on next (daily) restart.

**Comment by Dispenz0r** [comment]
Given a Community Box now, thanks for the bug report!
