### ISSUE TITLE
Dr_Playstation

### ISSUE THREAD

**Issue by Leafpad** [DFS-Servers/BugReportsAndSuggestions#68]
Update Dr_Playstation plz. There are so many bugs that are fixed with the most recent update. Plz and Thnx

**Comment by Dispenz0r** [comment]
ok


soon 😄

**Comment by Grandpa-niko** [comment]
Seems like /mm fucks up some stuff in the map, after should post some video here that prove them a problem with the plugin
Pretty much it should be disabled?

**Comment by Afterstormer** [comment]
Shameless advertising, but vids have arrived:
https://www.youtube.com/watch?v=i5rE9vxTa9c
https://www.youtube.com/watch?v=1z-Tl8KqfGs&t=8s
https://www.youtube.com/watch?v=WBRrRwa2pEk
https://www.youtube.com/watch?v=DT6K0jfPDRc
Disable /mm kthx. :>

**Comment by Dispenz0r** [comment]
I'm aware of these issues as well, /mm and any other conflicting plugins will be disabled along with the map update sometime soon.

**Comment by Dispenz0r** [comment]
Map is now updated, other plugins shouldn't conflict with it anymore.

Thanks for reporting!

**Comment by Dispenz0r** [comment]
Given a Community Box now
