### ISSUE TITLE
Random Crit?

### ISSUE THREAD

**Issue by biguty** [DFS-Servers/BugReportsAndSuggestions#69]
My steam profile is here https://steamcommunity.com/id/maxxproffithaltmann/

Suddenly when I was fighting someone they got a random crit on me even though they are meant to be disabled.

I was on mario_kart_deluxe and was gonna kill someone with my minigun, they whipped out their frying pan and started hitting me with it and suddenly they got a random crit even though they are "disabled".

Random crits are expected to not occur anymore after the prime update. 

Unfortunately, I don't have any screenshots.

The region is EU|UK.
The IP is 89.35.29.11:27145.

No additional context.

**Comment by WicopeeDot** [comment]
[fixed grammar]

**Comment by Dispenz0r** [comment]
That's because random crits are enabled on melee weapons for custom gamemode balance related reasons.

Closing this.
