### ISSUE TITLE
/mm and /bonemerge are enabled on comp maps

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#7]
On the previous map, which was dr_office, I had a Big Smoke model on my Heavy. When the map changed to mario_kart_deluxe_v3, I realised that I still had the model enabled. Callie informed us that bonemerge was disabled, so I tried to do the command, but it was enabled. Even though this seems harmless at first, this could cause some problems with people either equipping the Kirby model, or using the Popuko model with bonemerge to create small models which will be hard to see.

**Comment by Dispenz0r** [comment]
Is bonemerge and mm specifically enabled on this map only? Or other comp maps as well?

**Comment by Afterstormer** [comment]
I'm not sure. This is the only map that I've encountered this on.
When the next comp map comes, I'll test it on there as well.

**Comment by Afterstormer** [comment]
Okay, I tested it on ctf_facing_worlds_2011 and it seems to be disabled there, so it may be just mario_kart_deluxe_v3 that has this enabled.

**Comment by Dispenz0r** [comment]
Should be fixed with the next server maintenance, thanks for reporting!
