### ISSUE TITLE
Activated Particles Not Appearing

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#70]
**Describe the Bug:**
If you activate a particle, sometimes they won't appear on your character, which will require you to re-equip it.

**To Reproduce:**
1. Select a particle, whether it be footprints or attachments.
2. Activate it.
3. After enough time passes, the particle will not show.

**Expected Behaviour:**
The particle should stay on you 24/7.

**Screenshots or Error Logs:**
![untitled](https://user-images.githubusercontent.com/42520820/47607005-8d519280-da12-11e8-84bd-1ce92b1e3498.png)
(Note that I am moving in this picture.)

**Server Info:**
 - Region: [EU | UK]
 - IP: 89.35.29.11:27145

**Additional context**
I'm pretty sure that this affects all particles, as I was supposed to have the 'Twinkle Star' attachment on my character as well.

**Comment by Afterstormer** [comment]
I know this issue is pretty damn old, but I realised that this is only affected on the Slender Fortress gamemode. All others run the particles fine.

**Comment by Dispenz0r** [comment]
Not much we can do in that case
