### ISSUE TITLE
Going to random map

### ISSUE THREAD

**Issue by Leafpad** [DFS-Servers/BugReportsAndSuggestions#71]
The server going to a random map if the round has ended before a map vote has occurred. this not only occurs in the Slender maps, but also occurs in the Zombie maps as well. This has now become a more common thing. Can we get this fixed plz?

**Comment by Dispenz0r** [comment]
A little more detailed explanation if you could please.

**Comment by Leafpad** [comment]
If the round ends before the map vote has time to come to a conclusion, then the server will pick a random map and load it in. This not only happens on Slender but now happens on SZF as well. I don't exactly know what goes on with it

**Comment by Dispenz0r** [comment]
Our mapchooser plugin might be conflicting with SZF/Slender for some reason. Not sure about Slender but I'll try to investigate why it happens on SZF with @ramunecarbonated.

**Comment by ramunecarbonated** [comment]
mp_maxrounds? this not caused by szf

**Comment by Dispenz0r** [comment]
Should be somewhat fixed now, thanks for reporting.
