### ISSUE TITLE
Carnival of Carnage treated as a friendly map

### ISSUE THREAD

**Issue by Nevicate** [DFS-Servers/BugReportsAndSuggestions#72]
Carnival of Carnage (sd_doomsday_event) is currently a friendly map when it is supposed to be a comp map. Normal players are not able to damage enemies, autojump/double jump work, and friendly map commands such as /kartme can be used. 

I've only seen this happen on USA|AZ, so I'm not sure if the same issue is happening on EU|DE.

**Comment by WicopeeDot** [comment]
Possibly a bug. Awaiting Dispenz0r's or highly-leveled developer's response.

**Comment by Dispenz0r** [comment]
Should be fixed now, thanks for reporting.

**Comment by Dispenz0r** [comment]
Given a Community Box now
