### ISSUE TITLE
RTD option "Spawn a sentry" is functionable in friendly-mode

### ISSUE THREAD

**Issue by WicopeeDot** [DFS-Servers/BugReportsAndSuggestions#73]
RTD option "Spawn a sentry" is functionable and you can build one while being friendly.
I only saw this bug in action at EU | UK server.

**Comment by Dispenz0r** [comment]
Nothing much I can do about it, I'll probably try disabling "Spawn Sentry" effect itself a little later on.

**Comment by Dispenz0r** [comment]
Should be fixed now, other abusable rtd effects that bypass friendly and allowance have also been disabled.

Thanks for reporting.
