### ISSUE TITLE
Certain sounds begin to stop working over time

### ISSUE THREAD

**Issue by Macwithav** [DFS-Servers/BugReportsAndSuggestions#74]
**Steam Profile**
https://steamcommunity.com/id/macwithavengence/

**Describe the bug**
Over a certain period of time, certain sounds (not all, just very specific ones) begin to stop working while on DFS. Such as weapon hitsounds on world objects or players, deathcam zoom in sound effects, certain map sound effects such as spell roll sound effect on koth_lakeside_event (or spell effects in general), and several others. Snd_restart fixes this bug but it eventually comes back over time. 

**To Reproduce**
Joining in a map eventually leads to this bug taking place, it was evident on most of the maps on DFS, but it would take longer to manifest on certain maps over others, such as pit of death. As I said, snd restart manages to fix this bug but only for a certain amount of time. It also seems to only affect a certain amount of people as well, such as Strello and Calico. They said, similar to I, that these problems only manifested after the start of the Halloween update, so I imagine something added is causing a conflict or overwriting the sound of maps in general.

All of these people I mentioned above, myself included, have problems with the Dan-hands sound files not registering properly, which could be causing sound errors in general.

**Expected behavior**
Naturally one would expect everything to work fine, since sounds ceasing to work obviously shows something wrong with the way the server is registering sounds or certain files conflicting with those sounds.

**Screenshots or error logs**
The only thing I can think of is showing the problems in relation to the Dan-hand pet, as the sound files for several people haven't been registering properly in the console.

```
FF8800Dan-hand: Hello, Macwithavengence!
Dan-hand was sent out.
MP3 initialized with no sound cache, this may cause janking. [ dfs\pets\danhand_idle.mp3 ]
Failed to create decoder for MP3 [ dfs\pets\danhand_idle.mp3 ]
MP3 initialized with no sound cache, this may cause janking. [ dfs\pets\danhand_idle.mp3 ]
Failed to create decoder for MP3 [ dfs\pets\danhand_idle.mp3 ]
*** Invalid sample rate (0) for sound 'dfs\pets\danhand_idle.mp3'.
MP3 initialized with no sound cache, this may cause janking. [ dfs\pets\danhand_jump.mp3 ]
Failed to create decoder for MP3 [ dfs\pets\danhand_jump.mp3 ]
MP3 initialized with no sound cache, this may cause janking. [ dfs\pets\danhand_jump.mp3 ]
Failed to create decoder for MP3 [ dfs\pets\danhand_jump.mp3 ]
*** Invalid sample rate (0) for sound 'dfs\pets\danhand_jump.mp3'.
MP3 initialized with no sound cache, this may cause janking. [ dfs\pets\danhand_jump.mp3 ]
Failed to create decoder for MP3 [ dfs\pets\danhand_jump.mp3 ]
MP3 initialized with no sound cache, this may cause janking. [ dfs\pets\danhand_jump.mp3 ]
Failed to create decoder for MP3 [ dfs\pets\danhand_jump.mp3 ]
Invalid sample rate (0) for sound 'dfs\pets\danhand_jump.mp3'.
```

**Server Info (please complete the following information):**
 - All of the servers seem to be affected with this bug

**Additional context**
I recommend looking into how the Dan-hands sound files converted, since this could be causing problems with other people who may be having difficulty properly downloading them.

**Comment by ramunecarbonated** [comment]
Did you delete your `sound.cache` inside the tf2 folders?

**Comment by ramunecarbonated** [comment]
Did you delete your `sound.cache` inside the tf2 folders?

**Comment by Macwithav** [comment]
Yes, I should have clarified that this was similar to snd_restart, only a temporary fix.

**Comment by Dispenz0r** [comment]
Did you delete all of the `sound.cache` files in your tf folder? There are more than just one so just making sure.

As for the error logs, pinging @NeppuTennouboshi

**Comment by NeppuTennouboshi** [comment]
The Dan-hand sound files i made were exported like any other DFS sound, 32-bit float 44100Hz MP3s, They should be working (and they are for me) and they definitely don't have a 0hz sample rate. This should be fixed with removing sound.cache files but apparently that didn't work, so I'm not sure what's going on here considering there's nothing wrong with the files themselves as well as no one else reporting the issue. One command I'm thinking of is snd_rebuildaudiocache, I'm not sure if that'll help, but it's worth a try.

**Comment by Dispenz0r** [comment]
No response has been received for 14 days, I'll be closing this.
