### ISSUE TITLE
Player Title Doesn't Appear

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#75]
**Describe the Bug:**
Apparently, the titles don't appear on my screen when I select one.

**To Reproduce:**
1. Go to /profile.
2. Go to "Options".
3. Go to "Player Customisation".
4. Go to "Change Title".
5. Select a title.

**Expected Behaviour:**
The title would appear in the top-left of your screen alongside your level and status.

**Screenshots or Error Logs:**
![untitled](https://user-images.githubusercontent.com/42520820/48017684-d72f2c80-e126-11e8-8cdd-971ba75355aa.png)
(Note that the "Party" title doesn't show in the top left, but it does in the profile window.)

**Server Info:**
 - Region: [EU | UK]
 - IP: 89.35.29.11:27145

**Additional Context:**
I tried this with the "Online" and "Hunter" titles, but they had the same outcome, not showing up in the top-left of the screen.

**Comment by Light08** [comment]
Already taken care of.

**Comment by Dispenz0r** [comment]
Given a Community Box now
