### ISSUE TITLE
Medic building ubercharge at an accelerated rate during normal gameplay, the same rate as in the setup phase

### ISSUE THREAD

**Issue by Caliico** [DFS-Servers/BugReportsAndSuggestions#77]
**Steam Profile**: https://steamcommunity.com/id/calico1/

**Describe the bug**: During normal gameplay on payload maps, medic builds uber at the same accelerated rate as he would in the setup phase. I could build an uber during a normal round for instance, in less than 15-20 seconds or so.

**To Reproduce Describe the steps to reproduce the bug**

Firstly, we went on a payload map like pl_metropolis
Then, the **vote at the start of the map to switch to stop that tank or normal payload resulted in normal payload.**
Afterwards once the setup phase was over, medic retained his accelerated uber build rate into the actual match.

**Expected behavior:** Once setup phase was over, medic was supposed to revert back to his slower, normal uber build rate that was to be expected in an actual match.

**Screenshots or error logs:**
![20181109221215_1](https://user-images.githubusercontent.com/44916244/48297728-facadd80-e46c-11e8-80bb-71b1d4fdccc8.jpg)
![20181109221228_1](https://user-images.githubusercontent.com/44916244/48297730-ff8f9180-e46c-11e8-8781-99bb183f0c2e.jpg)

**This is a comparison of the charge rates at the bottom, and the timers on top of both screenshots to showcase just how quickly uber was built during a normal match**
**Server Info (please complete the following information):**

Region: USA | VA
IP: 198.24.171.83:27185
**Additional context**: Have not yet tested this on stop that tank,or on other payload/competitive maps.

**EDIT: Tested out on koth and normal pl maps, overall problem seems to lie in maps that support stop that tank and when people vote for normal payload in those maps specifically**

**Comment by konkey** [comment]
Fixed.

**Comment by Dispenz0r** [comment]
Given a community box now, thanks for reporting!
