### ISSUE TITLE
BUG: Player models available on mariokart_v3_deluxe & possibly other comp maps ?

### ISSUE THREAD

**Issue by miniz1994** [DFS-Servers/BugReportsAndSuggestions#8]
Hello -M-m- here
Seems playermodels on this map is available during comp at the moment in mariokart_v3_deluxe.

https://steamcommunity.com/sharedfiles/filedetails/?id=1485873499

Just got off the end of a deathrun map & still had the model equipped.

**Comment by Light08** [comment]
Duplicate of #7 .
