### ISSUE TITLE
new first aid weekly error

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#80]
**Steam Profile**
https://steamcommunity.com/id/vilxxu/

**Describe the bug**
Display error on the first aid quest (the 1k healing in 1 life one)

**To Reproduce**
1. gain the first aid quest weekly
2.attempt to view it's stats
3. inability to view it's stats

**Expected behavior**
The ability to view it

**Server Info (please complete the following information):**
 - Region: [US AZ]
 - IP [ 184.171.161.67:27015]

**Additional context**
This bug is minor and not majorly disrupting

**Comment by Dispenz0r** [comment]
Should be fixed now, thanks for reporting.

Given a Community Box as well.
