### ISSUE TITLE
[PLUGIN] /vehicle making people crash.

### ISSUE THREAD

**Issue by RealStrade** [DFS-Servers/BugReportsAndSuggestions#81]
**Describe the bug**

The new plugin released during the xmas update, /vehicle, is causing people to crash when using it in a certain way. After that, the vehicle itself disappears and it becomes impossible for the spawner to use the command again (the vehicle is considered as still there, and can't be despawned).

**To Reproduce**

1) Spawn a vehicle.
2) Enter the vehicle.
3) Suicide inside the vehicle.
4) Go to spectator.

**Expected Behaviour**

People shouldn't crash from that series of commands, and the plugin should be expected to work at any time.

This bug leaves no retrievable error on the console and is expected to happen on every server.

**Comment by konkey** [comment]
This should be fixed now, let us know if the issue persists!

**Comment by Dispenz0r** [comment]
Given a community box now, thanks for reporting!
