### ISSUE TITLE
Defensive survival quest not counting snatcher even though  conditions match

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#82]
**Steam Profile**
https://steamcommunity.com/id/vilxxu/

**Describe the bug**
The bug is that the campaign quest not counting the kill

**To Reproduce**
1. Gain access to the defensive survival quest
2. Fight snatcher as a defensive class like heavy
3. beat snatcher as heavy while surviving it
4.Go through the portal
5. quest has not gained progress

**Expected behavior**
finishing the quest.

**Screenshots or error logs**
https://steamcommunity.com/sharedfiles/filedetails/?id=1603421839
https://steamcommunity.com/sharedfiles/filedetails/?id=1603422072

**Server Info**
 - Region: [EU]
 - IP [89.35.29.11:27145]

**Additional context**
I've beaten snatcher twice like this

**Comment by Dispenz0r** [comment]
Should be fixed now, thanks for reporting.

Given a Community Box as well.
