### ISSUE TITLE
Can't reroll quest after accepting new one

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#85]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
If an quest is swapped for a new one using the command /newquest, the quest cannot be rerolled using /rerollquest until the player returns to the Quest Menu and opens the quest again.

**To Reproduce**
1. Open a Quest
2. Use /newquest to accept a new Quest
3. Attempt to use /rerollquest

**Expected behavior**
I expected that the new Quest would be rerolled. However, it did not and the message "No Quest selected." appeared in chat.

**Screenshots or error logs**
![hl2_2018-12-30_15-55-04](https://user-images.githubusercontent.com/42521633/50549168-01492a80-0c50-11e9-8090-0bc7808f824a.png)

**Server Info (please complete the following information):**
EU | UK: 89.35.29.11:27145

**Comment by Light08** [comment]
Aware of it since I did the change. It's due to the way it reopens and closes the menu. I'll probably redirect the command usage back to the Quest Board until I find a better solution next year.
