### ISSUE TITLE
Snatcher Voice Lines still occur after disabled Death Wish Campaign

### ISSUE THREAD

**Issue by Kray0la** [DFS-Servers/BugReportsAndSuggestions#86]
**Describe the bug**
Snatcher Voice lines still play on occasion after death from the client. They sometimes also play globally when playing on Slender if a player respawns in the BLU Waiting room. The sound files still exist in the DFS sound folders.

**To Reproduce**
Current causes for this are unknown. They seemingly play at random after death and that's all there's to it.

**Expected behavior**
N/A

**Screenshots or error logs**
N/A

**Server Info (please complete the following information):**
Any server

**Comment by Light08** [comment]
Impossible to play since campaign isnt live and it relies on the soundfiles from the active campaign (current one has none).

**Comment by Kray0la** [comment]
After a bit of testing, it seems it was just my illusion. Slender does feature Snatcher, and his vocal lines were played for BLU as well. Please close this issue.
