### ISSUE TITLE
Nerf Escape Plan for SZF

### ISSUE THREAD

**Issue by Kray0la** [DFS-Servers/BugReportsAndSuggestions#88]
**Describe your suggestion**
Right now, the Escape Plan gives a too large speed boost upon equipping for the Soldier. The hammer units you travel with this thing is bigger than me sprinting to my burnt pizza in the oven. 

**Describe alternatives you've considered**
I cannot think of any. 

**Additional context**
Zombies have a hard time catching up with Soldiers. The escape plan is too effective as a "get out of jail" card.

**Comment by DrAzure** [comment]
Could have the speed boost slowly/steadily increasing as you have it out instead of instantly having max speed and/or have damage taken also increase with said speed. Just a thought

**Comment by ramunecarbonated** [comment]
> Could have the speed boost slowly/steadily increasing as you have it out instead of instantly having max speed and/or have damage taken also increase with said speed. Just a thought

Yeah I was thinking of that, along with it's speed's maximum being lowered. The plugin is made for tick-based status/changes like these so no risks are taken in implementing it like that.

**Comment by ramunecarbonated** [comment]
Has been addressed in the code, should be live sometime soon. @Dispenz0r should give you a fancy box after the change(s) are live.
