### ISSUE TITLE
Super zombie fortress gamemode not working

### ISSUE THREAD

**Issue by Pro100RedMushroom** [DFS-Servers/BugReportsAndSuggestions#89]
**Describe the bug**
-Currently the super zombie fortress gamemode plugin doesnt initiate when a szf_ map is being played

**To Reproduce**
1. i went to the szf_isaac map
2. upon loading we all noticed that we had received all of our weapons from the start and some of the elements such as hints and zombies wernt working

**Expected behavior**
-the gamemode is supposed to work

**Screenshots or error logs**
i couldnt take a screenshot during the time this happened due to some technical problems, but some of the witnesses are cxx, unicake and green giant

**Server Info (please complete the following information):**
 - Region: [e.g. EU UK]
 - IP [e.g. 89.35.29.11:27145]

**Comment by Pro100RedMushroom** [comment]
oh and also,
**Additional context**
this issue persisted through map changes (or in other words, it persisted even if you changed the current szf_ map to another szf_ map)

**Comment by ramunecarbonated** [comment]
done
