### ISSUE TITLE
Beach Bum pet replaced with Little Dispenz0r upon relog.

### ISSUE THREAD

**Issue by TheRealNexion** [DFS-Servers/BugReportsAndSuggestions#9]
So after internet went out and came back, I relogged and found myself owning a Little Dispenz0r in place of my Beach Bum.

**Comment by Dispenz0r** [comment]
Gonna investigate this further in tomorrow's maintenance.

**Comment by Dispenz0r** [comment]
You should have your Beach Bum pet back now.
