### ISSUE TITLE
BTG semi noclip bug

### ISSUE THREAD

**Issue by windflow5** [DFS-Servers/BugReportsAndSuggestions#90]
**Steam Profile**
https://steamcommunity.com/id/vilxxu/

**Describe the bug**
The bug is that you can go thru the fountain barriers with /btg Easily

**To Reproduce**
1. Do /btg in chat
2.Press mouse1 while looking at the fountain on stadium Directly
3. You are in the pit now.
**Expected behavior**
The barrier to stop from going thru

**Server Info (please complete the following information):**
 - Region: [EU UK]
 - IP [89.35.29.11:27145]

**Additional context**
/btg is just bad imo and should be removed due to this

**Comment by Light08** [comment]
Doesn't matter since you can't do anything anyway?

**Comment by windflow5** [comment]
Haven't tried if you can unghost there yet
