### ISSUE TITLE
DFS Xmas Tree 2017 Size and Texture Errors

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#91]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
The DFS Xmas Tree 2017 pet is exceptionally large and is missing textures.

**To Reproduce**
1. Bring out the DFS Xmas Tree 2017

**Expected behavior**

**Screenshots or error logs**
![hl2_2019-01-22_21-33-50](https://user-images.githubusercontent.com/42521633/51567829-19e3e380-1e90-11e9-9354-38fec3de73c6.jpg)

**Server Info (please complete the following information):**
EU | UK

**Comment by Limeball** [comment]
Forgot to fill out the Expected behaviour section:
The pet should be of a regular small size with its textures.

**Comment by Dispenz0r** [comment]
Should be fixed along with the small hotfix update coming today, thanks for reporting.

Keep in mind that the material files will have to be re-downloaded from the server to have the fixes applied properly.

Given a Community Box now.
