### ISSUE TITLE
Bombinomicon Pet Placement Error

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#92]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
The Bombinomicon pet sits in the ground.

**To Reproduce**
1. Take out the Bombinomicon pet

**Expected behavior**
The pet should be of a regular small size.

**Screenshots or error logs**
![hl2_2019-01-22_21-37-00](https://user-images.githubusercontent.com/42521633/51568072-c3c37000-1e90-11e9-8942-350f541ab5c0.jpg)

**Server Info (please complete the following information):**
EU | UK

**Comment by Dispenz0r** [comment]
Should be fixed along with the small hotfix update coming today, thanks for reporting.

Given a Community Box now.
