### ISSUE TITLE
Community Crate uncrating has broken text

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#93]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
Uncrating a Community Crate posts a bugged message in chat. The name is incorrectly displayed as "Keyless as".

**To Reproduce**
1. Use a Community Crate

**Expected behavior**
The crate's name in the uncrating message should be displayed as "Community Crate"

**Screenshots or error logs**
![hl2_2019-01-22_21-43-04](https://user-images.githubusercontent.com/42521633/51568581-f883f700-1e91-11e9-976f-afcf02bb1042.png)

**Server Info (please complete the following information):**
EU | UK

**Comment by Light08** [comment]
This is what happens when you leave the program open and accidentally smash some random buttons while having focus on it.
Will be hotfixed in a bit.

**Comment by Dispenz0r** [comment]
Thanks for reporting, given a Community Box now.
