### ISSUE TITLE
Retrobelle's Missing Textures

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#94]
**Describe the Bug:**
Apparently, Retrobelle's model has missing textures on her.

**To Reproduce:**
1. Choose Heavy
2. Pick the Retrobelle model using /mm

**Expected Behaviour:**
She should have the full textures enabled.

**Screenshots or Error Logs**
![untitled](https://user-images.githubusercontent.com/42520820/51568820-88c23c00-1e92-11e9-93e0-94524a5f9053.png)

**Server Info:**
Region: EU | UK
IP: 89.35.29.11:27145

**Comment by Dispenz0r** [comment]
Should be fixed along with the small hotfix update coming today, thanks for reporting.

Keep in mind that the material files will have to be re-downloaded from the server to have the fixes applied properly.

Given a Community Box.
