### ISSUE TITLE
Duo Boss Bug

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#96]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/, submitting this bug on behalf of https://steamcommunity.com/id/domegastar/

**Describe the bug**
If two players are on the server and a duo boss is selected, neither player will be able to re-join RED Team and must disconnect and rejoin to continue the game.

**To Reproduce**
1. With only 2 players on the server, spawn as a duo boss
2. End the round

**Expected behavior**
The next boss should remain on BLU Team while the other player is moved back to RED.

**Server Info (please complete the following information):**
US | VA

**Comment by Benoist3012** [comment]
Fixed thanks.

**Comment by Dispenz0r** [comment]
Given a Community Box now, thanks for reporting!
