### ISSUE TITLE
VSH: Buff Banner effect on Spy still persists

### ISSUE THREAD

**Issue by DarkDragonian** [DFS-Servers/BugReportsAndSuggestions#97]
**Steam Profile**
https://steamcommunity.com/id/Fatalita/

**Describe the bug**
Just like the header says, cloaked Spies on VSH still have a visible buff banner effect around them.
The issue might have been fixed before (under normal circumstances), however, the mini crit buff for being one of the last survivors applies to cloaked Spies as well.

**To Reproduce**
Read Description.
Be one of the last REDs alive when the control point is being unlocked.

**Server Info**
Should be affected by all servers but this one was tested in [USA | VA]

**Comment by Benoist3012** [comment]
This issue has been fixed in commit VSH-Rewrite@179fa251de93954070af631624ba5e4241c62573 (4 days ago).
Perhaps the fix wasn't applied everywhere at that time, but it was already known and fixed. Thanks for reporting anyways.

**Comment by Dispenz0r** [comment]
Community Box given now, thanks for reporting!
