### ISSUE TITLE
VSH Bosses with Engineer Buildings

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#98]
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
Bosses in VSH can have and use the Engineer's building PDA if the player was an Engineer and had a Building Toolbox out when their loadout is changed to that of the boss.

**To Reproduce**
1. Be an Engineer
2. Be selected as the boss
3. Equip your PDA and choose a building
4. Hold the Toolbox until you are given the boss weapon

**Expected behavior**
The player should only have the boss' weapon.

**Screenshots or error logs**
![hl2_2019-01-27_23-29-49](https://user-images.githubusercontent.com/42521633/51808560-7890cf00-228d-11e9-95f6-2de437cb7ec1.jpg)
A boss able to create buildings

![hl2_2019-01-27_23-34-28](https://user-images.githubusercontent.com/42521633/51808565-7dee1980-228d-11e9-81d3-a90a305832fa.png)
Having the Toolbox out as a boss

**Server Info (please complete the following information):**
EU | UK

**Comment by Benoist3012** [comment]
Very much appreciated, I had known about it but simply forgot ^^'
Thanks for the report. Fix shall be dispatched on the servers soon.

**Comment by Dispenz0r** [comment]
Community Boxxo given
