### ISSUE TITLE
VSH: Demo Charge on Round Start

### ISSUE THREAD

**Issue by Afterstormer** [DFS-Servers/BugReportsAndSuggestions#99]
**Describe the Bug:**
On the start of a VSH round, everyone's locked in place, right? But, when a Demo uses one of the shields, they can bypass their locked state and charge to an area until the meter runs out.

**To Reproduce:**
1. Pick Demo with a shield equipped
2. Wait until the start of a round
3. Charge during the countdown

**Expected Behaviour:**
You shouldn't be able to charge.

**Server Info:**
Region: EU | UK
IP: 89.35.29.11:27145

**Comment by ramunecarbonated** [comment]
Should be fixed for a future update.

**Comment by Dispenz0r** [comment]
Community Box given, thanks for reporting!
